// blog-data-extra.jsx — Artículos adicionales: accesorios + grooming

// Agregar categoría grooming a CAT_META
CAT_META['grooming'] = { label: 'Grooming', labelEn: 'Grooming', color: '#9C27B0', bg: '#F3E5F5' };

const BLOG_EXTRA = [
  // ── ACCESORIOS ───────────────────────────────────────────────────────────
  {
    id: 35, cat: 'guias', emoji: '🎒', color: '#F58220',
    title: 'Los 15 accesorios esenciales para el nuevo dueño de perro',
    titleEn: 'The 15 Essential Accessories for the New Dog Owner',
    sub: 'Lo que realmente necesitas desde el día uno — sin gastar de más',
    subEn: 'What you actually need from day one — without overspending',
    date: 'Mayo 2025', dateEn: 'May 2025', read: 7,
    tags: ['accesorios', 'cachorro', 'nuevo dueño', 'compras'],
    lead: 'Adoptar un perro por primera vez es emocionante y abrumador a la vez. El mercado tiene miles de productos, la mayoría innecesarios. Esta es la lista real de lo que sí necesitas desde el primer día — con criterios para elegir bien.',
    leadEn: 'Adopting a dog for the first time is exciting and overwhelming all at once. The market has thousands of products, most of them unnecessary. This is the real list of what you truly need from day one — with the criteria to choose well.',
    body: [
      { h: '1. Arnés (no collar) desde el inicio', hEn: '1. A harness (not a collar) from the start', p: 'El arnés distribuye la presión en el pecho en lugar del cuello, esencial para cachorros y razas con cuello delicado. El PetSafe Easy Walk o Ruffwear Front Range son los más recomendados por entrenadores. Nunca empieces con collar hasta que el perro camine sin jalar.', pEn: 'A harness distributes pressure across the chest instead of the neck — essential for puppies and breeds with delicate necks. The PetSafe Easy Walk and Ruffwear Front Range are the ones most recommended by trainers. Never start with a collar until your dog walks without pulling.' },
      { h: '2. Crate o jaula de entrenamiento', hEn: '2. A crate or training kennel', p: 'El crate no es una cárcel: es el hogar del perro dentro de tu hogar. Fundamental para el entrenamiento de baño, la gestión de ansiedad y viajes. Talla correcta: el perro debe poder ponerse de pie, girar y acostarse. Ni grande ni pequeño.', pEn: 'A crate is not a prison: it is the dog\'s home within your home. It is fundamental for potty training, managing anxiety, and travel. The right size lets the dog stand up, turn around, and lie down — neither too big nor too small.' },
      { h: '3. Cama ortopédica', hEn: '3. An orthopedic bed', p: 'Las camas de espuma de memoria previenen problemas articulares en el largo plazo. Razas grandes especialmente se benefician. Big Barker y Orvis son las marcas más respaldadas por veterinarios. Invertir aquí desde cachorro es prevención, no lujo.', pEn: 'Memory-foam beds prevent joint problems over the long term. Large breeds especially benefit. Big Barker and Orvis are the brands most endorsed by veterinarians. Investing here from puppyhood is prevention, not luxury.' },
      { h: '4. Dispensador interactivo de comida (KONG)', hEn: '4. An interactive food dispenser (KONG)', p: 'El KONG Classic es probablemente el mejor accesorio que existe. Rellénalo con comida húmeda o mantequilla de maní y congelado ocupa al cachorro 20-40 minutos. Imprescindible para crate training, horas solas y estimulación mental diaria.', pEn: 'The KONG Classic is probably the best accessory there is. Fill it with wet food or peanut butter and, frozen, it keeps a puppy busy for 20-40 minutes. Indispensable for crate training, hours alone, and daily mental stimulation.' },
      { h: '5. Slow feeder o comedero antiansiedad', hEn: '5. A slow feeder or anti-gulping bowl', p: 'Perros que comen demasiado rápido pueden desarrollar problemas digestivos serios (incluyendo GDV en razas grandes). Un comedero con laberintos ralentiza la ingesta al menos un 50%. Inversión de $15 que puede evitar emergencias veterinarias.', pEn: 'Dogs that eat too fast can develop serious digestive problems (including GDV in large breeds). A maze-style bowl slows intake by at least 50%. A $15 investment that can prevent veterinary emergencies.' },
      { h: '6. Limpiador enzimático para accidentes', hEn: '6. An enzymatic cleaner for accidents', p: "Nature's Miracle o Rocco & Roxie son los estándares del mercado. Los limpiadores normales no eliminan los marcadores de olor que llevan al perro a repetir en el mismo spot. El limpiador enzimático sí los descompone completamente.", pEn: "Nature's Miracle and Rocco & Roxie are the market standards. Regular cleaners do not remove the scent markers that lead a dog to go again in the same spot. An enzymatic cleaner breaks them down completely." },
      { h: '7. Kit de aseo básico', hEn: '7. A basic grooming kit', p: 'Mínimo: cepillo apropiado para el tipo de pelaje (slicker para pelo largo, goma para pelo corto), cortauñas canino o lima eléctrica, y champú neutro. La frecuencia de baño depende de la raza: de semanal a mensual. El cepillado de dientes desde cachorro es crucial.', pEn: 'At minimum: a brush suited to the coat type (a slicker for long hair, a rubber one for short hair), canine nail clippers or an electric grinder, and a pH-neutral shampoo. Bathing frequency depends on the breed, from weekly to monthly. Brushing the teeth from puppyhood is crucial.' },
      { h: '8. Correa de 6 pies + correa retráctil para parque', hEn: '8. A 6-foot leash + a retractable leash for the park', p: 'Una correa fija de 1.5-2m para caminatas de entrenamiento (control y seguridad vial). Una retráctil de 5m solo para parques y espacios abiertos — nunca en calle con tráfico. Las retráctiles en ciudad son accidentes esperando ocurrir.', pEn: 'A fixed 5-6 ft leash for training walks (control and traffic safety). A 16 ft retractable one only for parks and open spaces — never on streets with traffic. Retractable leashes in the city are accidents waiting to happen.' },
      { h: '9. Juguetes de diferentes texturas', hEn: '9. Toys with different textures', p: 'El juego es necesidad cognitiva, no opcional. Necesitas al menos 3 tipos: un juguete de masticación resistente, uno interactivo de buscar/jalar, y uno de puzzle. Rota los juguetes semanalmente para mantener la novedad sin comprar nuevos.', pEn: 'Play is a cognitive need, not an option. You need at least 3 kinds: a durable chew toy, an interactive fetch/tug toy, and a puzzle toy. Rotate the toys weekly to keep them feeling new without buying more.' },
      { h: '10. Bolsa de entrenamiento + premios pequeños', hEn: '10. A training pouch + small treats', p: 'Una bolsa de treats que se use en la cintura te libera las manos durante el entrenamiento. Los premios deben ser del tamaño de un garbanzo máximo. Pollo cocido, queso bajo en grasa o premios liofilizados son más atractivos que galletas secas para mantener atención.', pEn: 'A treat pouch worn at the waist frees up your hands during training. Treats should be the size of a chickpea at most. Cooked chicken, low-fat cheese, or freeze-dried treats are more enticing than dry biscuits for holding attention.' },
    ],
    stat: 'El dueño promedio de perro nuevo gasta $1,200-$2,500 en el primer año en accesorios. El 40% de ese gasto es en productos que no usan después del primer mes, según la APPA.',
    statEn: 'The average new dog owner spends $1,200-$2,500 on accessories in the first year. According to the APPA, 40% of that spending goes to products they stop using after the first month.',
    tips: [
      'Compra el crate antes de que llegue el perro: que tenga tiempo de familiarizarse',
      'Amazon Subscribe & Save da 15% de descuento en consumibles (shampoo, treats, pads)',
      'No compres ropa hasta saber si tu perro la tolera: muchos la odian',
      'La tienda de BPuppy tiene los productos que recomendamos con links verificados'
    ],
    tipsEn: [
      'Buy the crate before the dog arrives, so it has time to get familiar with it',
      'Amazon Subscribe & Save gives 15% off consumables (shampoo, treats, pads)',
      "Don't buy clothing until you know your dog tolerates it — many dogs hate it",
      'The BPuppy store carries the products we recommend, with verified links'
    ],
    close: 'La clave no es tener todo desde el día uno: es tener las cosas correctas. Arnés, crate, KONG y limpiador enzimático ya te ponen muy por delante del dueño promedio. El resto lo vas agregando según las necesidades reales de tu perro.',
    closeEn: "The key isn't having everything from day one: it's having the right things. A harness, a crate, a KONG, and an enzymatic cleaner already put you well ahead of the average owner. You add the rest as your dog's real needs emerge."
  },
  {
    id: 36, cat: 'guias', emoji: '🐱', color: '#E85D75',
    title: 'Los 12 accesorios que todo dueño de gato necesita desde el día uno',
    titleEn: 'The 12 Accessories Every Cat Owner Needs from Day One',
    sub: 'La guía honesta para empezar sin errores ni gastos innecesarios',
    subEn: 'The honest guide to starting out without mistakes or wasted spending',
    date: 'Mayo 2025', dateEn: 'May 2025', read: 6,
    tags: ['accesorios', 'gato', 'nuevo dueño', 'compras'],
    lead: 'Los gatos son independientes pero sus necesidades de espacio, estimulación y sanidad son muy específicas. Un entorno mal equipado genera estrés felino, y el estrés en gatos aparece como comportamientos destructivos, problemas de salud y mal uso del arenero. Esta lista previene todo eso.',
    leadEn: 'Cats are independent, but their needs for space, stimulation, and hygiene are very specific. A poorly equipped environment creates feline stress, and stress in cats shows up as destructive behavior, health problems, and litter-box trouble. This list prevents all of that.',
    body: [
      { h: '1. Arenero: uno más que el número de gatos', hEn: '1. Litter boxes: one more than the number of cats', p: 'La regla es n+1: si tienes un gato, necesitas 2 areneros. Si tienes dos, necesitas 3. Los gatos son extraordinariamente limpios y rechazan areneros sucios o con olor. Caja destapada en zona tranquila, limpieza diaria, cambio completo de arena cada 2 semanas.', pEn: 'The rule is n+1: if you have one cat, you need 2 litter boxes. If you have two, you need 3. Cats are extraordinarily clean and refuse dirty or smelly boxes. Use an uncovered box in a quiet area, scoop daily, and do a full litter change every 2 weeks.' },
      { h: '2. Arena de calidad: marca la diferencia', hEn: '2. Quality litter: it makes the difference', p: 'Las arenas aglomerantes sin polvo son el estándar actual. Dr. Elsey\'s Cat Ultra y Ever Clean son las mejor evaluadas por veterinarios. Evitar arenas perfumadas: el olfato felino es 14 veces más sensible que el humano y los perfumes artificiales son rechazados activamente.', pEn: 'Dust-free clumping litters are the current standard. Dr. Elsey\'s Cat Ultra and Ever Clean rate highest with veterinarians. Avoid scented litters: a cat\'s sense of smell is 14 times more sensitive than a human\'s, and artificial fragrances are actively rejected.' },
      { h: '3. Árbol rascador y cat tree', hEn: '3. A scratching post and cat tree', p: 'Los gatos necesitan rascar: es marcaje territorial, estiramiento y mantenimiento de uñas. Si no les das superficie apropiada, eligen tus muebles. Un árbol con plataformas altas también satisface la necesidad felina de observar su territorio desde altura.', pEn: 'Cats need to scratch: it is territorial marking, stretching, and nail maintenance. If you don\'t give them an appropriate surface, they\'ll pick your furniture. A tree with high platforms also satisfies the feline need to survey their territory from above.' },
      { h: '4. Fuente de agua', hEn: '4. A water fountain', p: 'Los gatos domésticos beben muy poca agua por instinto (sus ancestros obtenían hidratación de las presas). Una fuente con agua en movimiento estimula el consumo y reduce el riesgo de enfermedad renal, la principal causa de muerte en gatos domésticos mayores. Drinkwell y Catit son las marcas más usadas.', pEn: 'Domestic cats instinctively drink very little water (their ancestors got their hydration from prey). A fountain with moving water encourages drinking and lowers the risk of kidney disease, the leading cause of death in older house cats. Drinkwell and Catit are the most widely used brands.' },
      { h: '5. Juguetes de estimulación activa', hEn: '5. Active-stimulation toys', p: 'Los gatos necesitan "caza simulada" diaria: 2 sesiones de 10-15 minutos con varita interactiva satisfacen su instinto predatorio. Sin eso, dirigen esa energía hacia comportamientos problemáticos. Los juguetes de batería (pelotas motorizadas, peces que se mueven) extienden el juego cuando no estás.', pEn: 'Cats need daily "simulated hunting": 2 sessions of 10-15 minutes with an interactive wand satisfy their predatory instinct. Without it, they channel that energy into problem behaviors. Battery-powered toys (motorized balls, wriggling fish) extend playtime when you\'re away.' },
      { h: '6. Transportadora cómoda', hEn: '6. A comfortable carrier', p: 'La transportadora que usarás para el vet, viajes y emergencias debe introducirse como espacio positivo desde el primer día, no solo cuando van al veterinario. Déjala abierta en casa con una manta suave adentro. Un gato familiarizado con su transportadora viaja con mucho menos estrés.', pEn: 'The carrier you\'ll use for the vet, travel, and emergencies should be introduced as a positive space from day one, not only when it\'s time for the vet. Leave it open at home with a soft blanket inside. A cat that\'s familiar with its carrier travels with far less stress.' },
      { h: '7. Rascador horizontal y vertical', hEn: '7. A horizontal and a vertical scratcher', p: 'Algunos gatos prefieren rascar horizontal (cartón corrugado), otros vertical (sisal). Ofrece ambas opciones al inicio para descubrir la preferencia de tu gato. Los rascadores de cartón son económicos y la mayoría de gatos los adoran.', pEn: 'Some cats prefer to scratch horizontally (corrugated cardboard), others vertically (sisal). Offer both options at first to discover your cat\'s preference. Cardboard scratchers are inexpensive and most cats adore them.' },
      { h: '8. Dispensador automático o comedero elevado', hEn: '8. An automatic feeder or raised bowl', p: 'Los gatos se benefician de alimentación en porciones controladas (especialmente razas propensas a obesidad como Maine Coon o gatos castrados). Un comedero elevado reduce la presión cervical. Si trabajas fuera, un dispensador automático con programación hace el trabajo.', pEn: 'Cats benefit from portion-controlled feeding (especially obesity-prone breeds like the Maine Coon, or neutered cats). A raised bowl reduces strain on the neck. If you work away from home, a programmable automatic feeder does the job.' },
    ],
    stat: 'El 58% de los gatos en USA tienen sobrepeso u obesidad, según la APOP (Association for Pet Obesity Prevention). La causa principal: libre acceso a comida y falta de estimulación física activa.',
    statEn: 'According to the APOP (Association for Pet Obesity Prevention), 58% of cats in the US are overweight or obese. The main cause: free access to food and a lack of active physical stimulation.',
    tips: [
      'Introduce al gato nuevo en un cuarto solo por los primeros 3-7 días: facilita la adaptación',
      'Feliway difusor de feromonas: reduce el estrés del primer mes significativamente',
      'Chips de identificación: obligatorio aunque sea gato de interior (se escapan)',
      'Revisa nuestra tienda para los productos recomendados con mejores precios'
    ],
    tipsEn: [
      'Introduce the new cat in a room of its own for the first 3-7 days — it eases the adjustment',
      'A Feliway pheromone diffuser significantly reduces stress during the first month',
      'Microchip ID: a must even for an indoor cat (they do get out)',
      'Check our store for the recommended products at the best prices'
    ],
    close: 'Un gato en un entorno bien equipado es un gato tranquilo, saludable y con buen carácter. La mayoría de "problemas de comportamiento felino" son respuestas lógicas a un entorno que no cubre sus necesidades. Cubre las necesidades, desaparecen los problemas.',
    closeEn: 'A cat in a well-equipped environment is a calm, healthy, good-natured cat. Most "feline behavior problems" are logical responses to an environment that doesn\'t meet their needs. Meet the needs, and the problems disappear.'
  },

  // ── GROOMING ─────────────────────────────────────────────────────────────
  {
    id: 37, cat: 'grooming', emoji: '✂️', color: '#9C27B0',
    title: 'Las tendencias de grooming que arrasan en 2025',
    titleEn: 'The Grooming Trends Taking Over in 2025',
    sub: 'De los cortes creativos asiáticos al grooming ecológico: lo que está de moda',
    subEn: 'From creative Asian cuts to eco-friendly grooming: what\'s in style',
    date: 'Mayo 2025', dateEn: 'May 2025', read: 5,
    tags: ['grooming', 'tendencias', '2025', 'cortes'],
    lead: 'El grooming canino se convirtió en una forma de expresión artística. Lo que antes era solo "baño y corte" hoy incluye tintes seguros, cortes arquitectónicos y estilos que hacen que las fotos de los perros sean más virales que las de sus dueños.',
    leadEn: 'Dog grooming has become a form of artistic expression. What used to be just "bath and trim" now includes safe dyes, architectural cuts, and styles that make photos of the dogs go more viral than the ones of their owners.',
    body: [
      { h: 'El grooming asiático: la tendencia más popular', hEn: 'Asian grooming: the most popular trend', p: 'Originado en Japón y Taiwan, el "Asian Fusion grooming" exagera las proporciones del perro de forma adorable: cabeza redonda tipo burbuja, patas cilíndricas, cara con volumen esférico. Las razas con pelo continuo (Poodle, Bichón, Maltés, Shih Tzu) son las más adaptables. El resultado son fotos que se viralizan inevitablemente.', pEn: 'Originating in Japan and Taiwan, "Asian Fusion grooming" exaggerates a dog\'s proportions in an adorable way: a round, bubble-like head, cylindrical legs, a face with spherical volume. Breeds with continuously growing hair (Poodle, Bichon, Maltese, Shih Tzu) are the most adaptable. The result is photos that inevitably go viral.' },
      { h: 'Tintes seguros para mascotas: arte canino', hEn: 'Pet-safe dyes: canine art', p: 'Los tintes para mascotas formulados sin peroxide, ammonia ni PPD son seguros para el pelaje. El "creative grooming" incluye mechas, puntas de color, patrones geométricos y hasta degradados. El negocio en USA genera millones anuales. En Miami, la demanda de grooming creativo creció 60% en 2023.', pEn: 'Pet dyes formulated without peroxide, ammonia, or PPD are safe for the coat. "Creative grooming" includes highlights, colored tips, geometric patterns, and even ombré fades. The business generates millions a year in the US. In Miami, demand for creative grooming grew 60% in 2023.' },
      { h: 'Grooming ecológico: la tendencia de valores', hEn: 'Eco-friendly grooming: the values-driven trend', p: 'Shampoos biodegradables, envases recargables, toallas de microfibra en lugar de secadoras de alto consumo energético, y productos sin sulfatos ni parabenos. Los dueños millennials preguntan específicamente por opciones eco-friendly y muchos salones están respondiendo con certificaciones cruelty-free.', pEn: 'Biodegradable shampoos, refillable containers, microfiber towels instead of energy-hungry dryers, and products free of sulfates and parabens. Millennial owners specifically ask for eco-friendly options, and many salons are responding with cruelty-free certifications.' },
      { h: 'El grooming de spa: experiencia premium', hEn: 'Spa grooming: the premium experience', p: 'Más allá del baño y corte: aromaterapia con aceites esenciales seguros, masajes de relajación, tratamientos de hidratación profunda del pelaje, y barro desintoxicante. Los salones premium ofrecen paquetes de spa que incluyen tiempo de relajación post-tratamiento antes de la recogida.', pEn: 'Beyond the bath and trim: aromatherapy with safe essential oils, relaxation massages, deep coat-hydration treatments, and detoxifying mud. Premium salons offer spa packages that include post-treatment relaxation time before pickup.' },
    ],
    stat: 'La industria global de grooming de mascotas superó los $11 billones USD en 2024 y se proyecta a $19 billones para 2030. El crecimiento está impulsado por el segmento premium y creative grooming.',
    statEn: 'The global pet grooming industry surpassed $11 billion USD in 2024 and is projected to reach $19 billion by 2030. The growth is driven by the premium segment and creative grooming.',
    tips: [
      'Para grooming asiático: necesitas al menos 3 meses de crecimiento de pelo previo',
      'Los tintes seguros duran 4-8 semanas dependiendo del pelaje y frecuencia de baño',
      'El grooming creativo aumenta el costo del servicio entre 40-80% sobre el precio base',
      'Pregunta siempre si los productos son testados en mascotas y libres de PPD'
    ],
    tipsEn: [
      'For Asian grooming, you need at least 3 months of prior hair growth',
      'Safe dyes last 4-8 weeks depending on the coat and how often you bathe',
      'Creative grooming raises the cost of the service by 40-80% over the base price',
      'Always ask whether the products are pet-tested and PPD-free'
    ],
    close: 'El grooming ya no es mantenimiento: es identidad. Y si tu perro termina siendo más seguido en Instagram que tú, eso es completamente aceptable.',
    closeEn: 'Grooming is no longer maintenance: it\'s identity. And if your dog ends up with more Instagram followers than you, that\'s completely acceptable.'
  },
  {
    id: 38, cat: 'grooming', emoji: '🐕', color: '#7C3AED',
    title: 'El corte perfecto para cada raza: guía visual para dueños',
    titleEn: 'The Perfect Cut for Every Breed: A Visual Guide for Owners',
    sub: 'Qué pedirle al groomer y qué esperar según la raza de tu perro',
    subEn: 'What to ask your groomer for and what to expect based on your dog\'s breed',
    date: 'Abril 2025', dateEn: 'April 2025', read: 6,
    tags: ['grooming', 'razas', 'cortes', 'pelaje'],
    lead: 'Llegas al groomer y dices "córtale el pelo". El resultado no es lo que imaginabas. Esto pasa cuando no conoces los nombres correctos de los cortes para tu raza. Esta guía te da el vocabulario y los criterios para comunicarte bien y obtener lo que quieres.',
    leadEn: 'You get to the groomer and say "cut his hair." The result isn\'t what you pictured. This happens when you don\'t know the correct names of the cuts for your breed. This guide gives you the vocabulary and the criteria to communicate well and get what you want.',
    body: [
      { h: 'Poodle: el rey del grooming artístico', hEn: 'Poodle: the king of artistic grooming', p: 'Los cortes estándar de Poodle tienen nombre propio: Continental Clip (concurso), Sporting Clip (funcional y elegante), Puppy Clip (pelo uniformemente corto en todo el cuerpo) y el Teddy Bear Cut (cara redondeada, pelo corto uniforme). Para la mayoría de dueños, el Teddy Bear o Puppy Clip son los más prácticos.', pEn: 'The standard Poodle cuts have names of their own: the Continental Clip (show), the Sporting Clip (functional and elegant), the Puppy Clip (uniformly short hair over the whole body), and the Teddy Bear Cut (rounded face, uniformly short hair). For most owners, the Teddy Bear or Puppy Clip are the most practical.' },
      { h: 'Golden Retriever y Labrador: lo menos es más', hEn: 'Golden Retriever and Labrador: less is more', p: 'Estas razas NO deben rasurarse nunca: su doble capa regula temperatura tanto en calor como en frío. El grooming correcto es: baño con shampoo deslanador, secado profesional con soplador de alta velocidad, y despelote (deslanado) con Furminator. Un Golden bien deslanado pierde la mitad del pelo flotante.', pEn: 'These breeds should NEVER be shaved: their double coat regulates temperature in both heat and cold. The right grooming is a bath with a de-shedding shampoo, professional drying with a high-velocity blower, and de-shedding with a Furminator. A well de-shed Golden loses half of its loose hair.' },
      { h: 'Schnauzer: el corte que define la raza', hEn: 'Schnauzer: the cut that defines the breed', p: 'El Schnauzer tiene un corte tradicional muy específico: cuerpo rapado corto con tijera en lomo, falda larga en la barriga y patas, y bigote y cejas pronunciados. Hay variaciones modernas (cuerpo más largo, cara más redondeada) pero el corte clásico es el que mejor respeta la morfología de la raza.', pEn: 'The Schnauzer has a very specific traditional cut: a closely clipped body scissored along the back, a long skirt on the belly and legs, and a pronounced beard and eyebrows. There are modern variations (a longer body, a rounder face), but the classic cut is the one that best respects the breed\'s build.' },
      { h: 'Yorkshire y Maltés: pelo largo vs. puppy cut', hEn: 'Yorkshire and Maltese: long coat vs. puppy cut', p: 'El pelo largo (floor-length) requiere cepillado diario sin excepción. El Puppy Cut (pelo uniformemente corto a 2-4cm) es idéntico en estética pero de mantenimiento radicalmente más fácil. Para dueños que no tienen tiempo de cepillar diariamente, el Puppy Cut es la opción responsable.', pEn: 'A long, floor-length coat requires daily brushing without exception. The Puppy Cut (hair kept uniformly short at about 1-1.5 inches) is just as cute but radically easier to maintain. For owners who don\'t have time to brush daily, the Puppy Cut is the responsible choice.' },
      { h: 'Cocker Spaniel y Shih Tzu: el equilibrio difícil', hEn: 'Cocker Spaniel and Shih Tzu: the difficult balance', p: 'Ambas razas tienen pelaje que requiere grooming profesional cada 6-8 semanas. El Cocker tiene un corte de concurso elaborado pero la mayoría de groomers ofrece una versión práctica que mantiene la forma característica sin el extremo mantenimiento del corte de show.', pEn: 'Both breeds have coats that require professional grooming every 6-8 weeks. The Cocker has an elaborate show cut, but most groomers offer a practical version that keeps the characteristic shape without the extreme upkeep of the show cut.' },
    ],
    stat: 'El 67% de los dueños de razas con pelo continuo no saben el nombre del corte correcto para su raza, según una encuesta de la National Dog Groomers Association of America. Esto genera frustración recurrente en las visitas de grooming.',
    statEn: 'According to a survey by the National Dog Groomers Association of America, 67% of owners of continuous-coat breeds don\'t know the name of the correct cut for their breed. This leads to recurring frustration at grooming appointments.',
    tips: [
      'Lleva una foto de referencia: "quiero esto" elimina el 90% de las malas comunicaciones',
      'Nunca rasures un Golden, Husky, Akita, Samoyedo o cualquier raza de doble capa',
      'El "Teddy Bear Cut" puede aplicarse a casi cualquier raza de pelo continuo',
      'Pide siempre que incluyan limpieza de oídos y expresión de glándulas anales en el servicio'
    ],
    tipsEn: [
      'Bring a reference photo: "I want this" eliminates 90% of miscommunications',
      'Never shave a Golden, Husky, Akita, Samoyed, or any double-coated breed',
      'The "Teddy Bear Cut" can be applied to almost any continuous-coat breed',
      'Always ask that ear cleaning and anal-gland expression be included in the service'
    ],
    close: 'La comunicación con tu groomer es una habilidad que se aprende. Una foto, el nombre del corte y una descripción de cuánto mantenimiento puedes dar en casa es toda la información que necesita para darte el resultado perfecto.',
    closeEn: 'Communicating with your groomer is a skill you learn. A photo, the name of the cut, and a description of how much upkeep you can manage at home is all the information they need to give you the perfect result.'
  },
  {
    id: 39, cat: 'grooming', emoji: '🛁', color: '#1EB87A',
    title: 'Cómo bañar a tu perro en casa sin traumatizarlo',
    titleEn: 'How to Bathe Your Dog at Home Without Traumatizing Him',
    sub: 'Técnica, productos y frecuencia para cada tipo de pelaje',
    subEn: 'Technique, products, and frequency for every coat type',
    date: 'Abril 2025', dateEn: 'April 2025', read: 5,
    tags: ['grooming', 'baño', 'casa', 'pelaje'],
    lead: 'Bañar a un perro en casa parece simple hasta que lo intentas. El perro se sacude, el agua va por todas partes, el pelo tapa el desagüe y tu baño queda peor que el perro. Con la técnica correcta y los productos adecuados, el baño en casa puede ser una experiencia tranquila para ambos.',
    leadEn: 'Bathing a dog at home seems simple until you try it. The dog shakes, water goes everywhere, hair clogs the drain, and your bathroom ends up worse off than the dog. With the right technique and the right products, the home bath can be a calm experience for you both.',
    body: [
      { h: 'La preparación que lo cambia todo', hEn: 'The prep that changes everything', p: 'Antes del agua: cepilla completamente el pelaje para deshacer nudos (el pelo mojado los vuelve imposibles de deshacer), junta todos los productos necesarios al alcance, y coloca una toalla antideslizante en el fondo de la bañera. Un perro que resbala en el baño aprende a tenerle miedo.', pEn: 'Before the water: brush the coat thoroughly to work out tangles (wet hair makes them impossible to undo), gather all the products you\'ll need within reach, and place a non-slip towel on the bottom of the tub. A dog that slips in the bath learns to fear it.' },
      { h: 'La temperatura y la presión correcta', hEn: 'The right temperature and pressure', p: 'El agua debe estar tibia, no caliente: la piel canina es más sensible a la temperatura que la humana. Usa una alcachofita o recipiente para mojar progressivamente en lugar del chorro directo. La presión alta del chorro asusta a muchos perros. Moja primero el cuerpo y deja la cara para el final.', pEn: 'The water should be lukewarm, not hot: canine skin is more sensitive to temperature than human skin. Use a handheld sprayer or a cup to wet the dog gradually instead of a direct stream. High water pressure frightens many dogs. Wet the body first and save the face for last.' },
      { h: 'Champú: nunca el de humanos', hEn: 'Shampoo: never the human kind', p: 'El pH de la piel canina (6.2-7.4) es diferente al humano (4.5-5.5). Los champús humanos alteran el manto ácido del pelaje del perro y pueden causar sequedad, irritación y mayor susceptibilidad a bacterias e hongos. Usa siempre champú formulado para perros o sin sulfatos si quieres algo suave.', pEn: 'The pH of canine skin (6.2-7.4) is different from human skin (4.5-5.5). Human shampoos disrupt the acid mantle of a dog\'s coat and can cause dryness, irritation, and greater susceptibility to bacteria and fungi. Always use a shampoo formulated for dogs, or a sulfate-free one if you want something gentle.' },
      { h: 'Secado: el paso más importante', hEn: 'Drying: the most important step', p: 'No dejes al perro húmedo: la humedad en la piel genera dermatitis por humedad (hot spots) especialmente en razas con pelaje denso. Usa secadora en temperatura media, a 30cm del pelo mínimo. Los sopladores de alta velocidad (force dryer) son la herramienta profesional que separa el pelo y seca mucho más eficientemente.', pEn: 'Don\'t leave the dog damp: moisture on the skin causes moist dermatitis (hot spots), especially in dense-coated breeds. Use a dryer on medium heat, at least a foot away from the coat. High-velocity force dryers are the professional tool that separates the hair and dries far more efficiently.' },
    ],
    stat: 'Según estudios del grooming profesional, el 73% de los perros que "odian el baño" lo hacen por experiencias negativas previas (agua en ojos, resbalones, temperatura incorrecta) no por aversión innata al agua.',
    statEn: 'According to professional grooming studies, 73% of dogs that "hate the bath" do so because of past negative experiences (water in the eyes, slips, the wrong temperature), not because of an innate aversion to water.',
    tips: [
      'Algodón en los oídos durante el baño previene otitis por humedad',
      'Premio durante y después del baño: asociación positiva consistente',
      'Lava el champú completamente: el residuo es la principal causa de irritación de piel',
      'Groomer profesional cada 8-12 semanas + baño en casa cuando necesario: la combinación ideal'
    ],
    tipsEn: [
      'Cotton in the ears during the bath prevents moisture-related ear infections',
      'A treat during and after the bath builds a consistent positive association',
      'Rinse the shampoo out completely: residue is the leading cause of skin irritation',
      'A professional groomer every 8-12 weeks plus a home bath when needed is the ideal combination'
    ],
    close: 'El baño en casa es viable y económico. Pero un groomer profesional con soplador de alta velocidad hace en 2 horas lo que te tomaría 4 a ti, con mejor resultado final y sin el desastre del baño. Los dos tienen su lugar.',
    closeEn: 'The home bath is doable and economical. But a professional groomer with a high-velocity dryer does in 2 hours what would take you 4, with a better final result and none of the bathroom mess. Both have their place.'
  },
  {
    id: 40, cat: 'grooming', emoji: '😺', color: '#E86535',
    title: 'Grooming para gatos: lo que la mayoría de dueños no sabe',
    titleEn: 'Cat Grooming: What Most Owners Don\'t Know',
    sub: 'Por qué los gatos también necesitan groomer profesional',
    subEn: 'Why cats need a professional groomer too',
    date: 'Marzo 2025', dateEn: 'March 2025', read: 5,
    tags: ['grooming', 'gatos', 'pelaje', 'mantenimiento'],
    lead: 'Los gatos se limpian solos, sí. Pero eso no significa que no necesiten grooming. Gatos de pelo largo, obesos o con artritis no pueden acicalarse correctamente. El resultado: nudos, bolas de pelo problemáticas, infecciones de piel y un gato incómodo que no puede decirte que algo le duele.',
    leadEn: 'Cats clean themselves, yes. But that doesn\'t mean they don\'t need grooming. Long-haired, overweight, or arthritic cats can\'t groom themselves properly. The result: mats, problematic hairballs, skin infections, and an uncomfortable cat that can\'t tell you something hurts.',
    body: [
      { h: '¿Cuándo necesita un gato groomer profesional?', hEn: 'When does a cat need a professional groomer?', p: 'Razas de pelo largo (Persa, Maine Coon, Ragdoll, Noruego del Bosque) necesitan grooming profesional cada 6-8 semanas sin excepción. Cualquier gato con nudos que no se pueden deshacer con cepillo necesita groomer. Gatos mayores o con artritis que ya no pueden alcanzarse ciertos puntos también.', pEn: 'Long-haired breeds (Persian, Maine Coon, Ragdoll, Norwegian Forest Cat) need professional grooming every 6-8 weeks without exception. Any cat with mats that can\'t be worked out with a brush needs a groomer. So do older or arthritic cats that can no longer reach certain spots.' },
      { h: 'El "lion cut": cuándo tiene sentido', hEn: 'The "lion cut": when it makes sense', p: 'El corte de león (rapar el cuerpo dejando melena, patas y punta de cola) es la solución más práctica para gatos con matones severos o para el verano en climas calurosos. Es reversible, el pelo crece en 3-4 meses. Contrario a lo que se cree, los gatos rapados en verano están más cómodos, no más vulnerables.', pEn: 'The lion cut (shaving the body while leaving the mane, legs, and tail tip) is the most practical solution for cats with severe matting or for summer in hot climates. It\'s reversible — the coat grows back in 3-4 months. Contrary to popular belief, cats shaved for summer are more comfortable, not more vulnerable.' },
      { h: 'Baño de gato: sí, es posible', hEn: 'Bathing a cat: yes, it\'s possible', p: 'Los groomers especializados bañan gatos con técnicas específicas: agua tibia en entorno cerrado y silencioso, movimientos lentos y seguros, secado con soplador de baja velocidad. Un gato bien acostumbrado al groomer desde joven lo tolera bien. Nunca intentes bañar un gato adulto no habituado sin ayuda.', pEn: 'Specialized groomers bathe cats with specific techniques: lukewarm water in an enclosed, quiet space, slow and reassuring movements, and drying with a low-velocity blower. A cat that\'s been accustomed to the groomer from a young age tolerates it well. Never try to bathe an unaccustomed adult cat without help.' },
      { h: 'Cepillado en casa: la rutina que previene todo', hEn: 'At-home brushing: the routine that prevents everything', p: 'Para pelo largo: cepillado diario de 5 minutos. Para pelo corto: semanal. El guante desmallador de goma (Zoom Groom) es el favorito de la mayoría de gatos porque imita la sensación del lamido. El FURminator para gatos reduce el 90% del pelo suelto que termina en alfombras y en las bolas de pelo.', pEn: 'For long hair: 5 minutes of daily brushing. For short hair: weekly. The rubber de-shedding glove (Zoom Groom) is most cats\' favorite because it mimics the feel of being licked. The FURminator for cats removes 90% of the loose hair that ends up on carpets and in hairballs.' },
    ],
    stat: 'Las bolas de pelo (hairballs) que requieren intervención veterinaria cuestan en promedio $800-$1,500 de tratamiento en USA. El cepillado regular y el grooming profesional reduce el riesgo en más del 80%.',
    statEn: 'Hairballs that require veterinary intervention cost an average of $800-$1,500 to treat in the US. Regular brushing and professional grooming reduce the risk by more than 80%.',
    tips: [
      'Empieza el grooming desde cachorro: la habituación temprana lo cambia todo',
      'Nunca uses tijeras en casa para deshacer nudos: riesgo de corte en piel bajo el nudo',
      'Pastillas para bolas de pelo (Laxatone): preventivo económico para pelo largo',
      'Limpieza de uñas mensual: evita que se claven en pads o que dañen muebles'
    ],
    tipsEn: [
      'Start grooming from kittenhood: early acclimation changes everything',
      'Never use scissors at home to cut out mats: you risk cutting the skin beneath the mat',
      'Hairball paste (Laxatone): an inexpensive preventive for long hair',
      'Monthly nail trims: keeps claws from snagging on paw pads or damaging furniture'
    ],
    close: 'Tu gato se lame para estar limpio, no para estar bien cuidado. El grooming profesional completa lo que el lengüetazo no puede. Un gato bien cuidado se ve diferente: pelo brillante, sin nudos, sin olor, sin molestias. Es la diferencia entre sobrevivir y florecer.',
    closeEn: 'Your cat licks itself to be clean, not to be well cared for. Professional grooming completes what the tongue can\'t. A well-cared-for cat looks different: a glossy coat, no mats, no odor, no discomfort. It\'s the difference between surviving and thriving.'
  },
  {
    id: 41, cat: 'grooming', emoji: '🌟', color: '#1E90FF',
    title: 'Grooming creativo: las transformaciones que se volvieron virales',
    titleEn: 'Creative Grooming: The Transformations That Went Viral',
    sub: 'El arte canino que conquista TikTok e Instagram globalmente',
    subEn: 'The canine art taking over TikTok and Instagram worldwide',
    date: 'Mayo 2025', dateEn: 'May 2025', read: 4,
    tags: ['grooming creativo', 'viral', 'TikTok', 'arte canino'],
    lead: 'El grooming creativo existe desde los 90s en competencias de concurso. Pero TikTok lo democratizó: ahora cualquier dueño puede llegar al groomer con una idea y convertir a su perro en tendencia global. Estos son los estilos que más se viralizan y qué requieren.',
    leadEn: 'Creative grooming has existed since the 90s in show competitions. But TikTok democratized it: now any owner can walk into the groomer with an idea and turn their dog into a global trend. These are the styles that go viral most, and what they require.',
    body: [
      { h: 'El Samoyedo Panda: el original viral', hEn: 'The Panda Samoyed: the original viral hit', p: 'Groomers en China y Japón comenzaron a dar a Samoyedos y Chow Chow el patrón de oso panda: manchas negras (con tinte seguro) alrededor de los ojos y orejas sobre el pelaje blanco. Las fotos generaron millones de interacciones. La tendencia llegó a USA en 2022 y sigue siendo una de las más solicitadas.', pEn: 'Groomers in China and Japan began giving Samoyeds and Chow Chows the panda-bear pattern: black markings (with safe dye) around the eyes and ears over the white coat. The photos generated millions of interactions. The trend reached the US in 2022 and remains one of the most requested.' },
      { h: 'Cortes arquitectónicos asiáticos', hEn: 'Asian architectural cuts', p: 'Los groomers de Taiwan y Corea del Sur llevan el Asian Fusion a otro nivel: perros que parecen esculpidos, con perfectas esferas de pelo en lugar de cabeza, rectángulos perfectos como cuerpo y cilindros uniformes como patas. Requieren meses de crecimiento, tijeras profesionales y horas de trabajo.', pEn: 'Groomers in Taiwan and South Korea take Asian Fusion to another level: dogs that look sculpted, with perfect spheres of hair for a head, perfect rectangles for a body, and uniform cylinders for legs. They require months of growth, professional shears, and hours of work.' },
      { h: 'Tintes temáticos: de Halloween a Pride', hEn: 'Themed dyes: from Halloween to Pride', p: 'Tintes seguros para mascotas (sin peroxide, amonio ni PPD) permiten decorar el pelaje para eventos especiales. Los más virales: patrones de llamas para Halloween, degradados de arcoíris para Pride, y tonos pastel para primavera. Los tintes duran 4-8 baños y son completamente reversibles.', pEn: 'Pet-safe dyes (free of peroxide, ammonia, and PPD) let you decorate the coat for special events. The most viral: flame patterns for Halloween, rainbow ombré for Pride, and pastel tones for spring. The dyes last 4-8 baths and are completely reversible.' },
      { h: 'El grooming competitivo: un deporte serio', hEn: 'Competitive grooming: a serious sport', p: 'Las competencias de grooming creativo (Intergroom en New Jersey, Groom Expo en Hershey) son eventos con jueces certificados, puntuaciones técnicas y premios importantes. Los ganadores son artistas que trabajan durante semanas el diseño de cada perro. Los videos de competencias son de lo más viral en la comunidad pet.', pEn: 'Creative grooming competitions (Intergroom in New Jersey, Groom Expo in Hershey) are events with certified judges, technical scoring, and significant prizes. The winners are artists who spend weeks designing each dog. Competition videos are some of the most viral content in the pet community.' },
    ],
    stat: 'Los videos de grooming creativo son el segundo tipo de contenido de mascotas con más engagement en TikTok (después de cachorros nuevos), con un promedio de 3.2M de visualizaciones en los top 100 videos del género.',
    statEn: 'Creative grooming videos are the second-most engaging type of pet content on TikTok (after new puppies), averaging 3.2M views across the top 100 videos in the genre.',
    tips: [
      'Verifica que el tinte sea específico para mascotas y PPD-free antes de aplicar',
      'El grooming creativo requiere perros con pelo en buen estado: nada de hacerlo sobre pelo dañado',
      'Los cortes arquitectónicos asiáticos cuestan $150-$400+ según el salon',
      'Documenta el proceso: el "before y after" es el formato más compartible'
    ],
    tipsEn: [
      'Confirm the dye is pet-specific and PPD-free before applying it',
      'Creative grooming requires dogs with a healthy coat — never do it over damaged hair',
      'Asian architectural cuts cost $150-$400+ depending on the salon',
      'Document the process: the "before and after" is the most shareable format'
    ],
    close: 'El grooming creativo no es para todos los perros ni para todos los dueños. Pero cuando el perro lo tolera bien y el groomer es un artista, el resultado es genuinamente espectacular. Y si se vuelve viral, el costo del grooming se paga solo.',
    closeEn: 'Creative grooming isn\'t for every dog or every owner. But when the dog tolerates it well and the groomer is an artist, the result is genuinely spectacular. And if it goes viral, the cost of the grooming pays for itself.'
  },
  { id:42, cat:'razas', emoji:'🐕', color:'#2D6A4F', img:'fotos-razas-sm/German Shepherd.webp',
    title:'Pastor Alemán: inteligencia, lealtad y mucha responsabilidad',
    titleEn:'German Shepherd: Intelligence, Loyalty, and a Lot of Responsibility',
    sub:'Todo lo que necesitas saber antes de adoptar uno',
    subEn:'Everything you need to know before adopting one',
    date:'Mayo 2025', dateEn:'May 2025', read:5, tags:['pastor alemán','german shepherd'],
    lead:'El Pastor Alemán es uno de los perros más versátiles del mundo. Pero esa inteligencia viene con un precio: necesita trabajo mental y físico todos los días.',
    leadEn:'The German Shepherd is one of the most versatile dogs in the world. But that intelligence comes at a price: it needs mental and physical work every single day.',
    body:[
      {h:'Ejercicio diario mínimo 2 horas',hEn:'A minimum of 2 hours of daily exercise',p:'Un Pastor Alemán sin ejercicio se vuelve destructivo. No es un perro para quien trabaja largas jornadas sin apoyo.',pEn:'A German Shepherd without exercise becomes destructive. It is not a dog for someone who works long days without help.'},
      {h:'Entrenamiento desde el primer día',hEn:'Training from day one',p:'Son extremadamente entrenables pero necesitan límites claros desde cachorros. El refuerzo positivo funciona muy bien.',pEn:'They are extremely trainable but need clear boundaries from puppyhood. Positive reinforcement works very well.'},
      {h:'Muda de pelo: prepararse',hEn:'Shedding: be prepared',p:'Mudan considerablemente dos veces al año. Cepillado frecuente y aspiradora de alta potencia son indispensables.',pEn:'They shed considerably twice a year. Frequent brushing and a high-powered vacuum are indispensable.'},
      {h:'Salud: displasia de cadera',hEn:'Health: hip dysplasia',p:'Son propensos a displasia de cadera. Compra solo de criadores que certifiquen salud de los padres.',pEn:'They are prone to hip dysplasia. Buy only from breeders who certify the parents\' health.'},
    ],
    stat:'El Pastor Alemán es la segunda raza más registrada en USA y la más utilizada por fuerzas policiales y militares en el mundo.',
    statEn:'The German Shepherd is the second-most registered breed in the US and the most widely used by police and military forces around the world.',
    tips:['Socialización temprana con personas y animales','Agility y nose work para canalizar energía','Chequeos de cadera anuales desde los 2 años'],
    tipsEn:['Early socialization with people and animals','Agility and nose work to channel their energy','Annual hip checkups starting at age 2'],
    close:'Un Pastor Alemán bien trabajado es uno de los compañeros más extraordinarios. Pero requiere compromiso real, no solo buenas intenciones.',
    closeEn:'A well-worked German Shepherd is one of the most extraordinary companions there is. But it requires real commitment, not just good intentions.'
  },
  { id:43, cat:'razas', emoji:'🐕', color:'#D4830A', img:'fotos-razas-sm/Pembroke Welsh Corgi.webp',
    title:'Corgi: el perro de la reina que conquista las redes sociales',
    titleEn:'Corgi: The Queen\'s Dog That\'s Conquering Social Media',
    sub:'Temperamento, energía y cuidados del perro más adorable de internet',
    subEn:'Temperament, energy, and care for the most adorable dog on the internet',
    date:'Mayo 2025', dateEn:'May 2025', read:4, tags:['corgi','pembroke','familia'],
    lead:'El Corgi tiene personalidad enorme en cuerpo pequeño. Pero detrás de los videos simpáticos hay un perro de pastoreo con energía real que pide movimiento diario.',
    leadEn:'The Corgi has an enormous personality in a small body. But behind the cute videos is a herding dog with real energy that demands daily movement.',
    body:[
      {h:'Herencia de pastoreo activa',hEn:'An active herding heritage',p:'Fue criado para pastorear ganado. Tiene instinto de morder talones, energía alta y necesidad de trabajo mental.',pEn:'It was bred to herd livestock. It has a heel-nipping instinct, high energy, and a need for mental work.'},
      {h:'Inteligencia notable',hEn:'Remarkable intelligence',p:'Son el puesto #11 en el ranking de inteligencia de Coren. Aprenden rápido pero también aprenden a manipular sin límites claros.',pEn:'They rank #11 on Coren\'s intelligence list. They learn fast — but they also learn to manipulate without clear boundaries.'},
      {h:'Columna: punto crítico',hEn:'The spine: a critical point',p:'Su espalda larga y patas cortas los hacen propensos a problemas de columna. Evita escaleras en cachorros y controla el peso.',pEn:'Their long back and short legs make them prone to spinal problems. Avoid stairs while they\'re puppies and keep their weight in check.'},
      {h:'Muda de pelo considerable',hEn:'Considerable shedding',p:'Doble capa con muda estacional. Cepillado semanal y deslanado profundo dos veces al año.',pEn:'A double coat with seasonal shedding. Weekly brushing and a deep de-shed twice a year.'},
    ],
    stat:'La Reina Isabel II tuvo más de 30 Corgis durante su reinado, convirtiendo a la raza en símbolo de la monarquía británica.',
    statEn:'Queen Elizabeth II owned more than 30 Corgis during her reign, making the breed a symbol of the British monarchy.',
    tips:['Excelente para familias activas','Agility es su deporte ideal','Controla las porciones: propenso al sobrepeso'],
    tipsEn:['Excellent for active families','Agility is their ideal sport','Watch the portions: prone to being overweight'],
    close:'El Corgi es mucho más que un perro viral. Es un compañero activo, inteligente y leal que pide ejercicio, estimulación y tiempo de calidad contigo.',
    closeEn:'The Corgi is much more than a viral dog. It\'s an active, intelligent, loyal companion that asks for exercise, stimulation, and quality time with you.'
  },
  { id:44, cat:'razas', emoji:'🌭', color:'#8B4513', img:'fotos-razas-sm/Dachshund.webp',
    title:'Dachshund (Salchicha): el cazador más valiente en el cuerpo más pequeño',
    titleEn:'Dachshund (Wiener Dog): The Bravest Hunter in the Smallest Body',
    sub:'Guía completa para vivir con el perro más terco y adorable del mundo',
    subEn:'A complete guide to living with the most stubborn and adorable dog in the world',
    date:'Mayo 2025', dateEn:'May 2025', read:4, tags:['dachshund','salchicha','teckel'],
    lead:'El Dachshund fue criado para meterse en madrigueras a cazar tejones. Valiente, terco, independiente. Es uno de los perros más encantadores y difíciles a la vez.',
    leadEn:'The Dachshund was bred to burrow into dens and hunt badgers. Brave, stubborn, independent. It\'s one of the most charming and most challenging dogs all at once.',
    body:[
      {h:'Columna vertebral: su talón de Aquiles',hEn:'The spine: its Achilles heel',p:'La IVDD es la condición más común. Evita saltos, escaleras frecuentes y sobrepeso. Una rampa para el sofá puede salvarle la vida.',pEn:'IVDD is the most common condition. Avoid jumping, frequent stairs, and excess weight. A ramp to the couch can save its life.'},
      {h:'Carácter terco por diseño',hEn:'Stubborn by design',p:'Criados para trabajar solos en madrigueras, sin instrucciones. Eso se traduce en terquedad. El entrenamiento requiere más paciencia.',pEn:'Bred to work alone in burrows, without instructions. That translates into stubbornness. Training takes more patience.'},
      {h:'Instinto de caza activo',hEn:'An active hunting instinct',p:'Ladran ante cualquier movimiento y perseguirán todo. Correa siempre, patio cercado.',pEn:'They bark at any movement and will chase anything. Always on leash, with a fenced yard.'},
      {h:'Variedades de pelaje',hEn:'Coat varieties',p:'Pelo corto, largo y duro. Los de pelo largo requieren cepillado regular. Los miniatura pesan hasta 5kg.',pEn:'Smooth, long, and wirehaired. The long-haired ones require regular brushing. The miniatures weigh up to 11 lbs.'},
    ],
    stat:'El Dachshund fue la mascota de los Juegos Olímpicos de Munich 1972, el primer perro olímpico oficial de la historia.',
    statEn:'The Dachshund was the mascot of the 1972 Munich Olympics — the first official Olympic dog in history.',
    tips:['Rampa para saltos: obligatorio','Control de peso estricto toda la vida','Socialización temprana','Ideal en apartamentos con paseos diarios'],
    tipsEn:['A ramp to prevent jumping: a must','Strict weight control for life','Early socialization','Ideal in apartments with daily walks'],
    close:'Vivir con un Dachshund es una negociación constante con uno de los personajes más entrañables. Si lo entiendes, es un compañero para toda la vida.',
    closeEn:'Living with a Dachshund is a constant negotiation with one of the most endearing characters around. If you understand it, it\'s a companion for life.'
  },
  { id:45, cat:'razas', emoji:'🐾', color:'#A0522D', img:'uploads/Page 8.webp',
    title:'Bulldog Inglés: el rey del sofá con corazón de campeón',
    titleEn:'English Bulldog: The King of the Couch with the Heart of a Champion',
    sub:'Cómo cuidar bien a una raza que requiere atención especial',
    subEn:'How to properly care for a breed that needs special attention',
    date:'Mayo 2025', dateEn:'May 2025', read:5, tags:['bulldog inglés','english bulldog','braquicéfalo'],
    lead:'El Bulldog Inglés es símbolo de tenacidad. También es una de las razas con más necesidades de salud específicas. Cuidarlos bien requiere información, no solo amor.',
    leadEn:'The English Bulldog is a symbol of tenacity. It\'s also one of the breeds with the most specific health needs. Caring for them well takes knowledge, not just love.',
    body:[
      {h:'Braquicefalia: el tema más importante',hEn:'Brachycephaly: the most important issue',p:'Su hocico aplastado causa dificultades respiratorias. Evita calor extremo, ejercicio intenso y estrés. El sobrecalentamiento puede ser mortal.',pEn:'Their flat muzzle causes breathing difficulties. Avoid extreme heat, intense exercise, and stress. Overheating can be fatal.'},
      {h:'Pliegues de piel: limpieza obligatoria',hEn:'Skin folds: cleaning is mandatory',p:'Las arrugas faciales acumulan humedad y causan infecciones. Limpiar con toallitas 2-3 veces por semana, especialmente el pliegue nasal.',pEn:'The facial wrinkles trap moisture and cause infections. Clean them with wipes 2-3 times a week, especially the nose rope.'},
      {h:'Ejercicio moderado y supervisado',hEn:'Moderate, supervised exercise',p:'Caminatas cortas en horarios frescos. Nunca en el calor del mediodía.',pEn:'Short walks during the cooler hours. Never in the midday heat.'},
      {h:'Peso: control estricto',hEn:'Weight: strict control',p:'El sobrepeso agrava todos sus problemas. Las porciones deben ser precisas.',pEn:'Excess weight worsens all of their problems. Portions must be precise.'},
    ],
    stat:'El Bulldog Inglés es la mascota oficial de más de 40 universidades en USA, incluyendo Yale.',
    statEn:'The English Bulldog is the official mascot of more than 40 universities in the US, including Yale.',
    tips:['AC siempre disponible en verano','Limpieza de pliegues 2-3 veces por semana','Seguro veterinario recomendado'],
    tipsEn:['Air conditioning always available in summer','Fold cleaning 2-3 times a week','Pet insurance recommended'],
    close:'El Bulldog Inglés es un compañero excepcional para quien entiende sus necesidades específicas. Su amor es incondicional; sus cuidados, también deben serlo.',
    closeEn:'The English Bulldog is an exceptional companion for those who understand its specific needs. Its love is unconditional; its care should be too.'
  },
  { id:46, cat:'razas', emoji:'🐺', color:'#4169E1', img:'fotos-razas-sm/Siberian Husky.webp',
    title:'Husky Siberiano: belleza glacial que necesita kilómetros de espacio',
    titleEn:'Siberian Husky: Glacial Beauty That Needs Miles of Space',
    sub:'La verdad sobre vivir con uno de los perros más espectaculares del mundo',
    subEn:'The truth about living with one of the most spectacular dogs in the world',
    date:'Mayo 2025', dateEn:'May 2025', read:5, tags:['husky siberiano','siberian husky'],
    lead:'El Husky es el perro más fotografiado de Instagram y uno de los más abandonados. Esta guía es para los que quieren entender antes de enamorarse.',
    leadEn:'The Husky is the most photographed dog on Instagram and one of the most surrendered. This guide is for those who want to understand before falling in love.',
    body:[
      {h:'Energía extrema',hEn:'Extreme energy',p:'Criados para correr 150km diarios tirando trineos. Necesitan al menos 2 horas de ejercicio intenso cada día.',pEn:'Bred to run 90+ miles a day pulling sleds. They need at least 2 hours of intense exercise every day.'},
      {h:'Escapistas de nivel experto',hEn:'Expert-level escape artists',p:'Saltan vallas de 2 metros, excavan bajo cercas. El patio debe ser a prueba de Husky antes de traer uno.',pEn:'They leap 6-foot fences and dig under them. The yard must be Husky-proof before you bring one home.'},
      {h:'Muda épica dos veces al año',hEn:'Epic shedding twice a year',p:'Cepillado diario en épocas de muda. Soplador de pelo de alta velocidad recomendado.',pEn:'Daily brushing during shedding season. A high-velocity coat blower is recommended.'},
      {h:'No son perros guardianes',hEn:'They are not guard dogs',p:'Son sociables con toda la familia y amigables con extraños. Si buscas protección, no es tu raza.',pEn:'They are sociable with the whole family and friendly with strangers. If you\'re looking for protection, this isn\'t your breed.'},
    ],
    stat:'El equipo de Huskies de Leonhard Seppala recorrió 674 km en menos de 6 días en 1925 para llevar suero antidiftérico a Nome, Alaska.',
    statEn:'Leonhard Seppala\'s Husky team covered 674 km (419 miles) in less than 6 days in 1925 to deliver diphtheria antitoxin to Nome, Alaska.',
    tips:['Patio completamente cercado y seguro','Nunca sin correa en espacios abiertos','2 horas de ejercicio mínimo diario'],
    tipsEn:['A fully fenced, secure yard','Never off leash in open spaces','A minimum of 2 hours of exercise daily'],
    close:'Un Husky bien ejercitado y estimulado es uno de los compañeros más extraordinarios. Pero te lo dan todo solo si tú das todo lo que necesitan.',
    closeEn:'A well-exercised, well-stimulated Husky is one of the most extraordinary companions there is. But it gives you everything only if you give it everything it needs.'
  },
  { id:47, cat:'razas', emoji:'🐩', color:'#FFB6C1', img:'fotos-razas-sm/Bichon Frise.webp',
    title:'Bichón Frisé: el eterno cachorro que nunca falla',
    titleEn:'Bichon Frise: The Forever Puppy That Never Disappoints',
    sub:'El perro ideal para apartamentos, alergias y corazones fáciles de conquistar',
    subEn:'The ideal dog for apartments, allergies, and easily won hearts',
    date:'Mayo 2025', dateEn:'May 2025', read:4, tags:['bichón frisé','hipoalergénico','apartamento'],
    lead:'El Bichón Frisé parece un peluche animado y su personalidad lo confirma: alegre, afectuoso y completamente enfocado en hacerte feliz.',
    leadEn:'The Bichon Frise looks like a living plush toy, and its personality confirms it: cheerful, affectionate, and completely focused on making you happy.',
    body:[
      {h:'Bajo derramamiento: ventaja real',hEn:'Low shedding: a real advantage',p:'Su pelo rizado crece continuamente sin soltar casi nada. Ideal para alergias moderadas. Requiere corte cada 6-8 semanas y cepillado diario.',pEn:'Its curly coat grows continuously and sheds almost nothing. Ideal for moderate allergies. It requires a trim every 6-8 weeks and daily brushing.'},
      {h:'Carácter: alegría pura',hEn:'Temperament: pure joy',p:'Extremadamente sociables, raramente agresivos. Se adaptan a energía alta o tranquila. Excelente con niños y personas mayores.',pEn:'Extremely sociable, rarely aggressive. They adapt to high energy or calm. Excellent with children and older adults.'},
      {h:'Separación: punto débil',hEn:'Separation: a weak spot',p:'Detestan la soledad. Un Bichón solo muchas horas puede desarrollar ansiedad. Son perros de compañía en el sentido más literal.',pEn:'They hate being alone. A Bichon left alone for many hours can develop anxiety. They are companion dogs in the most literal sense.'},
      {h:'Salud dental: atención especial',hEn:'Dental health: special attention',p:'Acumulan sarro rápidamente. Cepillado dental 3 veces por semana desde cachorros.',pEn:'They build up tartar quickly. Brush their teeth 3 times a week from puppyhood.'},
    ],
    stat:'El Bichón Frisé fue el perro favorito de los nobles europeos del siglo XVI y aparece en pinturas de Francisco de Goya.',
    statEn:'The Bichon Frise was the favorite dog of 16th-century European nobles and appears in paintings by Francisco de Goya.',
    tips:['Corte profesional cada 6-8 semanas','Ideal para apartamentos y personas mayores','Primer perro excelente'],
    tipsEn:['Professional trim every 6-8 weeks','Ideal for apartments and older adults','An excellent first dog'],
    close:'El Bichón Frisé es uno de los perros de compañía más equilibrados. Si buscas alegría concentrada en un paquete pequeño, esta raza rara vez decepciona.',
    closeEn:'The Bichon Frise is one of the most well-balanced companion dogs. If you\'re looking for joy concentrated in a small package, this breed rarely disappoints.'
  },
  { id:48, cat:'razas', emoji:'💪', color:'#708090', img:'fotos-razas-sm/Bull Terrier.webp',
    title:'American Bully: el gigante gentil que el mundo malentendió',
    titleEn:'American Bully: The Gentle Giant the World Misunderstood',
    sub:'La verdad sobre una de las razas más incomprendidas y más leales',
    subEn:'The truth about one of the most misunderstood and most loyal breeds',
    date:'Mayo 2025', dateEn:'May 2025', read:5, tags:['american bully','bully','familia'],
    lead:'El American Bully fue criado específicamente para ser perro de familia. Es uno de los compañeros más cariñosos y pacientes, pero necesita socialización y estructura.',
    leadEn:'The American Bully was bred specifically to be a family dog. It\'s one of the most affectionate and patient companions, but it needs socialization and structure.',
    body:[
      {h:'Criado para la familia',hEn:'Bred for the family',p:'Desarrollado en los 90s combinando razas para crear un perro gentil, estable y tolerante. No de pelea.',pEn:'Developed in the 90s by combining breeds to create a gentle, stable, tolerant dog. Not a fighting dog.'},
      {h:'Temperamento: amor en tamaño XXL',hEn:'Temperament: love in XXL size',p:'Extremadamente afectuosos con su familia. Notable tolerancia con niños. Con extraños, reservados si bien socializados.',pEn:'Extremely affectionate with their family. Notable tolerance with children. Reserved with strangers when well socialized.'},
      {h:'Socialización temprana: no negociable',hEn:'Early socialization: non-negotiable',p:'Un Bully bien socializado es embajador de la raza. Uno mal criado refuerza estereotipos injustos.',pEn:'A well-socialized Bully is an ambassador for the breed. A poorly raised one reinforces unfair stereotypes.'},
      {h:'Legislación BSL',hEn:'BSL legislation',p:'Algunas ciudades tienen restricciones sobre razas tipo bully. Infórmate antes de adoptar.',pEn:'Some cities have restrictions on bully-type breeds. Do your research before adopting.'},
    ],
    stat:'El American Bully fue reconocido por el United Kennel Club en 2013 y en menos de una década se convirtió en una de las razas más populares en USA.',
    statEn:'The American Bully was recognized by the United Kennel Club in 2013 and, in less than a decade, became one of the most popular breeds in the US.',
    tips:['Socialización desde las 8 semanas','Entrenamiento básico de obediencia fundamental','Chequea regulaciones locales'],
    tipsEn:['Socialization from 8 weeks of age','Basic obedience training is essential','Check local regulations'],
    close:'Dar una oportunidad a un American Bully es entender que una raza no define al perro. El carácter lo construye el criador, el dueño y el entorno.',
    closeEn:'Giving an American Bully a chance means understanding that a breed doesn\'t define the dog. Character is built by the breeder, the owner, and the environment.'
  },
  { id:49, cat:'razas', emoji:'🐶', color:'#DAA520', img:'fotos-razas-sm/Cavapoo.webp',
    title:'Cavapoo: el híbrido perfecto que sí existe',
    titleEn:'Cavapoo: The Perfect Hybrid That Actually Exists',
    sub:'Por qué esta mezcla de Cavalier y Poodle arrasa en todo el mundo',
    subEn:'Why this Cavalier and Poodle mix is taking the world by storm',
    date:'Mayo 2025', dateEn:'May 2025', read:4, tags:['cavapoo','híbrido','apoyo emocional'],
    lead:'El Cavapoo combina la gentileza del Cavalier King Charles con la inteligencia y bajo derramamiento del Poodle. Uno de los perros de compañía más equilibrados del mercado.',
    leadEn:'The Cavapoo combines the gentleness of the Cavalier King Charles with the intelligence and low shedding of the Poodle. One of the most well-balanced companion dogs out there.',
    body:[
      {h:'Temperamento heredado de ambos',hEn:'A temperament inherited from both',p:'Del Cavalier: paciencia, gentileza, tolerancia. Del Poodle: inteligencia, entrenabilidad, bajo derramamiento.',pEn:'From the Cavalier: patience, gentleness, tolerance. From the Poodle: intelligence, trainability, low shedding.'},
      {h:'Ideal para apoyo emocional',hEn:'Ideal for emotional support',p:'Sensibilidad al estado de ánimo humano más inteligencia adaptable los hace excelentes perros ESA certificados.',pEn:'Sensitivity to human moods plus adaptable intelligence makes them excellent certified ESA dogs.'},
      {h:'Salud: ventaja del híbrido',hEn:'Health: the hybrid advantage',p:'Híbridos F1 suelen tener menos problemas genéticos. Pide certificados de salud cardíaca de los padres Cavalier.',pEn:'F1 hybrids tend to have fewer genetic problems. Ask for cardiac health certificates from the Cavalier parents.'},
      {h:'Tamaño variable',hEn:'Variable size',p:'Dependiendo del Poodle padre (toy o miniatura), puede pesar entre 5-12kg.',pEn:'Depending on the Poodle parent (toy or miniature), it can weigh between 11 and 26 lbs.'},
    ],
    stat:'El Cavapoo fue desarrollado en Australia en los años 90 y hoy es una de las cinco razas de diseño más demandadas en USA, UK y Australia.',
    statEn:'The Cavapoo was developed in Australia in the 1990s and is now one of the five most in-demand designer breeds in the US, UK, and Australia.',
    tips:['Certifica salud cardíaca de los padres','Excelente con niños, mayores y otras mascotas','Corte profesional cada 8 semanas'],
    tipsEn:['Verify the parents\' cardiac health','Excellent with children, older adults, and other pets','Professional trim every 8 weeks'],
    close:'El Cavapoo no es un perro de moda: es una combinación intencional que funciona. En manos de criador responsable, rara vez decepciona.',
    closeEn:'The Cavapoo isn\'t a fad dog: it\'s an intentional combination that works. In the hands of a responsible breeder, it rarely disappoints.'
  },
  { id:50, cat:'razas', emoji:'🤍', color:'#C0C0C0', img:'fotos-razas-sm/Maltese.webp',
    title:'Maltés: nieve en movimiento con carácter de gigante',
    titleEn:'Maltese: Snow in Motion with the Spirit of a Giant',
    sub:'Todo sobre el perro blanco más elegante del mundo',
    subEn:'Everything about the most elegant white dog in the world',
    date:'Mayo 2025', dateEn:'May 2025', read:4, tags:['maltés','maltese','pequeño'],
    lead:'El Maltés lleva más de 2,000 años siendo perro de la aristocracia. Su pelaje blanco, carácter afectuoso y adaptabilidad los hacen perfectos para apartamento.',
    leadEn:'The Maltese has been a dog of the aristocracy for more than 2,000 years. Its white coat, affectionate nature, and adaptability make it perfect for apartment living.',
    body:[
      {h:'Pelaje blanco: belleza exigente',hEn:'A white coat: demanding beauty',p:'No muda casi, pero requiere cepillado diario. Muchos optan por puppy cut para reducir el mantenimiento significativamente.',pEn:'It barely sheds, but it requires daily brushing. Many owners opt for a puppy cut to reduce upkeep significantly.'},
      {h:'Energía en cuerpo pequeño',hEn:'Energy in a small body',p:'Son juguetones y activos, no los perritos frágiles que parecen. Sensibles al trato brusco y ruido excesivo.',pEn:'They are playful and active, not the fragile little dogs they appear to be. Sensitive to rough handling and excessive noise.'},
      {h:'Salud dental: prioridad',hEn:'Dental health: a priority',p:'Acumulan sarro aceleradamente. Cepillado dental frecuente y chequeo veterinario anual de boca.',pEn:'They build up tartar rapidly. Frequent tooth brushing and an annual veterinary dental check.'},
      {h:'Manchas en la cara',hEn:'Tear staining on the face',p:'Su pelo blanco puede manchar alrededor de los ojos. Limpieza con toallitas dos veces al día y buena nutrición ayudan.',pEn:'Their white hair can stain around the eyes. Cleaning with wipes twice a day and good nutrition help.'},
    ],
    stat:'El Maltés aparece en vasijas griegas del año 500 a.C. y fue el perro favorito de Aristóteles, que lo mencionó en sus escritos.',
    statEn:'The Maltese appears on Greek vases from 500 B.C. and was the favorite dog of Aristotle, who mentioned it in his writings.',
    tips:['Cepillado diario o puppy cut','Ideal para apartamentos y personas mayores','Limpieza de zona ocular diaria'],
    tipsEn:['Daily brushing or a puppy cut','Ideal for apartments and older adults','Daily cleaning of the eye area'],
    close:'El Maltés es uno de los grandes clásicos. Milenios de compañía humana no son accidente: esta raza tiene algo genuinamente especial.',
    closeEn:'The Maltese is one of the great classics. Millennia of human companionship are no accident: this breed has something genuinely special.'
  },
  { id:51, cat:'razas', emoji:'🧡', color:'#FF8C00', img:'fotos-razas-sm/Pomeranian.webp',
    title:'Pomerania: el bola de pelo que no sabe que es pequeño',
    titleEn:'Pomeranian: The Ball of Fluff That Doesn\'t Know It\'s Small',
    sub:'Todo sobre el perro más fotogénico del mundo y sus cuidados reales',
    subEn:'Everything about the most photogenic dog in the world and its real care needs',
    date:'Mayo 2025', dateEn:'May 2025', read:4, tags:['pomerania','pomeranian','pequeño'],
    lead:'El Pomerania es la prueba de que el tamaño no define la personalidad. Valiente, vocal, curioso y completamente convencido de poder competir con perros 10 veces más grandes.',
    leadEn:'The Pomeranian is proof that size doesn\'t define personality. Brave, vocal, curious, and completely convinced it can take on dogs 10 times its size.',
    body:[
      {h:'Personalidad sin filtro',hEn:'An unfiltered personality',p:'Curiosos, alertas y vocales. Ladran ante cualquier estímulo. El entrenamiento de control de ladrido es prioritario desde cachorro.',pEn:'Curious, alert, and vocal. They bark at any stimulus. Bark-control training is a priority from puppyhood.'},
      {h:'La doble capa',hEn:'The double coat',p:'Cepillado 3-4 veces por semana. Dos veces al año, muda profusamente durante 2-3 semanas.',pEn:'Brushing 3-4 times a week. Twice a year, they shed profusely for 2-3 weeks.'},
      {h:'Dientes pequeños, problemas grandes',hEn:'Small teeth, big problems',p:'Acumulan sarro muy rápido. Cepillado dental frecuente obligatorio.',pEn:'They build up tartar very fast. Frequent tooth brushing is a must.'},
      {h:'Colapso traqueal',hEn:'Tracheal collapse',p:'Propensos a colapso traqueal. Usa arnés en lugar de collar siempre.',pEn:'Prone to tracheal collapse. Always use a harness instead of a collar.'},
    ],
    stat:'La Reina Victoria popularizó el Pomerania en el siglo XIX, reduciéndolo de 14kg a los 2-3kg actuales a través de la cría selectiva.',
    statEn:'Queen Victoria popularized the Pomeranian in the 19th century, shrinking it from 30 lbs to today\'s 4-7 lbs through selective breeding.',
    tips:['Arnés siempre, nunca collar','Entrenamiento de ladrido desde el primer mes','Corte profesional cada 8-10 semanas'],
    tipsEn:['Always a harness, never a collar','Bark training from the first month','Professional trim every 8-10 weeks'],
    close:'El Pomerania es pura vida concentrada. Si tienes paciencia para el ladrido y los cuidados del pelaje, tendrás un compañero con más personalidad que muchos perros grandes.',
    closeEn:'The Pomeranian is pure life, concentrated. If you have patience for the barking and the coat care, you\'ll have a companion with more personality than many large dogs.'
  },
  { id:52, cat:'razas', emoji:'😊', color:'#D2691E', img:'fotos-razas-sm/Pug.webp',
    title:'Pug (Carlino): el payaso de la familia que necesita cuidados especiales',
    titleEn:'Pug: The Family Clown That Needs Special Care',
    sub:'Todo lo que debes saber sobre salud braquicéfala y vida feliz',
    subEn:'Everything you need to know about brachycephalic health and a happy life',
    date:'Mayo 2025', dateEn:'May 2025', read:4, tags:['pug','carlino','braquicéfalo'],
    lead:'El Pug es uno de los perros más expresivos y carismáticos del mundo. Su cara arrugada y personalidad juguetona lo convierten en un imán de afecto, pero su anatomía requiere atención especial.',
    leadEn:'The Pug is one of the most expressive and charismatic dogs in the world. Its wrinkled face and playful personality make it a magnet for affection, but its anatomy requires special attention.',
    body:[
      {h:'Respiración: el tema central',hEn:'Breathing: the central issue',p:'Son braquicéfalos. El calor, ejercicio intenso y estrés pueden ser peligrosos. En verano, siempre en interiores con clima.',pEn:'They are brachycephalic. Heat, intense exercise, and stress can be dangerous. In summer, always indoors with climate control.'},
      {h:'Pliegues faciales: limpieza diaria',hEn:'Facial folds: daily cleaning',p:'Las arrugas acumulan humedad y pueden desarrollar infecciones. Limpieza con toallitas suaves a diario.',pEn:'The wrinkles trap moisture and can develop infections. Clean them with gentle wipes daily.'},
      {h:'Ojos: protección extra',hEn:'Eyes: extra protection',p:'Sus ojos prominentes son vulnerables a lesiones. Gotas lubricantes veterinarias y supervisión en ambientes con polvo.',pEn:'Their prominent eyes are vulnerable to injury. Veterinary lubricating drops and supervision in dusty environments.'},
      {h:'Peso: control estricto',hEn:'Weight: strict control',p:'El sobrepeso agrava todos sus problemas respiratorios. Las porciones deben medirse.',pEn:'Excess weight worsens all of their breathing problems. Portions must be measured.'},
    ],
    stat:'El Pug fue el perro oficial de la Casa de Orange en el siglo XVII y acompañó a Guillermo III en su invasión de Inglaterra en 1688.',
    statEn:'The Pug was the official dog of the House of Orange in the 17th century and accompanied William III in his invasion of England in 1688.',
    tips:['Nunca en calor extremo','Seguro veterinario recomendado','Limpieza de pliegues diaria','Arnés respiratorio especializado'],
    tipsEn:['Never in extreme heat','Pet insurance recommended','Daily fold cleaning','A specialized no-pull harness'],
    close:'Vivir con un Pug es reírse todos los días. Solo necesitas entender su anatomía para que esa vida sea larga y feliz.',
    closeEn:'Living with a Pug means laughing every day. You just need to understand its anatomy so that life is long and happy.'
  },
  { id:53, cat:'razas', emoji:'🖤', color:'#333333', img:'fotos-razas-sm/Rottweiler.webp',
    title:'Rottweiler: el guardián leal que necesita un líder claro',
    titleEn:'Rottweiler: The Loyal Guardian That Needs a Clear Leader',
    sub:'Cómo criar uno de los perros más poderosos del mundo de forma responsable',
    subEn:'How to responsibly raise one of the most powerful dogs in the world',
    date:'Mayo 2025', dateEn:'May 2025', read:5, tags:['rottweiler','guardián','familia'],
    lead:'El Rottweiler es uno de los perros más poderosos y leales del mundo. En manos responsables, un guardián excepcional y compañero profundamente afectuoso. Sin estructura, puede ser un problema.',
    leadEn:'The Rottweiler is one of the most powerful and loyal dogs in the world. In responsible hands, an exceptional guardian and a deeply affectionate companion. Without structure, it can be a problem.',
    body:[
      {h:'Líder claro: no negociable',hEn:'A clear leader: non-negotiable',p:'Necesitan consistencia desde el primer día. Sin estructura, toman decisiones por su cuenta, y a 50kg eso puede ser problemático.',pEn:'They need consistency from day one. Without structure, they make decisions on their own — and at 110 lbs, that can be a problem.'},
      {h:'Entrenamiento desde cachorro',hEn:'Training from puppyhood',p:'Obediencia básica, socialización con personas y animales, y exposición a diferentes entornos desde las 8 semanas.',pEn:'Basic obedience, socialization with people and animals, and exposure to different environments from 8 weeks of age.'},
      {h:'Afecto real con la familia',hEn:'Real affection with the family',p:'Son extremadamente afectuosos con su familia nuclear. Reservados con extraños pero amorosos en casa.',pEn:'They are extremely affectionate with their immediate family. Reserved with strangers but loving at home.'},
      {h:'Salud: displasia y corazón',hEn:'Health: dysplasia and the heart',p:'Propensos a displasia de cadera y cardiomiopatía. Chequeos anuales y peso saludable son esenciales.',pEn:'Prone to hip dysplasia and cardiomyopathy. Annual checkups and a healthy weight are essential.'},
    ],
    stat:'El Rottweiler desciende de los perros romanos que acompañaban a las legiones. Su nombre viene de Rottweil, ciudad alemana medieval.',
    statEn:'The Rottweiler descends from the Roman dogs that accompanied the legions. Its name comes from Rottweil, a medieval German town.',
    tips:['Entrenamiento profesional recomendado para primerizos','Socialización desde las 8 semanas','Legislación BSL en algunas ciudades: infórmate'],
    tipsEn:['Professional training recommended for first-time owners','Socialization from 8 weeks of age','BSL legislation in some cities: do your research'],
    close:'Un Rottweiler bien criado es uno de los perros más completos: guardián, compañero y amigo. La responsabilidad es proporcional a su tamaño y capacidad.',
    closeEn:'A well-raised Rottweiler is one of the most complete dogs there is: guardian, companion, and friend. The responsibility is proportional to its size and capability.'
  },
  // ── EDAD: PERROS Y GATOS EN AÑOS HUMANOS ──────────────────────────────────
  {
    id: 54, cat: 'guias', emoji: '🎂', color: '#1EB87A',
    img: 'fotos-razas/Beagle.webp',
    widget: 'ageChart',
    title: '¿Cuántos años tiene tu perro (o gato) en años humanos?',
    titleEn: 'How Old Is Your Dog (or Cat) in Human Years?',
    sub: 'Olvida la regla del "x7": la edad real depende del tamaño y la especie',
    subEn: 'Forget the "times 7" rule: real age depends on size and species',
    date: 'Mayo 2025', dateEn: 'May 2025', read: 6,
    tags: ['edad', 'salud', 'perros', 'gatos'],
    lead: 'Durante décadas repetimos que "1 año de perro = 7 años humanos". Es una simplificación que se queda corta. Los perros maduran muchísimo en su primer año, y luego el ritmo cambia según su tamaño. Los gatos siguen otra tabla. Aquí está cómo calcularlo bien, y por qué importa para su cuidado.',
    leadEn: 'For decades we\'ve repeated that "1 dog year = 7 human years." It\'s a simplification that falls short. Dogs mature enormously in their first year, and then the pace changes according to their size. Cats follow a different table. Here\'s how to calculate it correctly, and why it matters for their care.',
    body: [
      { h: 'El primer año vale por quince', hEn: 'The first year counts for fifteen', p: 'Al cumplir 1 año, un perro ya es prácticamente un adolescente: equivale a unos 15 años humanos. Al segundo año suma unos 9 más (≈24 humanos). Por eso un cachorro de 8 meses ya tiene energía, dientes y hormonas de "adolescente".', pEn: 'By the time it turns 1, a dog is practically a teenager: roughly the equivalent of 15 human years. By the second year it adds about 9 more (≈24 human). That\'s why an 8-month-old puppy already has the energy, teeth, and hormones of a "teenager."' },
      { h: 'Después del segundo año, el tamaño manda', hEn: 'After the second year, size rules', p: 'A partir del tercer año, cada año de perro suma distinto según su tamaño: razas pequeñas ~4 años humanos por año, medianas ~5, grandes ~6 y gigantes ~7. Por eso un Gran Danés es "senior" a los 6 y un Chihuahua sigue joven a esa edad. Las razas pequeñas viven más.', pEn: 'From the third year on, each dog year adds differently depending on size: small breeds ~4 human years per year, medium ~5, large ~6, and giant ~7. That\'s why a Great Dane is a "senior" at 6 while a Chihuahua is still young at that age. Small breeds live longer.' },
      { h: 'Los gatos tienen su propia tabla', hEn: 'Cats have their own table', p: 'El gato llega a ~15 años humanos en su primer año y ~24 en el segundo. Desde ahí, suma unos 4 años humanos por cada año felino. Un gato de 10 años equivale a unos 56 humanos: oficialmente senior, aunque no lo parezca.', pEn: 'A cat reaches ~15 human years in its first year and ~24 in the second. From there, it adds about 4 human years for every feline year. A 10-year-old cat is the equivalent of about 56 human years: officially a senior, even if it doesn\'t look it.' },
      { h: 'Por qué importa para su cuidado', hEn: 'Why it matters for their care', p: 'Saber la edad "real" cambia decisiones: cuándo pasar de comida de cachorro a adulto, cuándo empezar chequeos de senior (articulaciones, riñón, dientes), y qué nivel de ejercicio es seguro. Un perro grande de 7 años necesita los mismos cuidados que una persona de 50+, aunque siga jugando.', pEn: 'Knowing the "real" age changes decisions: when to switch from puppy food to adult, when to start senior checkups (joints, kidneys, teeth), and what level of exercise is safe. A large 7-year-old dog needs the same care as a person of 50+, even if it\'s still playing.' },
      { h: 'Etapas de vida en una mirada', hEn: 'Life stages at a glance', p: 'Cachorro/gatito (0–1 año): crecimiento y socialización. Joven (1–2 años): energía máxima. Adulto (2 años hasta ~75% de su vida): rutina estable. Senior (último ~25%): chequeos más frecuentes, comida específica y más descanso. Usa la calculadora de abajo con el tamaño de tu mascota.', pEn: 'Puppy/kitten (0–1 year): growth and socialization. Young (1–2 years): peak energy. Adult (from 2 years until ~75% of their life): a stable routine. Senior (the last ~25%): more frequent checkups, specialized food, and more rest. Use the calculator below with your pet\'s size.' },
    ],
    stat: 'Un perro pequeño puede vivir 15–16 años; uno gigante, 7–10. A mayor tamaño, más rápido envejecen: la genética del crecimiento acelera también el reloj biológico.',
    statEn: 'A small dog can live 15–16 years; a giant one, 7–10. The larger the size, the faster they age: the genetics of growth also speed up the biological clock.',
    tips: ['Cambia de comida cachorro→adulto cuando alcanza ~el 90% de su peso adulto', 'Inicia chequeos "senior" a los 7 años en razas grandes, a los 9–10 en pequeñas y gatos', 'El peso saludable es el factor #1 para alargar la vida', 'Cuida los dientes: la salud dental impacta corazón y riñones'],
    tipsEn: ['Switch from puppy food to adult when they reach ~90% of their adult weight', 'Start "senior" checkups at age 7 in large breeds, at 9–10 in small breeds and cats', 'A healthy weight is the #1 factor for a longer life', 'Take care of the teeth: dental health affects the heart and kidneys'],
    close: 'No hay una fórmula mágica única, pero entender que tu mascota envejece distinto según su especie y tamaño te ayuda a darle el cuidado correcto en cada etapa. Mira la tabla interactiva aquí abajo.',
    closeEn: 'There\'s no single magic formula, but understanding that your pet ages differently depending on its species and size helps you give it the right care at every stage. Take a look at the interactive table below.'
  }

];

BLOG.push(...BLOG_EXTRA);
// Regenerar BLOG_CATS con la nueva categoría
window.BLOG_CATS = ['todos', ...Object.keys(CAT_META)];

Object.assign(window, { BLOG, CAT_META, BLOG_CATS });
