(function(){
const DOG_BREEDS = [
  // ── SMALL ──────────────────────────────────────────────
  {
    id: "french-bulldog",
    name: "French Bulldog",
    es: "Bulldog Franc\xE9s",
    emoji: "\u{1F436}",
    photo: "fotos-razas/French Bulldog.webp",
    size: "small",
    coat: ["short"],
    hypo: false,
    energy: 2,
    grooming: 1,
    shedding: 2,
    trainability: 3,
    barking: 2,
    family: 5,
    kids: 5,
    pets: 4,
    apartment: 5,
    origin: "Francia / Inglaterra",
    originEn: "France / England",
    flag: "\u{1F1EB}\u{1F1F7}",
    weight: "8\u201313 kg",
    height: "27\u201335 cm",
    lifespan: "10\u201312 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Adaptable", "Juguet\xF3n", "Leal", "Alerta", "Cari\xF1oso"],
    temperamentEn: ["Adaptable", "Playful", "Loyal", "Alert", "Affectionate"],
    bestFor: ["Apartamentos", "Familias", "Adultos mayores", "Due\xF1os primerizos"],
    bestForEn: ["Apartments", "Families", "Seniors", "First-time owners"],
    desc: "El Bulldog Franc\xE9s es un compa\xF1ero encantador con orejas en forma de murci\xE9lago. Descendiente de Bulldogs ingleses llevados a Francia en el siglo XIX. Altamente adaptable, puede vivir en apartamento o casa, con ni\xF1os o adultos mayores. Tiene sentido del humor inigualable y lealtad profunda.",
    descEn: "The French Bulldog is a charming companion with bat-like ears. Descended from English Bulldogs brought to France in the 1800s. Highly adaptable \u2014 thrives in apartments or houses, with kids or seniors. Unmistakable sense of humor and deep loyalty.",
    care: "Limpiar pliegues faciales a diario. M\xEDnimo cepillado. Sensible al calor \u2014 nunca ejercitar en d\xEDas calurosos.",
    careEn: "Wipe facial folds daily. Minimal brushing. Heat-sensitive \u2014 avoid exercise in hot weather.",
    health: "Braquic\xE9falo \u2014 propenso a problemas respiratorios. Vigilar problemas espinales y alergias.",
    healthEn: "Brachycephalic \u2014 prone to breathing issues. Watch for spinal problems and allergies.",
    mixes: [
      { name: "Frenchton", parents: "French Bulldog + Boston Terrier", desc: "M\xE1s activo que el Frenchie puro, mejor tolerancia al calor. Temperamento juguet\xF3n y cuerpo compacto." },
      { name: "Frug", parents: "French Bulldog + Pug", desc: "Cara ultrachata y personalidad divertida. Muy cari\xF1oso. Requiere vigilancia respiratoria." },
      { name: "French Bullhuahua", parents: "French Bulldog + Chihuahua", desc: "Peque\xF1o y alerta. Hereda la valent\xEDa del Chihuahua y el humor del Frenchie." }
    ]
  },
  {
    id: "yorkshire-terrier",
    name: "Yorkshire Terrier",
    es: "Yorkshire Terrier",
    emoji: "\u{1F429}",
    photo: "fotos-razas/Yorkshire Terrier.webp",
    size: "small",
    coat: ["long", "smooth"],
    hypo: true,
    energy: 3,
    grooming: 4,
    shedding: 1,
    trainability: 3,
    barking: 4,
    family: 4,
    kids: 3,
    pets: 3,
    apartment: 5,
    origin: "Inglaterra",
    originEn: "England",
    flag: "\u{1F1EC}\u{1F1E7}",
    weight: "2\u20133.2 kg",
    height: "17\u201323 cm",
    lifespan: "13\u201316 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Valiente", "Independiente", "Curioso", "Cari\xF1oso", "Energ\xE9tico"],
    temperamentEn: ["Bold", "Independent", "Curious", "Affectionate", "Energetic"],
    bestFor: ["Apartamentos", "Adultos", "Personas activas"],
    bestForEn: ["Apartments", "Adults", "Active people"],
    desc: "El Yorkshire Terrier naci\xF3 en el norte de Inglaterra para cazar ratas en minas y f\xE1bricas textiles. Hoy es uno de los perros de compa\xF1\xEDa m\xE1s amados del mundo. A pesar de su peque\xF1o tama\xF1o, tiene una personalidad enorme: valiente, curioso e independiente. Su pelaje sedoso requiere cuidado regular pero no suelta mucho pelo.",
    descEn: "The Yorkshire Terrier was bred in northern England to hunt rats in mines and textile mills. Today it's one of the world's most beloved companions. Despite its small size, it has an enormous personality: brave, curious, and independent. Its silky coat requires regular care but sheds minimally.",
    care: "Cepillado diario para evitar nudos. Visitas al groomer cada 6\u20138 semanas. Limpieza dental regular.",
    careEn: "Daily brushing to prevent tangles. Groomer visits every 6\u20138 weeks. Regular dental care.",
    health: "Propenso a problemas dentales, luxaci\xF3n de r\xF3tula y colapso traqueal. Alimentaci\xF3n de calidad esencial.",
    healthEn: "Prone to dental issues, patellar luxation, and tracheal collapse. High-quality diet essential.",
    mixes: [
      { name: "Morkie", parents: "Maltese + Yorkshire Terrier", desc: "Pelaje suave y temperamento cari\xF1oso. Muy sociable, ideal para apartamentos y familias sin ni\xF1os peque\xF1os." },
      { name: "Chorkie", parents: "Chihuahua + Yorkshire Terrier", desc: "Peque\xF1o, activo y lleno de personalidad. Leal a su due\xF1o principal y desconfiado con extra\xF1os." },
      { name: "Shorkie", parents: "Shih Tzu + Yorkshire Terrier", desc: "D\xF3cil y amigable. Combina la dulzura del Shih Tzu con la energ\xEDa del Yorkie. Pelaje suave y poco derramante." },
      { name: "Borkie", parents: "Beagle + Yorkshire Terrier", desc: "Curioso y juguet\xF3n. Hereda la nariz del Beagle y la valent\xEDa del Yorkie. Ideal para familias activas." }
    ]
  },
  {
    id: "pomeranian",
    name: "Pomeranian",
    es: "Pomerania",
    emoji: "\u{1F98A}",
    photo: "fotos-razas/Pomeranian.webp",
    size: "small",
    coat: ["long"],
    hypo: false,
    energy: 3,
    grooming: 4,
    shedding: 3,
    trainability: 4,
    barking: 4,
    family: 4,
    kids: 3,
    pets: 3,
    apartment: 5,
    origin: "Alemania / Polonia",
    originEn: "Germany / Poland",
    flag: "\u{1F1E9}\u{1F1EA}",
    weight: "1.8\u20133.5 kg",
    height: "18\u201322 cm",
    lifespan: "12\u201316 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Vivaz", "Curioso", "Audaz", "Amigable", "Extrovertido"],
    temperamentEn: ["Lively", "Curious", "Bold", "Friendly", "Extroverted"],
    bestFor: ["Apartamentos", "Adultos", "Personas mayores"],
    bestForEn: ["Apartments", "Adults", "Seniors"],
    desc: "El Pomerania es un perro peque\xF1o de gran coraz\xF3n, con su caracter\xEDstico pelaje esponjoso y su expresi\xF3n de zorro. Descendiente de perros de trineo del \xC1rtico, fue reducido de tama\xF1o por la realeza europea, especialmente la Reina Victoria. Vivaz y activo, le encanta aprender trucos y ser el centro de atenci\xF3n.",
    descEn: "The Pomeranian is a small dog with a big heart, with its characteristic fluffy coat and fox-like expression. Descended from Arctic sled dogs, it was miniaturized by European royalty, especially Queen Victoria. Lively and active, it loves learning tricks and being the center of attention.",
    care: "Cepillado 2\u20133 veces por semana. Ba\xF1o mensual. Evitar calor excesivo por su doble capa.",
    careEn: "Brush 2\u20133 times weekly. Monthly bath. Avoid excessive heat due to double coat.",
    health: "Propenso a luxaci\xF3n de r\xF3tula, problemas dentales y colapso traqueal.",
    healthEn: "Prone to patellar luxation, dental problems, and tracheal collapse.",
    mixes: [
      { name: "Pomchi", parents: "Pomeranian + Chihuahua", desc: "Peque\xF1o y valiente. Hereda el pelaje del Pomerania y la actitud del Chihuahua. Muy leal a su due\xF1o." },
      { name: "Pomsky", parents: "Pomeranian + Husky Siberiano", desc: "Adorable combinaci\xF3n con ojos penetrantes del Husky y el tama\xF1o manejable del Pomerania. Alta demanda." },
      { name: "Pomapoo", parents: "Pomeranian + Poodle", desc: "Inteligente y de bajo derramamiento. Pelaje suave y rizado. Muy sociable y adaptable." }
    ]
  },
  {
    id: "chihuahua",
    name: "Chihuahua",
    es: "Chihuahua",
    emoji: "\u{1F415}",
    photo: "fotos-razas/Chihuahua.webp",
    size: "small",
    coat: ["short", "long"],
    hypo: false,
    energy: 3,
    grooming: 2,
    shedding: 2,
    trainability: 3,
    barking: 4,
    family: 3,
    kids: 2,
    pets: 3,
    apartment: 5,
    origin: "M\xE9xico",
    originEn: "Mexico",
    flag: "\u{1F1F2}\u{1F1FD}",
    weight: "1.5\u20133 kg",
    height: "15\u201323 cm",
    lifespan: "14\u201317 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Valiente", "Leal", "Curioso", "Alerta", "Independiente"],
    temperamentEn: ["Bold", "Loyal", "Curious", "Alert", "Independent"],
    bestFor: ["Apartamentos", "Adultos", "Una sola persona"],
    bestForEn: ["Apartments", "Adults", "Single owners"],
    desc: "El Chihuahua es la raza m\xE1s peque\xF1a del mundo y una de las m\xE1s antiguas de Am\xE9rica. Originario de M\xE9xico, lleva el nombre del estado donde fue descubierto. Tiene una personalidad enorme en un cuerpo diminuto. Es incre\xEDblemente leal a su due\xF1o principal y puede ser desconfiado con extra\xF1os. Ideal para adultos que buscan un compa\xF1ero constante.",
    descEn: "The Chihuahua is the world's smallest breed and one of the oldest in the Americas. Originating in Mexico, named after the state where it was discovered. It has an enormous personality in a tiny body. Incredibly loyal to its main owner and can be wary of strangers. Ideal for adults seeking a constant companion.",
    care: "Poco mantenimiento en pelaje corto. Los de pelo largo requieren cepillado regular. Muy sensible al fr\xEDo.",
    careEn: "Low maintenance for short coat. Long-coated need regular brushing. Very cold-sensitive.",
    health: "Propenso a problemas dentales, luxaci\xF3n de r\xF3tula y fontanela abierta. Huesos fr\xE1giles.",
    healthEn: "Prone to dental issues, patellar luxation, and open fontanelle. Fragile bones.",
    mixes: [
      { name: "Chorkie", parents: "Chihuahua + Yorkshire Terrier", desc: "Peque\xF1o y lleno de energ\xEDa. Personalidad fuerte y gran valent\xEDa para su tama\xF1o." },
      { name: "Chion", parents: "Chihuahua + Papillon", desc: "Elegante y vivaz. Hereda las orejas caracter\xEDsticas del Papillon con el temperamento del Chihuahua." },
      { name: "Pomchi", parents: "Chihuahua + Pomeranian", desc: "Esponjoso y atrevido. Combina el pelaje del Pomerania con la audacia del Chihuahua." }
    ]
  },
  {
    id: "maltese",
    name: "Maltese",
    es: "Malt\xE9s",
    emoji: "\u{1F429}",
    photo: "fotos-razas/Maltese.webp",
    size: "small",
    coat: ["long", "smooth"],
    hypo: true,
    energy: 2,
    grooming: 4,
    shedding: 1,
    trainability: 4,
    barking: 3,
    family: 5,
    kids: 3,
    pets: 4,
    apartment: 5,
    origin: "Malta / Mediterr\xE1neo",
    originEn: "Malta / Mediterranean",
    flag: "\u{1F1F2}\u{1F1F9}",
    weight: "1.4\u20133.6 kg",
    height: "20\u201325 cm",
    lifespan: "12\u201315 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Gentil", "Juguet\xF3n", "Responsivo", "Cari\xF1oso", "Elegante"],
    temperamentEn: ["Gentle", "Playful", "Responsive", "Affectionate", "Elegant"],
    bestFor: ["Apartamentos", "Adultos", "Apoyo emocional"],
    bestForEn: ["Apartments", "Adults", "Emotional support"],
    desc: "El Malt\xE9s es una de las razas m\xE1s antiguas del mundo, con m\xE1s de 2.000 a\xF1os de historia como perro de compa\xF1\xEDa de la nobleza mediterr\xE1nea. Su pelaje blanco como la seda y su car\xE1cter gentil lo hacen ideal como perro de apoyo emocional. Es hipoalerg\xE9nico y suelta muy poco pelo, perfecto para personas con alergias leves.",
    descEn: "The Maltese is one of the world's oldest breeds, with over 2,000 years of history as a companion to Mediterranean nobility. Its silky white coat and gentle character make it ideal as an emotional support dog. Hypoallergenic and minimal shedding \u2014 perfect for people with mild allergies.",
    care: "Cepillado diario esencial. Muchos due\xF1os optan por corte corto (puppy cut). Limpieza ocular para evitar manchas.",
    careEn: "Daily brushing essential. Many owners opt for a puppy cut. Eye cleaning to prevent tear stains.",
    health: "Relativamente saludable. Vigilar luxaci\xF3n de r\xF3tula, problemas dentales y manchas lagrimales.",
    healthEn: "Relatively healthy. Watch for patellar luxation, dental issues, and tear staining.",
    mixes: [
      { name: "Maltipoo", parents: "Maltese + Poodle", desc: "Muy popular. Hipoalerg\xE9nico, inteligente y adorable. Hereda lo mejor de ambas razas." },
      { name: "Morkie", parents: "Maltese + Yorkshire Terrier", desc: "Pelaje suave y gran personalidad. Muy adaptable y cari\xF1oso con su familia." },
      { name: "Malshi", parents: "Maltese + Shih Tzu", desc: "Gentil y sociable. Ideal para apartamentos y familias sin ni\xF1os muy peque\xF1os." }
    ]
  },
  {
    id: "shih-tzu",
    name: "Shih Tzu",
    es: "Shih Tzu",
    emoji: "\u{1F436}",
    photo: "fotos-razas/Shih Tzu.webp",
    size: "small",
    coat: ["long"],
    hypo: false,
    energy: 2,
    grooming: 4,
    shedding: 1,
    trainability: 3,
    barking: 2,
    family: 5,
    kids: 4,
    pets: 5,
    apartment: 5,
    origin: "China / Tibet",
    originEn: "China / Tibet",
    flag: "\u{1F1E8}\u{1F1F3}",
    weight: "4\u20137.2 kg",
    height: "20\u201328 cm",
    lifespan: "10\u201318 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Amigable", "Confiado", "Vivo", "Cari\xF1oso", "Independiente"],
    temperamentEn: ["Friendly", "Confident", "Lively", "Affectionate", "Independent"],
    bestFor: ["Apartamentos", "Familias", "Adultos mayores", "Apoyo emocional"],
    bestForEn: ["Apartments", "Families", "Seniors", "Emotional support"],
    desc: 'El Shih Tzu, cuyo nombre significa "Le\xF3n peque\xF1o" en chino, fue criado durante siglos en los palacios imperiales de China y Tibet. Es uno de los perros de compa\xF1\xEDa m\xE1s antiguos y amados del mundo. D\xF3cil, amigable con todos y sorprendentemente robusto para su tama\xF1o. Excelente con ni\xF1os, adultos mayores y otras mascotas.',
    descEn: `The Shih Tzu, whose name means "little lion" in Chinese, was bred for centuries in the imperial palaces of China and Tibet. One of the world's oldest and most beloved companions. Docile, friendly with everyone, and surprisingly sturdy for its size. Excellent with children, seniors, and other pets.`,
    care: "Cepillado diario. Corte profesional cada 6\u20138 semanas. Limpieza regular de ojos y pliegues faciales.",
    careEn: "Daily brushing. Professional grooming every 6\u20138 weeks. Regular eye and facial fold cleaning.",
    health: "Generalmente saludable. Vigilar problemas oculares, problemas respiratorios leves y luxaci\xF3n de r\xF3tula.",
    healthEn: "Generally healthy. Watch for eye problems, mild breathing issues, and patellar luxation.",
    mixes: [
      { name: "Shorkie", parents: "Shih Tzu + Yorkshire Terrier", desc: "Pelaje sedoso y mucha personalidad. Juguet\xF3n y leal. Ideal para apartamentos." },
      { name: "Malshi", parents: "Shih Tzu + Maltese", desc: "Gentil y f\xE1cil de manejar. Poco derramante, ideal para personas con alergias leves." },
      { name: "Shichon", parents: "Shih Tzu + Bichon Fris\xE9", desc: 'Tambi\xE9n llamado "Teddy Bear". Pelo rizado suave, car\xE1cter dulce. Muy popular como perro de compa\xF1\xEDa.' }
    ]
  },
  {
    id: "miniature-schnauzer",
    name: "Miniature Schnauzer",
    es: "Schnauzer Miniatura",
    emoji: "\u{1F415}",
    photo: "fotos-razas/Miniature Schnauzer.webp",
    size: "small",
    coat: ["wiry"],
    hypo: true,
    energy: 3,
    grooming: 3,
    shedding: 1,
    trainability: 5,
    barking: 3,
    family: 5,
    kids: 5,
    pets: 3,
    apartment: 4,
    origin: "Alemania",
    originEn: "Germany",
    flag: "\u{1F1E9}\u{1F1EA}",
    weight: "5\u20139 kg",
    height: "30\u201336 cm",
    lifespan: "12\u201315 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Amigable", "Obediente", "Inteligente", "Animado", "Alerta"],
    temperamentEn: ["Friendly", "Obedient", "Intelligent", "Spirited", "Alert"],
    bestFor: ["Casas con patio", "Familias con ni\xF1os", "Personas activas"],
    bestForEn: ["Houses with yard", "Families with kids", "Active people"],
    desc: "El Schnauzer Miniatura es el m\xE1s popular de los tres tama\xF1os de Schnauzer. Originado en Alemania como perro cazador de ratas, combina inteligencia, robustez y un car\xE1cter adorable. Hipoalerg\xE9nico, suelta muy poco pelo y se lleva muy bien con ni\xF1os. Es obediente, f\xE1cil de entrenar y muy adaptable.",
    descEn: "The Miniature Schnauzer is the most popular of the three Schnauzer sizes. Originating in Germany as a rat-hunting dog, it combines intelligence, robustness, and an adorable character. Hypoallergenic, minimal shedding, and great with children. Obedient, easy to train, and very adaptable.",
    care: "Stripping o recorte cada 5\u20138 semanas. Cepillado regular. Barba necesita limpieza despu\xE9s de comer.",
    careEn: "Stripping or clipping every 5\u20138 weeks. Regular brushing. Beard needs cleaning after meals.",
    health: "Generalmente robusto. Vigilar pancreatitis, c\xE1lculos renales y problemas oculares.",
    healthEn: "Generally robust. Watch for pancreatitis, kidney stones, and eye problems.",
    mixes: [
      { name: "Schnoodle", parents: "Schnauzer + Poodle", desc: "Inteligente y casi sin derramamiento. Hereda lo mejor de dos razas altamente entrenables." },
      { name: "Snorkie", parents: "Schnauzer Miniatura + Yorkie", desc: "Peque\xF1o y valiente. Muy en\xE9rgico y cari\xF1oso con su familia." }
    ]
  },
  {
    id: "cavalier-kcs",
    name: "Cavalier King Charles",
    es: "Cavalier King Charles",
    emoji: "\u{1F436}",
    photo: "fotos-razas/Cavalier King Charles Spaniel.webp",
    size: "small",
    coat: ["long", "smooth"],
    hypo: false,
    energy: 2,
    grooming: 3,
    shedding: 2,
    trainability: 4,
    barking: 2,
    family: 5,
    kids: 5,
    pets: 5,
    apartment: 5,
    origin: "Inglaterra",
    originEn: "England",
    flag: "\u{1F1EC}\u{1F1E7}",
    weight: "5.9\u20138.2 kg",
    height: "30\u201333 cm",
    lifespan: "9\u201314 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Gentil", "Afectuoso", "Sociable", "D\xF3cil", "Adaptable"],
    temperamentEn: ["Gentle", "Affectionate", "Sociable", "Graceful", "Adaptable"],
    bestFor: ["Apartamentos", "Apoyo emocional", "Adultos mayores", "Familias tranquilas"],
    bestForEn: ["Apartments", "Emotional support", "Seniors", "Calm families"],
    desc: "El Cavalier King Charles Spaniel es considerado el perro de compa\xF1\xEDa por excelencia. Criado para ser el perro de falda de la realeza inglesa, tiene un temperamento excepcionalmente gentil y cari\xF1oso. Se adapta a cualquier hogar, ama a ni\xF1os y adultos por igual, y tiene un instinto natural para brindar apoyo emocional.",
    descEn: "The Cavalier King Charles Spaniel is considered the quintessential companion dog. Bred to be the lap dog of English royalty, it has an exceptionally gentle and affectionate temperament. Adapts to any home, loves children and adults alike, and has a natural instinct for providing emotional support.",
    care: "Cepillado 3\u20134 veces por semana. Revisar orejas regularmente. Evitar calor excesivo.",
    careEn: "Brush 3\u20134 times weekly. Regular ear checks. Avoid excessive heat.",
    health: "Propenso a enfermedades card\xEDacas (MVD) y siringomielia. Comprar solo de criadores que realizan pruebas card\xEDacas.",
    healthEn: "Prone to heart disease (MVD) and syringomyelia. Only buy from breeders who do cardiac testing.",
    mixes: [
      { name: "Cavapoo", parents: "Cavalier KCS + Poodle", desc: "Muy popular. Bajo derramamiento, inteligente y con el temperamento gentil del Cavalier. Ideal para apoyo emocional." },
      { name: "Cavachon", parents: "Cavalier KCS + Bichon Fris\xE9", desc: "Dulce y juguet\xF3n. Pelaje suave y poco derramante. Excelente con ni\xF1os." }
    ]
  },
  {
    id: "dachshund",
    name: "Dachshund",
    es: "Dachshund (Teckel)",
    emoji: "\u{1F32D}",
    photo: "fotos-razas/Dachshund.webp",
    size: "small",
    coat: ["short", "long", "wiry"],
    hypo: false,
    energy: 3,
    grooming: 2,
    shedding: 2,
    trainability: 3,
    barking: 3,
    family: 4,
    kids: 3,
    pets: 3,
    apartment: 4,
    origin: "Alemania",
    originEn: "Germany",
    flag: "\u{1F1E9}\u{1F1EA}",
    weight: "3.6\u201314.5 kg",
    height: "13\u201323 cm",
    lifespan: "12\u201316 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Curioso", "Amigable", "Atrevido", "Obstinado", "Cari\xF1oso"],
    temperamentEn: ["Curious", "Friendly", "Bold", "Stubborn", "Affectionate"],
    bestFor: ["Apartamentos", "Adultos", "Familias sin ni\xF1os muy peque\xF1os"],
    bestForEn: ["Apartments", "Adults", "Families without toddlers"],
    desc: 'El Dachshund, tambi\xE9n conocido como Teckel o "salchicha", fue criado en Alemania para cazar tejones en sus madrigueras. Su cuerpo largo y patas cortas son perfectos para meterse en t\xFAneles. Tiene una personalidad enorme, curiosa y a veces obstinada. Viene en dos tama\xF1os (est\xE1ndar y miniatura) y tres tipos de pelaje.',
    descEn: 'The Dachshund, also known as "wiener dog," was bred in Germany to hunt badgers in their burrows. Its long body and short legs are perfect for entering tunnels. It has an enormous, curious, and sometimes stubborn personality. Comes in two sizes (standard and miniature) and three coat types.',
    care: "Vigilar el peso \u2014 la obesidad da\xF1a su columna. Evitar saltos altos. Cepillado seg\xFAn el tipo de pelaje.",
    careEn: "Monitor weight \u2014 obesity damages the spine. Avoid high jumps. Grooming depends on coat type.",
    health: "Propenso a DDIV (enfermedad del disco intervertebral). Clave mantener peso saludable.",
    healthEn: "Prone to IVDD (intervertebral disc disease). Maintaining healthy weight is key.",
    mixes: [
      { name: "Dorkie", parents: "Dachshund + Yorkshire Terrier", desc: "Peque\xF1o y audaz. Hereda la curiosidad del Dachshund con la energ\xEDa del Yorkie." },
      { name: "Doxle", parents: "Dachshund + Beagle", desc: "Curioso y sociable. Excelente olfato heredado del Beagle con el temperamento del Dachshund." }
    ]
  },
  {
    id: "boston-terrier",
    name: "Boston Terrier",
    es: "Boston Terrier",
    emoji: "\u{1F436}",
    photo: "fotos-razas/Boston Terrier.webp",
    size: "small",
    coat: ["short"],
    hypo: false,
    energy: 3,
    grooming: 1,
    shedding: 2,
    trainability: 4,
    barking: 2,
    family: 5,
    kids: 5,
    pets: 4,
    apartment: 5,
    origin: "Estados Unidos",
    originEn: "United States",
    flag: "\u{1F1FA}\u{1F1F8}",
    weight: "4.5\u201311 kg",
    height: "38\u201343 cm",
    lifespan: "11\u201313 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Amigable", "Brillante", "Divertido", "Adaptable", "Cari\xF1oso"],
    temperamentEn: ["Friendly", "Bright", "Amusing", "Adaptable", "Affectionate"],
    bestFor: ["Apartamentos", "Familias", "Primeros due\xF1os"],
    bestForEn: ["Apartments", "Families", "First-time owners"],
    desc: 'El Boston Terrier, conocido como el "Caballero Americano", es una de las pocas razas creadas en Estados Unidos. Con su esmoquin blanco y negro y sus enormes ojos expresivos, es el compa\xF1ero perfecto para la vida urbana. Amigable, divertido y adaptable, se lleva bien con toda la familia.',
    descEn: `The Boston Terrier, known as the "American Gentleman," is one of the few breeds created in the United States. With its black and white tuxedo and huge expressive eyes, it's the perfect companion for city life. Friendly, amusing, and adaptable \u2014 gets along great with the whole family.`,
    care: "M\xEDnimo mantenimiento de pelaje. Limpiar pliegues faciales. Sensible al calor y al fr\xEDo extremo.",
    careEn: "Minimal coat care. Clean facial folds. Sensitive to extreme heat and cold.",
    health: "Braquic\xE9falo \u2014 vigilar respiraci\xF3n. Propenso a cataratas y problemas articulares.",
    healthEn: "Brachycephalic \u2014 monitor breathing. Prone to cataracts and joint problems.",
    mixes: [
      { name: "Frenchton", parents: "French Bulldog + Boston Terrier", desc: "Lo mejor de dos mundos. Activo y robusto, con temperamento juguet\xF3n y amigable." },
      { name: "Bossi-Poo", parents: "Boston Terrier + Poodle", desc: "Inteligente y bajo mantenimiento. Hereda el humor del Boston con la inteligencia del Poodle." }
    ]
  },
  // ── MEDIUM ─────────────────────────────────────────────
  {
    id: "beagle",
    name: "Beagle",
    es: "Beagle",
    emoji: "\u{1F415}",
    photo: "fotos-razas/Beagle.webp",
    size: "medium",
    coat: ["short"],
    hypo: false,
    energy: 4,
    grooming: 2,
    shedding: 3,
    trainability: 3,
    barking: 4,
    family: 5,
    kids: 5,
    pets: 4,
    apartment: 3,
    origin: "Inglaterra",
    originEn: "England",
    flag: "\u{1F1EC}\u{1F1E7}",
    weight: "9\u201311 kg",
    height: "33\u201341 cm",
    lifespan: "10\u201315 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Amigable", "Curioso", "Determinado", "Juguet\xF3n", "Leal"],
    temperamentEn: ["Friendly", "Curious", "Determined", "Playful", "Loyal"],
    bestFor: ["Casas con patio", "Familias con ni\xF1os", "Personas activas"],
    bestForEn: ["Houses with yard", "Families with kids", "Active people"],
    desc: "El Beagle es uno de los perros de caza m\xE1s populares y amados como mascota familiar. Con su nariz extraordinaria y su car\xE1cter sociable, es un compa\xF1ero incansable para ni\xF1os. Necesita ejercicio regular y estimulaci\xF3n mental. Tiende a seguir olores, por lo que un jard\xEDn cercado es ideal.",
    descEn: "The Beagle is one of the most popular hunting dogs and beloved as a family pet. With its extraordinary nose and sociable character, it's a tireless companion for children. Needs regular exercise and mental stimulation. Tends to follow scents, so a fenced yard is ideal.",
    care: "Ejercicio diario obligatorio. Revisar orejas regularmente para evitar infecciones. Vigilar el peso.",
    careEn: "Daily exercise essential. Check ears regularly to prevent infections. Monitor weight.",
    health: "Generalmente saludable. Vigilar epilepsia, problemas de tiroides y obesidad.",
    healthEn: "Generally healthy. Watch for epilepsy, thyroid issues, and obesity.",
    mixes: [
      { name: "Puggle", parents: "Beagle + Pug", desc: "Sociable y divertido. Menos propenso a problemas respiratorios que el Pug puro." },
      { name: "Borkie", parents: "Beagle + Yorkshire Terrier", desc: "Curioso y energ\xE9tico. Hereda la nariz del Beagle con la personalidad del Yorkie." },
      { name: "Beabull", parents: "Beagle + Bulldog", desc: "Gentil y resistente. Combina la curiosidad del Beagle con la calma del Bulldog." }
    ]
  },
  {
    id: "cocker-spaniel",
    name: "Cocker Spaniel",
    es: "Cocker Spaniel",
    emoji: "\u{1F436}",
    photo: "fotos-razas/Cocker Spaniel.webp",
    size: "medium",
    coat: ["long", "smooth"],
    hypo: false,
    energy: 3,
    grooming: 4,
    shedding: 3,
    trainability: 4,
    barking: 3,
    family: 5,
    kids: 5,
    pets: 4,
    apartment: 3,
    origin: "Espa\xF1a / Inglaterra",
    originEn: "Spain / England",
    flag: "\u{1F1EC}\u{1F1E7}",
    weight: "9\u201314.5 kg",
    height: "36\u201343 cm",
    lifespan: "10\u201314 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Gentil", "Cari\xF1oso", "Activo", "Juguet\xF3n", "Feliz"],
    temperamentEn: ["Gentle", "Affectionate", "Active", "Playful", "Merry"],
    bestFor: ["Familias con ni\xF1os", "Casas con patio", "Personas activas"],
    bestForEn: ["Families with kids", "Houses with yard", "Active people"],
    desc: "El Cocker Spaniel americano es conocido por sus hermosas orejas ca\xEDdas y su expresi\xF3n dulce. Excelente perro de familia, gentil con ni\xF1os y muy afectuoso. Fue durante muchos a\xF1os la raza m\xE1s popular en Estados Unidos. Necesita ejercicio regular y cuidado frecuente de su pelaje largo y sedoso.",
    descEn: "The American Cocker Spaniel is known for its beautiful droopy ears and sweet expression. Excellent family dog, gentle with children and very affectionate. Was for many years the most popular breed in the United States. Needs regular exercise and frequent grooming of its long, silky coat.",
    care: "Cepillado diario. Visita al groomer cada 6\u20138 semanas. Limpieza regular de o\xEDdos para prevenir infecciones.",
    careEn: "Daily brushing. Groomer every 6\u20138 weeks. Regular ear cleaning to prevent infections.",
    health: "Propenso a problemas oculares (cataratas), infecciones de o\xEDdo y problemas de cadera.",
    healthEn: "Prone to eye problems (cataracts), ear infections, and hip problems.",
    mixes: [
      { name: "Cockapoo", parents: "Cocker Spaniel + Poodle", desc: "Una de las primeras razas de dise\xF1o. Muy popular, bajo derramamiento, inteligente y cari\xF1oso." },
      { name: "Spangold", parents: "Cocker Spaniel + Golden Retriever", desc: "Afectuoso y activo. Hereda la lealtad del Golden con la elegancia del Cocker." }
    ]
  },
  {
    id: "border-collie",
    name: "Border Collie",
    es: "Border Collie",
    emoji: "\u{1F415}",
    photo: "fotos-razas/Border Collie.webp",
    size: "medium",
    coat: ["long", "smooth"],
    hypo: false,
    energy: 5,
    grooming: 3,
    shedding: 3,
    trainability: 5,
    barking: 3,
    family: 4,
    kids: 4,
    pets: 3,
    apartment: 1,
    origin: "Reino Unido",
    originEn: "United Kingdom",
    flag: "\u{1F1EC}\u{1F1E7}",
    weight: "12\u201320 kg",
    height: "46\u201356 cm",
    lifespan: "12\u201315 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Energ\xE9tico", "Inteligente", "Alerta", "Receptivo", "Trabajador"],
    temperamentEn: ["Energetic", "Intelligent", "Alert", "Responsive", "Hard-working"],
    bestFor: ["Casas con jard\xEDn grande", "Familias muy activas", "Personas con tiempo para entrenar"],
    bestForEn: ["Houses with large yard", "Very active families", "People with time to train"],
    desc: "El Border Collie est\xE1 considerado la raza m\xE1s inteligente del mundo. Criado para arrear ovejas en la frontera entre Escocia e Inglaterra, necesita cantidades enormes de ejercicio y estimulaci\xF3n mental. No apto para apartamentos ni para personas con estilo de vida sedentario. Con el entrenamiento correcto, es extraordinario.",
    descEn: "The Border Collie is considered the world's most intelligent breed. Bred to herd sheep on the Scottish-English border, it needs enormous amounts of exercise and mental stimulation. Not suitable for apartments or sedentary lifestyles. With proper training, it is extraordinary.",
    care: "Ejercicio intenso diario (m\xEDnimo 2 horas). Entrenamiento y estimulaci\xF3n mental esenciales. Cepillado frecuente.",
    careEn: "Intensive daily exercise (minimum 2 hours). Training and mental stimulation essential. Frequent brushing.",
    health: "Generalmente saludable. Vigilar epilepsia, displasia de cadera y anomal\xEDa del ojo del Collie.",
    healthEn: "Generally healthy. Watch for epilepsy, hip dysplasia, and Collie eye anomaly.",
    mixes: [
      { name: "Bordoodle", parents: "Border Collie + Poodle", desc: "Altamente inteligente y bajo derramamiento. Para personas muy activas que buscan entrenar extensamente." },
      { name: "Borador", parents: "Border Collie + Labrador", desc: "Amigable y energ\xE9tico. M\xE1s manejable que el Border puro pero igualmente inteligente." }
    ]
  },
  {
    id: "english-bulldog",
    name: "English Bulldog",
    es: "Bulldog Ingl\xE9s",
    emoji: "\u{1F436}",
    photo: "fotos-razas/English Bulldog.webp",
    size: "medium",
    coat: ["short"],
    hypo: false,
    energy: 2,
    grooming: 2,
    shedding: 3,
    trainability: 3,
    barking: 2,
    family: 5,
    kids: 5,
    pets: 4,
    apartment: 4,
    origin: "Inglaterra",
    originEn: "England",
    flag: "\u{1F1EC}\u{1F1E7}",
    weight: "18\u201325 kg",
    height: "31\u201340 cm",
    lifespan: "8\u201310 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Amigable", "Valeroso", "Calmado", "Leal", "Gentil"],
    temperamentEn: ["Friendly", "Courageous", "Calm", "Loyal", "Gentle"],
    bestFor: ["Apartamentos", "Familias", "Adultos mayores"],
    bestForEn: ["Apartments", "Families", "Seniors"],
    desc: "El Bulldog Ingl\xE9s es un \xEDcono de la resistencia y la nobleza. A pesar de su apariencia intimidante, es uno de los perros m\xE1s gentiles y afectuosos que existen. Ama a los ni\xF1os, es tranquilo en interiores y requiere poco ejercicio. Su esperanza de vida m\xE1s corta hace importante elegir criadores responsables.",
    descEn: "The English Bulldog is an icon of resilience and nobility. Despite its intimidating appearance, it is one of the gentlest and most affectionate dogs. Loves children, is calm indoors, and requires little exercise. Its shorter lifespan makes choosing responsible breeders especially important.",
    care: "Limpiar pliegues diariamente. M\xEDnimo ejercicio pero paseos cortos regulares. Muy sensible al calor.",
    careEn: "Clean folds daily. Minimal exercise but regular short walks. Very heat sensitive.",
    health: "Propenso a problemas respiratorios, displasia de cadera y codera, problemas de piel.",
    healthEn: "Prone to breathing problems, hip and elbow dysplasia, skin problems.",
    mixes: [
      { name: "Bullador", parents: "Bulldog Ingl\xE9s + Labrador", desc: "M\xE1s activo y saludable que el Bulldog puro. Temperamento gentil con m\xE1s energ\xEDa." },
      { name: "Beabull", parents: "Bulldog Ingl\xE9s + Beagle", desc: "Curioso y sociable. Combina la curiosidad del Beagle con la calma del Bulldog." }
    ]
  },
  // ── LARGE ──────────────────────────────────────────────
  {
    id: "golden-retriever",
    name: "Golden Retriever",
    es: "Golden Retriever",
    emoji: "\u{1F9AE}",
    photo: "fotos-razas/Golden Retriever.webp",
    size: "large",
    coat: ["long"],
    hypo: false,
    energy: 4,
    grooming: 3,
    shedding: 4,
    trainability: 5,
    barking: 2,
    family: 5,
    kids: 5,
    pets: 5,
    apartment: 2,
    origin: "Escocia",
    originEn: "Scotland",
    flag: "\u{1F3F4}\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}",
    weight: "25\u201334 kg",
    height: "51\u201361 cm",
    lifespan: "10\u201312 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Confiable", "Amistoso", "Inteligente", "Cari\xF1oso", "Paciente"],
    temperamentEn: ["Reliable", "Friendly", "Intelligent", "Affectionate", "Patient"],
    bestFor: ["Familias con ni\xF1os", "Apoyo emocional", "Personas activas", "Casas con patio"],
    bestForEn: ["Families with kids", "Emotional support", "Active people", "Houses with yard"],
    desc: "El Golden Retriever es uno de los perros m\xE1s amados del mundo por su temperamento excepcional. Criado originalmente en Escocia como perro de caza, hoy brilla como perro de terapia, asistencia y compa\xF1\xEDa familiar. Es infinitamente paciente con los ni\xF1os, f\xE1cil de entrenar y siempre alegre. Su sonrisa es inconfundible.",
    descEn: "The Golden Retriever is one of the world's most beloved dogs for its exceptional temperament. Originally bred in Scotland as a hunting dog, today it excels as a therapy, assistance, and family companion dog. Infinitely patient with children, easy to train, and always joyful. Its smile is unmistakable.",
    care: "Cepillado 2\u20133 veces por semana. Ejercicio diario moderado-alto. Vigilar peso y alimentaci\xF3n.",
    careEn: "Brush 2\u20133 times weekly. Moderate-high daily exercise. Monitor weight and diet.",
    health: "Propenso a displasia de cadera, cataratas y c\xE1ncer. Comprar de criadores con pruebas gen\xE9ticas.",
    healthEn: "Prone to hip dysplasia, cataracts, and cancer. Buy from breeders with genetic testing.",
    mixes: [
      { name: "Goldendoodle", parents: "Golden Retriever + Poodle", desc: "Extremadamente popular. Bajo derramamiento, muy inteligente y con el car\xE1cter gentil del Golden." },
      { name: "Goldador", parents: "Golden Retriever + Labrador", desc: "El perro de compa\xF1\xEDa definitivo. Combina lo mejor de dos razas excepcionales." },
      { name: "Golden Husky (Goberian)", parents: "Golden Retriever + Husky", desc: "Impresionante combinaci\xF3n de apariencia. Activo y leal, necesita mucho ejercicio." }
    ]
  },
  {
    id: "labrador-retriever",
    name: "Labrador Retriever",
    es: "Labrador Retriever",
    emoji: "\u{1F9AE}",
    photo: "fotos-razas/Labrador Retriever.webp",
    size: "large",
    coat: ["short"],
    hypo: false,
    energy: 4,
    grooming: 2,
    shedding: 4,
    trainability: 5,
    barking: 2,
    family: 5,
    kids: 5,
    pets: 5,
    apartment: 2,
    origin: "Canad\xE1 / Inglaterra",
    originEn: "Canada / England",
    flag: "\u{1F1E8}\u{1F1E6}",
    weight: "25\u201336 kg",
    height: "54\u201362 cm",
    lifespan: "10\u201312 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Amistoso", "Activo", "Amable", "Confiable", "Adaptable"],
    temperamentEn: ["Friendly", "Active", "Kind", "Trustworthy", "Adaptable"],
    bestFor: ["Familias con ni\xF1os", "Gu\xEDa/asistencia", "Personas muy activas", "Casas con patio"],
    bestForEn: ["Families with kids", "Guide/assistance", "Very active people", "Houses with yard"],
    desc: "El Labrador Retriever ha sido la raza m\xE1s popular de Estados Unidos durante m\xE1s de 30 a\xF1os consecutivos. Es el perro de servicio por excelencia: gu\xEDa para ciegos, asistencia, detecci\xF3n de drogas y terapia. Su car\xE1cter amable, activo y siempre dispuesto a complacer lo hace el compa\xF1ero familiar ideal.",
    descEn: "The Labrador Retriever has been the most popular breed in the United States for over 30 consecutive years. It is the ultimate service dog: guide for the blind, assistance, drug detection, and therapy. Its kind, active, and always eager-to-please character makes it the ideal family companion.",
    care: "Ejercicio intenso diario. Cepillado frecuente en \xE9poca de muda. Muy propenso a comer en exceso.",
    careEn: "Intense daily exercise. Frequent brushing during shedding season. Very prone to overeating.",
    health: "Vigilar displasia de cadera y codo, obesidad y problemas oculares hereditarios.",
    healthEn: "Watch for hip and elbow dysplasia, obesity, and hereditary eye problems.",
    mixes: [
      { name: "Labradoodle", parents: "Labrador + Poodle", desc: "Popular perro de servicio y familia. Bajo derramamiento, inteligente y de excelente temperamento." },
      { name: "Huskador", parents: "Labrador + Husky Siberiano", desc: "En\xE9rgico y leal. Necesita ejercicio intenso. Hermosa combinaci\xF3n de ambas razas." },
      { name: "Bullador", parents: "Labrador + Bulldog", desc: "M\xE1s tranquilo que el Lab puro. Temperamento equilibrado, ideal para familias." }
    ]
  },
  {
    id: "german-shepherd",
    name: "German Shepherd",
    es: "Pastor Alem\xE1n",
    emoji: "\u{1F415}\u200D\u{1F9BA}",
    photo: "fotos-razas/German Shepherd.webp",
    size: "large",
    coat: ["long", "smooth"],
    hypo: false,
    energy: 4,
    grooming: 3,
    shedding: 5,
    trainability: 5,
    barking: 3,
    family: 5,
    kids: 5,
    pets: 3,
    apartment: 2,
    origin: "Alemania",
    originEn: "Germany",
    flag: "\u{1F1E9}\u{1F1EA}",
    weight: "22\u201340 kg",
    height: "55\u201365 cm",
    lifespan: "9\u201313 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Confiado", "Valiente", "Inteligente", "Leal", "Obediente"],
    temperamentEn: ["Confident", "Courageous", "Intelligent", "Loyal", "Obedient"],
    bestFor: ["Familias activas", "Personas con experiencia", "Casas con patio", "Seguridad"],
    bestForEn: ["Active families", "Experienced owners", "Houses with yard", "Security"],
    desc: "El Pastor Alem\xE1n es una de las razas m\xE1s vers\xE1tiles e inteligentes del mundo. Usado en polic\xEDa, ej\xE9rcito, b\xFAsqueda y rescate, y como perro de servicio. Es extremadamente leal a su familia y excelente guardi\xE1n. Necesita socializaci\xF3n temprana y un due\xF1o con experiencia que establezca liderazgo claro.",
    descEn: "The German Shepherd is one of the world's most versatile and intelligent breeds. Used in police, military, search and rescue, and as a service dog. Extremely loyal to its family and an excellent guardian. Needs early socialization and an experienced owner who establishes clear leadership.",
    care: "Ejercicio intenso diario. Cepillado frecuente \u2014 muda abundante dos veces al a\xF1o. Entrenamiento temprano crucial.",
    careEn: "Intense daily exercise. Frequent brushing \u2014 heavy shedding twice a year. Early training crucial.",
    health: "Propenso a displasia de cadera y codo. Buscar l\xEDneas de criadores con certificaciones de salud.",
    healthEn: "Prone to hip and elbow dysplasia. Seek breeders with health certifications.",
    mixes: [
      { name: "Sheprador", parents: "German Shepherd + Labrador", desc: "Leal y amigable. Combina la inteligencia del Pastor con la sociabilidad del Labrador." },
      { name: "Gerberian Shepsky", parents: "German Shepherd + Husky", desc: "Impresionante y en\xE9rgico. Para personas muy activas con experiencia canina." }
    ]
  },
  {
    id: "siberian-husky",
    name: "Siberian Husky",
    es: "Husky Siberiano",
    emoji: "\u{1F43A}",
    photo: "fotos-razas/Siberian Husky.webp",
    size: "large",
    coat: ["long"],
    hypo: false,
    energy: 5,
    grooming: 3,
    shedding: 5,
    trainability: 3,
    barking: 2,
    family: 4,
    kids: 4,
    pets: 3,
    apartment: 1,
    origin: "Siberia (Rusia)",
    originEn: "Siberia (Russia)",
    flag: "\u{1F1F7}\u{1F1FA}",
    weight: "16\u201327 kg",
    height: "51\u201360 cm",
    lifespan: "12\u201314 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Extrovertido", "Energ\xE9tico", "Independiente", "Amistoso", "Leal"],
    temperamentEn: ["Outgoing", "Energetic", "Independent", "Friendly", "Loyal"],
    bestFor: ["Personas muy activas", "Climas fr\xEDos", "Casas con jard\xEDn grande"],
    bestForEn: ["Very active people", "Cold climates", "Houses with large yard"],
    desc: "El Husky Siberiano fue criado por el pueblo Chukchi de Siberia para tirar trineos durante siglos. Sus ojos azules o multicolores y su denso pelaje son ic\xF3nicos. Es un perro de manada que necesita compa\xF1\xEDa constante y ejercicio intenso. Muy independiente \u2014 requiere due\xF1os con experiencia y mucho tiempo.",
    descEn: "The Siberian Husky was bred by the Chukchi people of Siberia to pull sleds for centuries. Its blue or multicolored eyes and dense coat are iconic. It is a pack dog that needs constant companionship and intense exercise. Very independent \u2014 requires experienced owners with lots of time.",
    care: "Ejercicio intenso diario (m\xEDnimo 2 horas). Cepillado intenso en \xE9pocas de muda. Nunca dejar suelto sin cercado.",
    careEn: "Intense daily exercise (minimum 2 hours). Heavy brushing during shedding seasons. Never leave unleashed without fencing.",
    health: "Generalmente saludable. Vigilar displasia de cadera, cataratas hereditarias y problemas de tiroides.",
    healthEn: "Generally healthy. Watch for hip dysplasia, hereditary cataracts, and thyroid issues.",
    mixes: [
      { name: "Pomsky", parents: "Pomeranian + Husky Siberiano", desc: "Tama\xF1o manejable con la apariencia del Husky. Alta demanda. Requiere ejercicio regular." },
      { name: "Huskador", parents: "Husky + Labrador", desc: "M\xE1s amigable y manejable que el Husky puro. En\xE9rgico y leal." },
      { name: "Gerberian Shepsky", parents: "Husky + Pastor Alem\xE1n", desc: "Inteligente y en\xE9rgico. Para personas muy activas con experiencia." }
    ]
  },
  {
    id: "standard-poodle",
    name: "Standard Poodle",
    es: "Caniche Est\xE1ndar",
    emoji: "\u{1F429}",
    photo: "fotos-razas/Standard Poodle.webp",
    size: "large",
    coat: ["curly"],
    hypo: true,
    energy: 4,
    grooming: 5,
    shedding: 1,
    trainability: 5,
    barking: 2,
    family: 5,
    kids: 5,
    pets: 5,
    apartment: 3,
    origin: "Francia / Alemania",
    originEn: "France / Germany",
    flag: "\u{1F1EB}\u{1F1F7}",
    weight: "20\u201332 kg",
    height: "45\u201370 cm",
    lifespan: "12\u201315 a\xF1os",
    akc: true,
    fci: true,
    temperament: ["Activo", "Instintivo", "Adaptable", "Inteligente", "Elegante"],
    temperamentEn: ["Active", "Instinctual", "Adaptable", "Intelligent", "Elegant"],
    bestFor: ["Personas con alergias", "Familias activas", "Deporte canino", "Apoyo emocional"],
    bestForEn: ["People with allergies", "Active families", "Dog sports", "Emotional support"],
    desc: "El Caniche Est\xE1ndar es el perro m\xE1s inteligente del mundo seg\xFAn muchos expertos, superado solo por el Border Collie. Hipoalerg\xE9nico con muy poco derramamiento. Es atl\xE9tico, elegante y excepcionalmente vers\xE1til. El padre de muchas de las razas de dise\xF1o m\xE1s populares (Goldendoodle, Labradoodle, Cavapoo, etc.).",
    descEn: "The Standard Poodle is considered the world's most intelligent dog by many experts, only surpassed by the Border Collie. Hypoallergenic with very little shedding. Athletic, elegant, and exceptionally versatile. The parent of many of the most popular designer breeds (Goldendoodle, Labradoodle, Cavapoo, etc.).",
    care: "Grooming profesional cada 6\u20138 semanas. Cepillado regular para evitar nudos. Ejercicio diario moderado-alto.",
    careEn: "Professional grooming every 6\u20138 weeks. Regular brushing to prevent matting. Moderate-high daily exercise.",
    health: "Generalmente saludable. Vigilar displasia de cadera, problemas oculares hereditarios y dilataci\xF3n g\xE1strica.",
    healthEn: "Generally healthy. Watch for hip dysplasia, hereditary eye problems, and gastric dilation.",
    mixes: [
      { name: "Goldendoodle", parents: "Golden Retriever + Standard Poodle", desc: "La mezcla m\xE1s popular. Bajo derramamiento, inteligente y de car\xE1cter excepcional." },
      { name: "Labradoodle", parents: "Labrador + Standard Poodle", desc: "Origen como perro de servicio hipoalerg\xE9nico. Inteligente y de excelente temperamento." },
      { name: "Bernedoodle", parents: "Bernese Mountain Dog + Poodle", desc: "Leal y gentil. Combina el pelaje del Bernese con el bajo derramamiento del Poodle." }
    ]
  }
];
const DESIGNER_BREEDS = [
  {
    id: "goldendoodle",
    name: "Goldendoodle",
    parents: "Golden Retriever + Standard Poodle",
    emoji: "\u{1F429}",
    photo: "fotos-razas/Goldendoodle.webp",
    size: "medium-large",
    coat: ["curly", "wavy"],
    hypo: true,
    energy: 4,
    desc: "La mezcla de dise\xF1o m\xE1s popular en EE. UU. Hereda la inteligencia y el bajo derramamiento del Poodle con el car\xE1cter gentil e incondicional del Golden Retriever. Ideal para familias, personas con alergias y como perro de apoyo emocional. Viene en varios tama\xF1os seg\xFAn el tipo de Poodle.",
    descEn: "The most popular designer mix in the U.S. Inherits the intelligence and low shedding of the Poodle with the gentle, unconditional character of the Golden Retriever. Ideal for families, allergy sufferers, and as an emotional support dog. Available in various sizes depending on the Poodle type."
  },
  {
    id: "labradoodle",
    name: "Labradoodle",
    parents: "Labrador Retriever + Poodle",
    emoji: "\u{1F429}",
    photo: "fotos-razas/Labradoodle.webp",
    size: "medium-large",
    coat: ["curly", "wavy"],
    hypo: true,
    energy: 4,
    desc: "Originalmente creado en Australia como perro gu\xEDa hipoalerg\xE9nico. Combina la obediencia y sociabilidad del Labrador con el bajo derramamiento del Poodle. Excelente perro de servicio y compa\xF1\xEDa familiar.",
    descEn: "Originally created in Australia as a hypoallergenic guide dog. Combines the obedience and sociability of the Labrador with the low shedding of the Poodle. Excellent service dog and family companion."
  },
  {
    id: "cavapoo",
    name: "Cavapoo",
    parents: "Cavalier King Charles + Miniature Poodle",
    emoji: "\u{1F436}",
    photo: "fotos-razas/Cavapoo.webp",
    size: "small",
    coat: ["curly", "wavy"],
    hypo: true,
    energy: 3,
    desc: "Dulce, gentil y de bajo mantenimiento. Hereda el temperamento cari\xF1oso del Cavalier con el bajo derramamiento del Poodle. Ideal para apoyo emocional, adultos mayores y apartamentos.",
    descEn: "Sweet, gentle, and low maintenance. Inherits the affectionate temperament of the Cavalier with the low shedding of the Poodle. Ideal for emotional support, seniors, and apartments."
  },
  {
    id: "maltipoo",
    name: "Maltipoo",
    parents: "Maltese + Miniature Poodle",
    emoji: "\u{1F429}",
    photo: "fotos-razas/Maltipoo.webp",
    size: "small",
    coat: ["curly", "wavy"],
    hypo: true,
    energy: 3,
    desc: "Peque\xF1o, adorable e hipoalerg\xE9nico. Muy popular para personas con alergias. Cari\xF1oso y sociable, se adapta perfectamente a apartamentos y hogares tranquilos.",
    descEn: "Small, adorable, and hypoallergenic. Very popular for people with allergies. Affectionate and sociable, perfectly adapted to apartments and quiet homes."
  },
  {
    id: "shorkie",
    name: "Shorkie",
    parents: "Shih Tzu + Yorkshire Terrier",
    emoji: "\u{1F436}",
    size: "small",
    coat: ["long", "silky"],
    hypo: false,
    energy: 3,
    desc: "Pelaje sedoso y car\xE1cter juguet\xF3n. Combina la dulzura del Shih Tzu con la energ\xEDa del Yorkie. Poco derramante, ideal para apartamentos.",
    descEn: "Silky coat and playful character. Combines the sweetness of the Shih Tzu with the energy of the Yorkie. Low shedding, ideal for apartments."
  },
  {
    id: "morkie",
    name: "Morkie",
    parents: "Maltese + Yorkshire Terrier",
    emoji: "\u{1F436}",
    size: "small",
    coat: ["long", "silky"],
    hypo: false,
    energy: 3,
    desc: "Pelaje largo y suave, temperamento cari\xF1oso y adaptable. Muy sociable. Ideal para adultos y familias sin ni\xF1os muy peque\xF1os.",
    descEn: "Long, soft coat, affectionate and adaptable temperament. Very sociable. Ideal for adults and families without very young children."
  },
  {
    id: "pomsky",
    name: "Pomsky",
    parents: "Pomeranian + Siberian Husky",
    emoji: "\u{1F43A}",
    photo: "fotos-razas/Pomsky.webp",
    size: "small-medium",
    coat: ["long"],
    hypo: false,
    energy: 4,
    desc: "Alta demanda por su apariencia de Husky en miniatura. En\xE9rgico, inteligente y de fuerte personalidad. Requiere ejercicio regular y socializaci\xF3n temprana.",
    descEn: "High demand for its miniature Husky appearance. Energetic, intelligent, and strong-willed. Requires regular exercise and early socialization."
  },
  {
    id: "frenchton",
    name: "Frenchton",
    parents: "French Bulldog + Boston Terrier",
    emoji: "\u{1F436}",
    size: "small",
    coat: ["short"],
    hypo: false,
    energy: 3,
    desc: "M\xE1s activo y saludable que el French Bulldog puro. Mejor tolerancia al calor. Temperamento juguet\xF3n y muy sociable. Excelente para apartamentos y familias.",
    descEn: "More active and healthier than a pure French Bulldog. Better heat tolerance. Playful temperament and very sociable. Excellent for apartments and families."
  },
  {
    id: "schnoodle",
    name: "Schnoodle",
    parents: "Schnauzer + Poodle",
    emoji: "\u{1F429}",
    size: "small-medium",
    coat: ["curly", "wiry"],
    hypo: true,
    energy: 3,
    desc: "Inteligente, sin derramamiento y con car\xE1cter equilibrado. Hereda la lealtad del Schnauzer y la inteligencia del Poodle. Excelente perro de familia.",
    descEn: "Intelligent, non-shedding, and balanced character. Inherits the loyalty of the Schnauzer and the intelligence of the Poodle. Excellent family dog."
  },
  {
    id: "shichon",
    name: "Shichon (Teddy Bear)",
    parents: "Shih Tzu + Bichon Fris\xE9",
    emoji: "\u{1F9F8}",
    size: "small",
    coat: ["curly", "soft"],
    hypo: true,
    energy: 2,
    desc: 'Conocido como "Teddy Bear" por su apariencia adorable. Gentil, sociable y de bajo mantenimiento. Casi sin derramamiento. Ideal para personas mayores y familias tranquilas.',
    descEn: 'Known as "Teddy Bear" for its adorable appearance. Gentle, sociable, and low maintenance. Almost no shedding. Ideal for seniors and calm families.'
  }
];
const MESTIZO_INFO = {
  title: ["Perros Mestizos", "Mixed Breed Dogs"],
  desc: [
    'Los perros mestizos son una combinaci\xF3n \xFAnica de varias razas. Suelen tener excelente salud gracias a la "heterosis" (vigor h\xEDbrido), temperamentos equilibrados y personalidades \xFAnicas. Cada perro mestizo es irrepetible. La mayor\xEDa se encuentran en refugios locales esperando un hogar amoroso.',
    'Mixed breed dogs are a unique combination of several breeds. They often have excellent health thanks to "heterosis" (hybrid vigor), balanced temperaments, and unique personalities. Each mixed breed dog is one of a kind. Most are found in local shelters waiting for a loving home.'
  ],
  link: "/adopciones"
};
const ALL_SIZES = ["small", "medium", "large"];
const ALL_COATS = ["short", "long", "curly", "smooth", "wiry", "hairless"];
Object.assign(window, { DOG_BREEDS, DESIGNER_BREEDS, MESTIZO_INFO, ALL_SIZES, ALL_COATS });

})();
