// breed-trivia.js — Datos curiosos, dueños famosos y curiosidades por raza.
// Se fusiona por id en DOG_BREEDS / CAT_BREEDS (cargado después de breed-data / cat-breed-data).
(function () {
  var DOG_TRIVIA = {
    'french-bulldog': {
      funFacts: ['No pueden nadar bien: su cuerpo pesado y cara chata se lo impiden.', 'Casi siempre nacen por cesárea por su cabeza grande.', 'Son una de las razas que más "hablan" con gruñidos y bostezos graciosos.'],
      funFactsEn: ['They can\'t really swim: their heavy body and flat face make it hard.', 'They are almost always born by C-section due to their large heads.', 'One of the most "talkative" breeds, with funny grunts and yawns.'],
      famous: ['Lady Gaga', 'Dwayne "The Rock" Johnson', 'Hugh Jackman', 'Reese Witherspoon'],
      curiosity: 'Fue el perro de moda entre las costureras del Londres victoriano antes de conquistar París, donde recibió su nombre.',
      curiosityEn: 'It was the favorite of Victorian London lacemakers before conquering Paris, where it got its name.',
    },
    'golden-retriever': {
      funFacts: ['Tienen "boca blanda": pueden cargar un huevo sin romperlo.', 'Fueron criados en Escocia para recuperar presas en agua y tierra.', 'Su cola no para de moverse: es de las razas más expresivas.'],
      funFactsEn: ['They have a "soft mouth": they can carry an egg without breaking it.', 'Bred in Scotland to retrieve game on water and land.', 'Their tail never stops wagging — one of the most expressive breeds.'],
      famous: ['Oprah Winfrey', 'Adam Levine', 'Jimmy Fallon'],
      curiosity: 'Son de los mejores perros de terapia y asistencia del mundo gracias a su paciencia infinita.',
      curiosityEn: 'They are among the best therapy and service dogs in the world thanks to their endless patience.',
    },
    'labrador-retriever': {
      funFacts: ['Son la raza #1 más popular de EE. UU. por décadas.', 'Tienen patas semipalmeadas: nadadores natos.', 'Su nariz puede detectar olores que ningún aparato humano detecta.'],
      funFactsEn: ['They\'ve been the #1 most popular breed in the U.S. for decades.', 'They have semi-webbed feet — natural swimmers.', 'Their nose can detect scents no human device can.'],
      famous: ['Príncipe Guillermo y Kate', 'Bill Clinton (su Lab "Buddy")', 'Anne Hathaway'],
      famousEn: ['Prince William & Kate', 'Bill Clinton (his Lab "Buddy")', 'Anne Hathaway'],
      curiosity: 'Vienen en tres colores (negro, chocolate y dorado) y pueden nacer los tres en la misma camada.',
      curiosityEn: 'They come in three colors (black, chocolate, yellow) and all three can appear in one litter.',
    },
    'german-shepherd': {
      funFacts: ['Es el perro policía y militar más usado del mundo.', 'Aprende órdenes nuevas en menos de 5 repeticiones.', 'La estrella de cine Rin Tin Tin era un Pastor Alemán rescatado en la I Guerra Mundial.'],
      funFactsEn: ['It\'s the most widely used police and military dog in the world.', 'Learns new commands in fewer than 5 repetitions.', 'Movie star Rin Tin Tin was a German Shepherd rescued in WWI.'],
      famous: ['Jake Gyllenhaal', 'Claudia Schiffer', 'Rin Tin Tin'],
      curiosity: 'Fue creado por un solo hombre, el capitán Max von Stephanitz, con la idea del "perro de utilidad perfecto".',
      curiosityEn: 'It was created by one man, Captain Max von Stephanitz, with the idea of the "perfect utility dog".',
    },
    'standard-poodle': {
      funFacts: ['Está entre las 2 razas más inteligentes del mundo.', 'El corte "pompón" nació para protegerle las articulaciones al nadar.', 'Casi no suelta pelo: ideal para alérgicos.'],
      funFactsEn: ['Ranked among the 2 smartest breeds in the world.', 'The "pom-pom" cut was created to protect its joints while swimming.', 'Barely sheds — great for allergy sufferers.'],
      famous: ['Rihanna', 'Walt Disney', 'Jackie Kennedy'],
      curiosity: 'Aunque hoy parece elegante, fue criado en Alemania como perro cazador de patos en el agua.',
      curiosityEn: 'Though it looks elegant today, it was bred in Germany as a water duck-hunting dog.',
    },
    'beagle': {
      funFacts: ['Tiene unos 220 millones de receptores de olor (los humanos, 5 millones).', 'Snoopy, el personaje más famoso del cómic, es un Beagle.', 'Su "aullido" especial se llama "baying".'],
      funFactsEn: ['Has around 220 million scent receptors (humans have 5 million).', 'Snoopy, the famous comic character, is a Beagle.', 'Their special howl is called "baying".'],
      famous: ['Snoopy', 'Lyndon B. Johnson', 'Barry Manilow'],
      curiosity: 'Su olfato es tan bueno que trabajan en aeropuertos detectando comida y plantas prohibidas.',
      curiosityEn: 'Their nose is so good they work in airports detecting banned food and plants.',
    },
    'chihuahua': {
      funFacts: ['Es la raza de perro más pequeña del mundo.', 'Nacen con una "mollera" blanda en el cráneo, como los bebés.', 'Viven hasta 16–18 años, de las más longevas.'],
      funFactsEn: ['The smallest dog breed in the world.', 'They\'re born with a soft spot on the skull, like babies.', 'They live 16–18 years, among the longest-lived.'],
      famous: ['Paris Hilton', 'Marilyn Monroe', 'Madonna'],
      curiosity: 'Lleva el nombre del estado mexicano de Chihuahua, donde fue redescubierto en el siglo XIX.',
      curiosityEn: 'Named after the Mexican state of Chihuahua, where it was rediscovered in the 1800s.',
    },
    'pomeranian': {
      funFacts: ['Desciende de grandes perros de trineo, ¡aunque no lo parezca!', 'La reina Victoria los puso de moda al criar ejemplares cada vez más pequeños.', 'Dos Pomerania sobrevivieron al hundimiento del Titanic.'],
      funFactsEn: ['Descends from large sled dogs — hard to believe!', 'Queen Victoria made them popular by breeding ever-smaller ones.', 'Two Pomeranians survived the sinking of the Titanic.'],
      famous: ['Reina Victoria', 'Boo "el perro más lindo del mundo"', 'Nicole Richie'],
      famousEn: ['Queen Victoria', 'Boo "the world\'s cutest dog"', 'Nicole Richie'],
      curiosity: 'Mozart y Miguel Ángel también tuvieron Pomeranias como compañeros.',
      curiosityEn: 'Mozart and Michelangelo also kept Pomeranians as companions.',
    },
    'yorkshire-terrier': {
      funFacts: ['Su pelo tiene textura de cabello humano y casi no suelta.', 'Nació para cazar ratas en fábricas y minas de Inglaterra.', 'Smoky, una Yorkie, fue heroína de guerra en la II Guerra Mundial.'],
      funFactsEn: ['Their coat has a human-hair texture and barely sheds.', 'Bred to hunt rats in England\'s mills and mines.', 'Smoky, a Yorkie, was a WWII war hero.'],
      famous: ['Audrey Hepburn', 'Missy Elliott', 'Whitney Houston'],
      curiosity: 'Pasó de perro obrero de clase trabajadora a símbolo de lujo victoriano en pocas décadas.',
      curiosityEn: 'It went from working-class ratter to Victorian luxury symbol in just a few decades.',
    },
    'dachshund': {
      funFacts: ['"Dachshund" significa "perro tejón": fue criado para cazarlos bajo tierra.', 'Su cuerpo largo le dio el apodo de "perro salchicha".', 'Fue la primera mascota oficial de unos Juegos Olímpicos (Múnich 1972, "Waldi").'],
      funFactsEn: ['"Dachshund" means "badger dog": bred to hunt them underground.', 'Its long body earned it the "sausage dog" nickname.', 'It was the first official Olympic mascot (Munich 1972, "Waldi").'],
      famous: ['Pablo Picasso (su "Lump")', 'Andy Warhol', 'David Hockney'],
      famousEn: ['Pablo Picasso (his "Lump")', 'Andy Warhol', 'David Hockney'],
      curiosity: 'Picasso dibujó a su Dachshund "Lump" en varias de sus obras.',
      curiosityEn: 'Picasso drew his Dachshund "Lump" in several of his works.',
    },
    'siberian-husky': {
      funFacts: ['Pueden correr más de 150 km en un día tirando de un trineo.', 'Sus ojos pueden ser de dos colores distintos (heterocromía).', 'No ladran casi nada, pero "cantan" y aúllan mucho.'],
      funFactsEn: ['They can run over 150 km in a day pulling a sled.', 'Their eyes can be two different colors (heterochromia).', 'They barely bark, but they "sing" and howl a lot.'],
      famous: ['Balto y Togo (héroes de Alaska)', 'Ben Stiller', 'Rita Ora'],
      famousEn: ['Balto and Togo (Alaskan heroes)', 'Ben Stiller', 'Rita Ora'],
      curiosity: 'En 1925, equipos de Huskies llevaron medicina a través de Alaska para frenar una epidemia: hoy se recuerda en la carrera Iditarod.',
      curiosityEn: 'In 1925, Husky teams relayed medicine across Alaska to stop an epidemic — remembered today in the Iditarod race.',
    },
    'cavalier-kcs': {
      funFacts: ['Lleva el nombre del rey Carlos II de Inglaterra, que adoraba la raza.', 'Es de los perros falderos más cariñosos que existen.', 'Adora seguir a su humano de cuarto en cuarto.'],
      funFactsEn: ['Named after King Charles II of England, who adored the breed.', 'One of the most affectionate lap dogs there is.', 'Loves following its human from room to room.'],
      famous: ['Frank Sinatra', 'Ronald Reagan', 'Rey Carlos II'],
      famousEn: ['Frank Sinatra', 'Ronald Reagan', 'King Charles II'],
      curiosity: 'Se decía que estos perros se permitían en cualquier edificio público de Inglaterra, ¡incluido el Parlamento!',
      curiosityEn: 'These dogs were reportedly allowed in any public building in England — even Parliament!',
    },
    'pug': {
      funFacts: ['Su nombre en latín, "multum in parvo", significa "mucho en poco espacio".', 'Un grupo de Pugs se llama "a grumble" (un gruñido).', 'Fueron mascotas de los emperadores chinos durante siglos.'],
      funFactsEn: ['Their motto in Latin, "multum in parvo", means "a lot in a little".', 'A group of Pugs is called "a grumble".', 'They were companions to Chinese emperors for centuries.'],
      famous: ['Reina Victoria', 'Gerard Butler', 'Jessica Alba'],
      famousEn: ['Queen Victoria', 'Gerard Butler', 'Jessica Alba'],
      curiosity: 'Un Pug llamado Pompey salvó la vida del príncipe Guillermo de Orange al alertarlo de un ataque enemigo.',
      curiosityEn: 'A Pug named Pompey saved Prince William of Orange by alerting him to an enemy attack.',
    },
    'shiba-inu': {
      funFacts: ['Es la raza detrás del famoso meme "Doge" y de la cripto Dogecoin.', 'Se limpian solos como los gatos.', 'Hacen el "Shiba scream", un grito agudo cuando se emocionan o enojan.'],
      funFactsEn: ['It\'s the breed behind the famous "Doge" meme and Dogecoin.', 'They groom themselves like cats.', 'They do the "Shiba scream", a high-pitched yell when excited or upset.'],
      famous: ['Kabosu (la cara del meme Doge)', 'Crusoe', 'Bunko'],
      famousEn: ['Kabosu (the face of the Doge meme)', 'Crusoe', 'Bunko'],
      curiosity: 'Es la raza más antigua y popular de Japón; casi se extingue tras la II Guerra Mundial.',
      curiosityEn: 'It\'s Japan\'s oldest and most popular breed; it nearly went extinct after WWII.',
    },
    'rottweiler': {
      funFacts: ['Acompañaban a las legiones romanas arreando ganado por los Alpes.', 'Su nombre viene de Rottweil, una ciudad medieval alemana.', 'Son de los perros más fuertes: protectores y leales con su familia.'],
      funFactsEn: ['They accompanied Roman legions herding cattle across the Alps.', 'Their name comes from Rottweil, a medieval German town.', 'Among the strongest dogs — protective and loyal to family.'],
      famous: ['Will Smith', 'Bruno Mars', 'Leonardo DiCaprio'],
      curiosity: 'Fueron de los primeros perros guía y hoy trabajan en rescate y como perros policía.',
      curiosityEn: 'They were among the first guide dogs and today work in search-and-rescue and police K9 units.',
    },
    'boston-terrier': {
      funFacts: ['Lo apodan "el caballero americano" por su esmoquin blanco y negro.', 'Es una de las pocas razas 100% originarias de EE. UU.', 'Es la mascota oficial del estado de Massachusetts.'],
      funFactsEn: ['Nicknamed "the American Gentleman" for its black-and-white tuxedo.', 'One of the few breeds 100% originated in the U.S.', 'It\'s the official state dog of Massachusetts.'],
      famous: ['Helen Keller (su Boston "Phiz")', 'Rose McGowan', 'Robin Williams'],
      famousEn: ['Helen Keller (her Boston "Phiz")', 'Rose McGowan', 'Robin Williams'],
      curiosity: 'Helen Keller recibió uno de los primeros Akita del mundo, pero su perro del día a día fue un Boston Terrier.',
      curiosityEn: 'Helen Keller received one of the first Akitas in the world, but her everyday dog was a Boston Terrier.',
    },
    'maltese': {
      funFacts: ['Su pelo es blanco puro y sedoso, sin subpelo: casi no suelta.', 'Fue perro de compañía de la nobleza griega y romana hace 2000 años.'],
      funFactsEn: ['Their coat is pure white and silky, with no undercoat — barely sheds.', 'It was a companion to Greek and Roman nobility 2,000 years ago.'],
      famous: ['Elizabeth Taylor', 'Halle Berry'],
      curiosity: 'Aparece pintado en ánforas griegas antiguas: es de los perros falderos más antiguos del mundo.',
      curiosityEn: 'It appears painted on ancient Greek amphorae — one of the oldest lap dogs in the world.',
    },
    'shih-tzu': {
      funFacts: ['Su nombre significa "perro león" en chino.', 'Vivió en los palacios imperiales chinos como compañero de la realeza.'],
      funFactsEn: ['Its name means "lion dog" in Chinese.', 'It lived in Chinese imperial palaces as a royal companion.'],
      famous: ['Emperatriz Cixí', 'Miley Cyrus', 'Nicole Richie'],
      famousEn: ['Empress Cixi', 'Miley Cyrus', 'Nicole Richie'],
      curiosity: 'Casi se extingue; todos los Shih Tzu de hoy descienden de apenas 14 perros.',
      curiosityEn: 'It nearly went extinct; every Shih Tzu today descends from just 14 dogs.',
    },
    'miniature-schnauzer': {
      funFacts: ['Sus cejas y barba pobladas son su sello inconfundible.', 'Nació como cazador de ratas en granjas alemanas.'],
      funFactsEn: ['Its bushy eyebrows and beard are its unmistakable trademark.', 'It was bred as a rat-catcher on German farms.'],
      curiosity: 'Es el único Schnauzer que el AKC clasifica en el grupo de los terrier.',
      curiosityEn: 'It\'s the only Schnauzer the AKC places in the Terrier group.',
    },
    'cocker-spaniel': {
      funFacts: ['Sus largas orejas fueron criadas para arrastrar y levantar olores del suelo.', '"Lady", de La Dama y el Vagabundo, es una Cocker Spaniel.'],
      funFactsEn: ['Its long ears were bred to stir up and lift scents from the ground.', '"Lady" from Lady and the Tramp is a Cocker Spaniel.'],
      famous: ['Lady (Disney)', 'Oprah Winfrey', 'Elizabeth Barrett Browning'],
      curiosity: 'El cocker "Flush" de la poeta E. B. Browning inspiró un libro de Virginia Woolf.',
      curiosityEn: 'Poet E. B. Browning\'s cocker "Flush" inspired a book by Virginia Woolf.',
    },
    'border-collie': {
      funFacts: ['Es considerado el perro más inteligente del mundo.', 'Usa una mirada fija e hipnótica ("the eye") para arrear ovejas.'],
      funFactsEn: ['Considered the most intelligent dog breed in the world.', 'Uses a fixed, hypnotic stare ("the eye") to herd sheep.'],
      famous: ['Chaser (sabía 1000+ palabras)', 'Tilda Swinton'],
      famousEn: ['Chaser (knew 1,000+ words)', 'Tilda Swinton'],
      curiosity: 'Una Border Collie llamada Chaser aprendió los nombres de más de 1000 juguetes.',
      curiosityEn: 'A Border Collie named Chaser learned the names of over 1,000 toys.',
    },
    'english-bulldog': {
      funFacts: ['Es un símbolo nacional de Gran Bretaña y de la tenacidad.', 'A pesar de su cara seria, es de los perros más cariñosos y tranquilos.'],
      funFactsEn: ['It\'s a national symbol of Britain and of tenacity.', 'Despite its grumpy face, it\'s one of the most affectionate, calm dogs.'],
      famous: ['Adam Sandler', 'David Beckham', 'Pink'],
      curiosity: 'Es la mascota de docenas de universidades y equipos, como Yale ("Handsome Dan").',
      curiosityEn: 'It\'s the mascot of dozens of universities and teams, like Yale ("Handsome Dan").',
    },
    'goldendoodle': {
      funFacts: ['Mezcla de Golden Retriever y Poodle: suele soltar muy poco pelo.', 'Hereda la inteligencia del Poodle y la dulzura del Golden.'],
      funFactsEn: ['A Golden Retriever–Poodle mix that usually sheds very little.', 'Inherits the Poodle\'s smarts and the Golden\'s sweetness.'],
      curiosity: 'Surgió en los años 90 buscando un perro grande, amistoso y apto para alérgicos.',
      curiosityEn: 'It emerged in the 1990s as a large, friendly, allergy-friendlier dog.',
    },
    'labradoodle': {
      funFacts: ['Cruce de Labrador y Poodle, pensado como perro guía hipoalergénico.', 'Activo, sociable y de pelaje rizado o lanudo.'],
      funFactsEn: ['A Labrador–Poodle cross conceived as a hypoallergenic guide dog.', 'Active, social, with a curly or fleece coat.'],
      curiosity: 'Fue creado en 1989 en Australia por Wally Conron para una persona ciega alérgica.',
      curiosityEn: 'It was created in 1989 in Australia by Wally Conron for a blind, allergic person.',
    },
    'cavapoo': {
      funFacts: ['Mezcla de Cavalier King Charles y Poodle: pequeño y muy cariñoso.', 'Suele soltar poco pelo y adaptarse genial a apartamentos.'],
      funFactsEn: ['A Cavalier King Charles–Poodle mix: small and very affectionate.', 'Usually low-shedding and great for apartments.'],
      curiosity: 'Es uno de los perros "de diseño" más populares en EE. UU. y Reino Unido.',
      curiosityEn: 'It\'s one of the most popular "designer" dogs in the U.S. and U.K.',
    },
    'maltipoo': {
      funFacts: ['Cruce de Maltés y Poodle: diminuto, esponjoso y juguetón.', 'Suele soltar poco pelo, ideal para alérgicos.'],
      funFactsEn: ['A Maltese–Poodle cross: tiny, fluffy and playful.', 'Usually low-shedding — good for allergy sufferers.'],
      curiosity: 'Es uno de los favoritos como perro faldero de celebridades.',
      curiosityEn: 'It\'s a celebrity lap-dog favorite.',
    },
    'shorkie': {
      funFacts: ['Mezcla de Shih Tzu y Yorkshire Terrier: pequeño y muy apegado.', 'Tiene mucha personalidad en un cuerpo diminuto.'],
      funFactsEn: ['A Shih Tzu–Yorkshire Terrier mix: small and very attached.', 'Big personality in a tiny body.'],
      curiosity: 'Combina el pelaje sedoso del Yorkie con el carácter dulce del Shih Tzu.',
      curiosityEn: 'It blends the Yorkie\'s silky coat with the Shih Tzu\'s sweet nature.',
    },
    'morkie': {
      funFacts: ['Cruce de Maltés y Yorkie: minúsculo, alegre y enérgico.', 'Adora la compañía y no le gusta quedarse solo.'],
      funFactsEn: ['A Maltese–Yorkie cross: tiny, cheerful and energetic.', 'Loves company and dislikes being left alone.'],
      curiosity: 'Es un perro de compañía muy popular en ciudades por su tamaño.',
      curiosityEn: 'A very popular city companion thanks to its size.',
    },
    'pomsky': {
      funFacts: ['Mezcla de Pomerania y Husky: aspecto de husky en tamaño pequeño.', 'Suele tener ojos claros y pelaje espeso.'],
      funFactsEn: ['A Pomeranian–Husky mix: husky looks in a small size.', 'Often has light eyes and a thick coat.'],
      curiosity: 'Casi siempre se cría por inseminación, por la gran diferencia de tamaño entre padres.',
      curiosityEn: 'It\'s almost always bred via insemination due to the big size gap between parents.',
    },
    'frenchton': {
      funFacts: ['Cruce de Bulldog Francés y Boston Terrier.', 'Suele respirar mejor y tolerar más el calor que el Frenchie puro.'],
      funFactsEn: ['A French Bulldog–Boston Terrier cross.', 'Often breathes better and tolerates heat more than a purebred Frenchie.'],
      curiosity: 'Se cría buscando un Frenchie más sano gracias al hocico algo más largo.',
      curiosityEn: 'It\'s bred for a healthier Frenchie thanks to a slightly longer snout.',
    },
    'schnoodle': {
      funFacts: ['Mezcla de Schnauzer y Poodle: inteligente y de bajo desprendimiento de pelo.', 'Muy entrenable y buen perro de familia.'],
      funFactsEn: ['A Schnauzer–Poodle mix: smart and low-shedding.', 'Very trainable and a good family dog.'],
      curiosity: 'Combina la barba del Schnauzer con el pelo rizado del Poodle.',
      curiosityEn: 'It blends the Schnauzer\'s beard with the Poodle\'s curly coat.',
    },
    'shichon': {
      funFacts: ['Cruce de Shih Tzu y Bichón Frisé, apodado "oso de peluche".', 'Suave, cariñoso y de bajo desprendimiento de pelo.'],
      funFactsEn: ['A Shih Tzu–Bichon Frise cross, nicknamed "teddy bear".', 'Soft, affectionate and low-shedding.'],
      curiosity: 'Su cara redonda y peluda le da un aspecto de peluche permanente.',
      curiosityEn: 'Its round, fluffy face gives it a permanent plush-toy look.',
    },
    'affenpinscher': {
      funFacts: ['Su nombre significa "perro mono" en alemán por su carita.', 'Es valiente y gracioso, con aires de payaso.'],
      funFactsEn: ['Its name means "monkey dog" in German because of its face.', 'It\'s brave and funny, with a clownish flair.'],
      famous: ['Banana Joe (ganó Westminster 2013)'],
      famousEn: ['Banana Joe (won Westminster 2013)'],
      curiosity: 'Un Affenpinscher llamado Banana Joe ganó el prestigioso Westminster en 2013.',
      curiosityEn: 'An Affenpinscher named Banana Joe won the prestigious Westminster show in 2013.',
    },
    'bichon-frise': {
      funFacts: ['Su pelaje blanco parece una nube de algodón.', 'Fue artista de circo en Europa por su carácter alegre y listo.'],
      funFactsEn: ['Its white coat looks like a cotton cloud.', 'It was a European circus performer thanks to its cheerful, clever nature.'],
      famous: ['Barbra Streisand'],
      curiosity: 'Barbra Streisand clonó a su Bichón Sammie en dos cachorros.',
      curiosityEn: 'Barbra Streisand cloned her Bichon Sammie into two puppies.',
    },
    'havanese': {
      funFacts: ['Es el único perro nativo de Cuba.', 'Lo apodan "perro velcro" porque te sigue a todas partes.'],
      funFactsEn: ['It\'s the only dog breed native to Cuba.', 'Nicknamed the "Velcro dog" because it follows you everywhere.'],
      famous: ['Charles Dickens (su perro "Tim")', 'Ernest Hemingway'],
      famousEn: ['Charles Dickens (his dog "Tim")', 'Ernest Hemingway'],
      curiosity: 'Es el perro nacional de Cuba y fue mascota de la aristocracia de La Habana.',
      curiosityEn: 'It\'s Cuba\'s national dog and was a pet of Havana\'s aristocracy.',
    },
    'jack-russell': {
      funFacts: ['Tiene una energía casi infinita: necesita mucho ejercicio.', 'Brilla en el cine por lo entrenable que es.'],
      funFactsEn: ['It has almost endless energy and needs lots of exercise.', 'It shines in movies thanks to how trainable it is.'],
      famous: ['Uggie (El Artista)', 'Moose (Eddie en Frasier)', 'Wishbone'],
      curiosity: 'Fue criado por el reverendo John Russell en el siglo XIX para cazar zorros.',
      curiosityEn: 'It was bred by Reverend John Russell in the 1800s for fox hunting.',
    },
    'toy-poodle': {
      funFacts: ['Es la versión más pequeña del Poodle y de las más inteligentes.', 'Su pelo rizado casi no suelta: ideal para alérgicos.'],
      funFactsEn: ['It\'s the smallest Poodle variety and among the smartest.', 'Its curly coat barely sheds — great for allergy sufferers.'],
      curiosity: 'Los Poodle fueron estrellas de los circos europeos durante siglos.',
      curiosityEn: 'Poodles were stars of European circuses for centuries.',
    },
    'australian-shepherd': {
      funFacts: ['¡Sorpresa! Se desarrolló en EE. UU., no en Australia.', 'Sus ojos pueden ser azules, ámbar o de dos colores.'],
      funFactsEn: ['Surprise! It was developed in the U.S., not Australia.', 'Its eyes can be blue, amber, or two different colors.'],
      curiosity: 'Recibió su nombre por los pastores vascos que llegaron vía Australia a EE. UU.',
      curiosityEn: 'It got its name from Basque shepherds who reached the U.S. via Australia.',
    },
    'basset-hound': {
      funFacts: ['Tiene el segundo mejor olfato del mundo, tras el Bloodhound.', 'Sus orejas larguísimas barren los olores del suelo hacia su nariz.'],
      funFactsEn: ['It has the second-best nose in the world, after the Bloodhound.', 'Its very long ears sweep ground scents up toward its nose.'],
      famous: ['Mascota de Hush Puppies', 'Elvis Presley'],
      famousEn: ['Hush Puppies mascot', 'Elvis Presley'],
      curiosity: 'Elvis le cantó "Hound Dog" a un Basset con sombrero de copa en TV en 1956.',
      curiosityEn: 'Elvis sang "Hound Dog" to a top-hatted Basset on TV in 1956.',
    },
    'bull-terrier': {
      funFacts: ['Es el único perro con ojos triangulares.', 'Su cabeza con forma de huevo es inconfundible.'],
      funFactsEn: ['It\'s the only dog with triangular eyes.', 'Its egg-shaped head is unmistakable.'],
      famous: ['Bullseye (perro de Target)', 'Spuds MacKenzie', 'General Patton ("Willie")'],
      curiosity: 'Fue la cara de campañas icónicas como la del perro de la tienda Target.',
      curiosityEn: 'It was the face of iconic campaigns like the Target store dog.',
    },
    'chow-chow': {
      funFacts: ['Tiene la lengua azul-negra, algo único entre los perros.', 'Su melena le da aspecto de pequeño león.'],
      funFactsEn: ['It has a blue-black tongue, unique among dogs.', 'Its mane gives it the look of a little lion.'],
      famous: ['Sigmund Freud', 'Martha Stewart'],
      curiosity: 'Freud tenía una Chow llamada Jofi y creía que ayudaba en sus terapias.',
      curiosityEn: 'Freud had a Chow named Jofi and believed it helped in his therapy sessions.',
    },
    'pembroke-corgi': {
      funFacts: ['Fue la raza favorita de la reina Isabel II por más de 70 años.', 'A pesar de sus patas cortas, es un pastor de ganado ágil.'],
      funFactsEn: ['It was Queen Elizabeth II\'s favorite breed for over 70 years.', 'Despite its short legs, it\'s an agile cattle herder.'],
      famous: ['Reina Isabel II'],
      famousEn: ['Queen Elizabeth II'],
      curiosity: 'Una leyenda galesa dice que las hadas montaban Corgis: sus marcas serían la "silla del hada".',
      curiosityEn: 'A Welsh legend says fairies rode Corgis — their markings are the "fairy saddle".',
    },
    'afghan-hound': {
      funFacts: ['Su pelaje largo y sedoso parece de pasarela de moda.', 'Es un sighthound antiguo que caza por vista, no por olfato.'],
      funFactsEn: ['Its long, silky coat looks straight off a fashion runway.', 'It\'s an ancient sighthound that hunts by sight, not smell.'],
      curiosity: 'El primer perro clonado del mundo, Snuppy (2005), fue un Afghan Hound.',
      curiosityEn: 'The world\'s first cloned dog, Snuppy (2005), was an Afghan Hound.',
    },
    'airedale-terrier': {
      funFacts: ['Es el terrier más grande: lo apodan "el rey de los terrier".', 'Sirvió como mensajero y centinela en la Primera Guerra Mundial.'],
      funFactsEn: ['It\'s the largest terrier — nicknamed "the King of Terriers".', 'It served as a messenger and sentry in World War I.'],
      famous: ['Presidente Harding ("Laddie Boy")', 'Theodore Roosevelt'],
      curiosity: 'Tres presidentes de EE. UU. tuvieron Airedales en la Casa Blanca.',
      curiosityEn: 'Three U.S. presidents kept Airedales in the White House.',
    },
    'akita': {
      funFacts: ['Es un símbolo de lealtad y buena suerte en Japón.', 'Es fuerte, digno y muy protector con su familia.'],
      funFactsEn: ['It\'s a symbol of loyalty and good luck in Japan.', 'Strong, dignified, and very protective of its family.'],
      famous: ['Hachiko', 'Helen Keller'],
      curiosity: 'El Akita Hachiko esperó a su dueño en la estación de Shibuya cada día durante ~9 años.',
      curiosityEn: 'The Akita Hachiko waited for his owner at Shibuya station every day for ~9 years.',
    },
    'alaskan-malamute': {
      funFacts: ['Es un perro de trineo de carga, más grande y fuerte que el Husky.', 'Aúlla y "habla" más de lo que ladra.'],
      funFactsEn: ['It\'s a freight sled dog, bigger and stronger than the Husky.', 'It howls and "talks" more than it barks.'],
      curiosity: 'Debe su nombre al pueblo inuit Mahlemut, que lo crió en Alaska.',
      curiosityEn: 'It\'s named after the Mahlemut Inuit people who bred it in Alaska.',
    },
    'belgian-malinois': {
      funFacts: ['Es el perro de élite preferido por policías y militares.', 'Increíblemente atlético, inteligente y enérgico.'],
      funFactsEn: ['It\'s the elite dog of choice for police and military.', 'Incredibly athletic, intelligent and energetic.'],
      famous: ['Cairo (perro de los Navy SEAL)'],
      famousEn: ['Cairo (Navy SEAL dog)'],
      curiosity: 'Un Malinois llamado Cairo participó en la operación de 2011 contra Bin Laden.',
      curiosityEn: 'A Malinois named Cairo took part in the 2011 raid on Bin Laden.',
    },
    'bernese-mountain-dog': {
      funFacts: ['Gigante gentil de pelaje tricolor, criado en los Alpes suizos.', 'Adora el frío y a los niños por igual.'],
      funFactsEn: ['A gentle tricolor giant bred in the Swiss Alps.', 'It loves cold weather and kids equally.'],
      curiosity: 'Tiraba carros con leche y queso por las granjas de los Alpes suizos.',
      curiosityEn: 'It pulled carts of milk and cheese across Swiss Alpine farms.',
    },
    'boxer': {
      funFacts: ['Su nombre viene de cómo "boxea" con las patas delanteras al jugar.', 'Es payaso, leal y eternamente cachorro de corazón.'],
      funFactsEn: ['Its name comes from how it "boxes" with its front paws when playing.', 'It\'s a clown, loyal, and forever a puppy at heart.'],
      curiosity: 'Sirvió como perro mensajero y de guardia en la Primera Guerra Mundial.',
      curiosityEn: 'It served as a messenger and guard dog in World War I.',
    },
    'dalmatian': {
      funFacts: ['Nace completamente blanco: las manchas aparecen a las pocas semanas.', 'Fue perro de carruajes y mascota de los bomberos.'],
      funFactsEn: ['It\'s born pure white — the spots appear after a few weeks.', 'It was a carriage dog and a firehouse mascot.'],
      famous: ['101 Dálmatas', 'Mascota de los bomberos'],
      famousEn: ['101 Dalmatians', 'Firehouse mascot'],
      curiosity: 'Corría junto a los carros de bomberos tirados por caballos para abrir paso.',
      curiosityEn: 'It ran alongside horse-drawn fire carriages to clear the way.',
    },
    'doberman-pinscher': {
      funFacts: ['Es elegante, atlético y un guardián muy inteligente.', 'Aprende y obedece con una rapidez impresionante.'],
      funFactsEn: ['Elegant, athletic, and a very intelligent guardian.', 'It learns and obeys impressively fast.'],
      curiosity: 'Fue creado por un recaudador de impuestos alemán, Karl Dobermann, que quería protección en sus rondas.',
      curiosityEn: 'It was created by a German tax collector, Karl Dobermann, who wanted protection on his rounds.',
    },
    'great-dane': {
      funFacts: ['Lo llaman "el Apolo de los perros" por su porte.', 'Es de las razas más altas del mundo, pero un gigante gentil.'],
      funFactsEn: ['It\'s called "the Apollo of dogs" for its stature.', 'One of the tallest breeds in the world, yet a gentle giant.'],
      famous: ['Scooby-Doo', 'Marmaduke', 'Zeus (récord de altura)'],
      famousEn: ['Scooby-Doo', 'Marmaduke', 'Zeus (height record)'],
      curiosity: 'A pesar de su nombre ("gran danés"), la raza se desarrolló en Alemania.',
      curiosityEn: 'Despite its name ("Great Dane"), the breed was developed in Germany.',
    },
    'saint-bernard': {
      funFacts: ['Fue perro de rescate en los Alpes durante siglos.', 'Es enorme, baboso y de corazón gigante.'],
      funFactsEn: ['It was an Alpine rescue dog for centuries.', 'It\'s huge, drooly, and big-hearted.'],
      famous: ['Beethoven (película)', 'Barry (héroe de rescate)'],
      famousEn: ['Beethoven (movie)', 'Barry (rescue hero)'],
      curiosity: 'El famoso barrilito de brandy en el collar es un mito inventado por un pintor.',
      curiosityEn: 'The famous brandy barrel on the collar is a myth invented by a painter.',
    },
    'samoyed': {
      funFacts: ['Su "sonrisa Sammy" no es casualidad: evita que babee y se le hagan carámbanos.', 'Su pelaje blanco y espeso lo aísla del frío extremo.'],
      funFactsEn: ['Its "Sammy smile" isn\'t random: it prevents drooling and icicles.', 'Its thick white coat insulates it from extreme cold.'],
      curiosity: 'Ayudaba al pueblo Samoyedo de Siberia a arrear renos y a dormir abrigado.',
      curiosityEn: 'It helped the Samoyede people of Siberia herd reindeer and stay warm at night.',
    },
    'weimaraner': {
      funFacts: ['Lo apodan "el fantasma gris" por su pelaje plateado y ojos claros.', 'Es atlético, leal y muy apegado a su familia.'],
      funFactsEn: ['Nicknamed "the gray ghost" for its silver coat and light eyes.', 'It\'s athletic, loyal and very attached to its family.'],
      famous: ['Los perros de William Wegman'],
      famousEn: ['William Wegman\'s dogs'],
      curiosity: 'El artista William Wegman los hizo mundialmente famosos en sus fotografías y videos.',
      curiosityEn: 'Artist William Wegman made them world-famous in his photographs and videos.',
    },
    'yorkipoo': {
      funFacts: ['Cruce de Yorkshire Terrier y Poodle: pequeño, listo y alegre.', 'Suele soltar poco pelo, ideal para apartamentos.'],
      funFactsEn: ['A Yorkshire Terrier–Poodle mix: small, smart and cheerful.', 'Usually low-shedding — ideal for apartments.'],
      curiosity: 'Combina la chispa del Yorkie con la inteligencia del Poodle.',
      curiosityEn: 'It blends the Yorkie\'s spark with the Poodle\'s intelligence.',
    },
    'chocolate-labradoodle': {
      funFacts: ['Es un Labradoodle de color chocolate: Labrador + Poodle.', 'Amistoso, inteligente y de bajo desprendimiento de pelo.'],
      funFactsEn: ['It\'s a chocolate-colored Labradoodle: Labrador + Poodle.', 'Friendly, smart, and low-shedding.'],
      curiosity: 'Su color chocolate viene del gen marrón heredado de ambos padres.',
      curiosityEn: 'Its chocolate color comes from the brown gene inherited from both parents.',
    },
  };

  var CAT_TRIVIA = {
    'persian': {
      funFacts: ['Es el gato de raza más popular del mundo desde hace más de un siglo.', 'Su cara plana hace que sus ojos lagrimeen: hay que limpiarlos a diario.', 'Prefieren quedarse en el suelo: no son grandes saltadores.'],
      funFactsEn: ['It\'s been the world\'s most popular pedigreed cat for over a century.', 'Its flat face makes the eyes water — needs daily cleaning.', 'They prefer staying on the ground — not big jumpers.'],
      famous: ['Florence Nightingale', 'Marilyn Monroe', 'Raymond Chandler'],
      curiosity: 'Llegó a Europa desde Persia en el siglo XVII y fue favorito de la realeza, incluida la reina Victoria.',
      curiosityEn: 'It reached Europe from Persia in the 1600s and was a royal favorite, including Queen Victoria.',
    },
    'siamese': {
      funFacts: ['Son de los gatos más "habladores": mantienen conversaciones contigo.', 'Sus puntos oscuros aparecen en las zonas más frías del cuerpo.', 'Los gatitos nacen totalmente blancos y el color llega con los días.'],
      funFactsEn: ['Among the most "talkative" cats — they hold conversations with you.', 'Their dark points appear on the coolest parts of the body.', 'Kittens are born all white; color develops over days.'],
      famous: ['Si y Am (La Dama y el Vagabundo)', 'James Dean', 'Syd Barrett'],
      famousEn: ['Si and Am (Lady and the Tramp)', 'James Dean', 'Syd Barrett'],
      curiosity: 'Eran gatos sagrados en los templos de Tailandia (antiguo Siam) y se creía que guardaban las almas de la realeza.',
      curiosityEn: 'They were sacred temple cats in Thailand (old Siam), believed to guard the souls of royalty.',
    },
    'maine-coon': {
      funFacts: ['Es la raza de gato doméstico más grande: ¡hasta 1.2 m de largo!', 'Muchos adoran el agua y saben "hablar" con trinos.', 'Tienen pelo extra entre los dedos, como raquetas para la nieve.'],
      funFactsEn: ['The largest domestic cat breed — up to 1.2 m long!', 'Many love water and "talk" with chirps and trills.', 'They have extra fur between their toes, like snowshoes.'],
      famous: ['Stewie (récord Guinness al más largo)', 'Ricky Gervais'],
      famousEn: ['Stewie (Guinness record for longest)', 'Ricky Gervais'],
      curiosity: 'Es el gato oficial del estado de Maine y hay leyendas (falsas pero divertidas) de que es mitad mapache.',
      curiosityEn: 'It\'s the official state cat of Maine, with fun (false) legends that it\'s part raccoon.',
    },
    'bengal': {
      funFacts: ['Su pelaje brilla como si tuviera purpurina ("glitter").', 'Muchos aman el agua y juegan en la ducha.', 'Descienden del cruce con el gato leopardo asiático.'],
      funFactsEn: ['Their coat shimmers as if dusted with glitter.', 'Many love water and play in the shower.', 'They descend from crosses with the Asian leopard cat.'],
      famous: ['Kristin Stewart', 'Ian Somerhalder'],
      curiosity: 'Parecen pequeños leopardos, pero su carácter es de gato doméstico muy juguetón y atlético.',
      curiosityEn: 'They look like tiny leopards, but their temperament is that of a very playful, athletic house cat.',
    },
    'ragdoll': {
      funFacts: ['Se quedan "flojitos" como un muñeco de trapo cuando los cargas: de ahí su nombre.', 'Suelen recibirte en la puerta como un perro.', 'Sus ojos azules son una de sus marcas registradas.'],
      funFactsEn: ['They go limp like a rag doll when you hold them — hence the name.', 'They often greet you at the door like a dog.', 'Their blue eyes are a trademark.'],
      famous: ['Taylor Swift (fan de gatos)', 'Ed Sheeran'],
      curiosity: 'Fue desarrollado en California en los años 60 buscando un gato dócil, grande y muy apegado a las personas.',
      curiosityEn: 'It was developed in 1960s California, aiming for a docile, large, very people-attached cat.',
    },
    'british-shorthair': {
      funFacts: ['Inspiró al Gato de Cheshire de "Alicia en el País de las Maravillas".', 'Es el gato del famoso anuncio de Whiskas.', 'Su cuerpo redondo y mejillas le dan cara de peluche permanente.'],
      funFactsEn: ['It inspired the Cheshire Cat in "Alice in Wonderland".', 'It\'s the cat from the famous Whiskas ads.', 'Its round body and cheeks give it a permanent plush-toy face.'],
      famous: ['El Gato de Cheshire', 'Gato de Whiskas'],
      famousEn: ['The Cheshire Cat', 'The Whiskas cat'],
      curiosity: 'Es una de las razas de gato más antiguas; llegó a Gran Bretaña con los romanos.',
      curiosityEn: 'One of the oldest cat breeds; it arrived in Britain with the Romans.',
    },
    'sphynx': {
      funFacts: ['No es 100% calvo: tiene una pelusa suave como un durazno.', 'Necesita baños porque su piel acumula grasa.', 'Busca calor constante: adora las cobijas y tu regazo.'],
      funFactsEn: ['It\'s not 100% bald — it has a soft peach-fuzz coat.', 'Needs baths because its skin builds up oils.', 'Constantly seeks warmth — loves blankets and your lap.'],
      famous: ['Mr. Bigglesworth (Austin Powers)', 'Steven Tyler'],
      curiosity: 'La falta de pelo viene de una mutación natural aparecida en Canadá en 1966.',
      curiosityEn: 'Its hairlessness comes from a natural mutation that appeared in Canada in 1966.',
    },
    'scottish-fold': {
      funFacts: ['Sus orejitas dobladas vienen de una mutación natural.', 'Adoptan la "pose de Buda", sentados con la barriga al aire.', 'Nacen con orejas rectas; se doblan a las pocas semanas.'],
      funFactsEn: ['Their folded ears come from a natural mutation.', 'They adopt the "Buddha pose", sitting with their belly up.', 'Born with straight ears that fold after a few weeks.'],
      famous: ['Taylor Swift (Olivia Benson y Meredith Grey)', 'Ed Sheeran'],
      famousEn: ['Taylor Swift (Olivia Benson and Meredith Grey)', 'Ed Sheeran'],
      curiosity: 'Toda la raza desciende de una sola gata llamada Susie, encontrada en una granja escocesa en 1961.',
      curiosityEn: 'The entire breed descends from a single cat named Susie, found on a Scottish farm in 1961.',
    },
    'russian-blue': {
      funFacts: ['Su pelaje azul-plateado es denso y suave como felpa.', 'Tiene ojos verdes intensos y una "sonrisa" tipo Mona Lisa.'],
      funFactsEn: ['Its blue-silver coat is dense and plush.', 'It has intense green eyes and a Mona Lisa–like "smile".'],
      curiosity: 'En Rusia se cree que trae buena suerte; según la leyenda, vivían en los palacios de los zares.',
      curiosityEn: 'In Russia it\'s believed to bring good luck; legend says they lived in the czars\' palaces.',
    },
    'abyssinian': {
      funFacts: ['Su pelaje "ticked" (con bandas de color) recuerda a un puma en miniatura.', 'Es muy activo, curioso y juguetón: un payaso felino.'],
      funFactsEn: ['Its "ticked" coat (banded hairs) recalls a miniature cougar.', 'It\'s very active, curious and playful — a feline clown.'],
      curiosity: 'Se parece a los gatos de las pinturas del antiguo Egipto, aunque su origen real es discutido.',
      curiosityEn: 'It resembles the cats in ancient Egyptian art, though its true origin is debated.',
    },
    'devon-rex': {
      funFacts: ['Lo apodan "gato duende" por sus orejas enormes y cara traviesa.', 'Su pelaje rizado y suave casi parece de peluche.'],
      funFactsEn: ['Nicknamed the "pixie cat" for its huge ears and mischievous face.', 'Its curly, soft coat feels almost like plush.'],
      curiosity: 'Su pelo rizado nació de una mutación natural en Devon, Inglaterra, en 1960.',
      curiosityEn: 'Its curly coat came from a natural mutation in Devon, England, in 1960.',
    },
    'norwegian-forest': {
      funFacts: ['Su pelaje doble es casi impermeable, hecho para inviernos nórdicos.', 'Es un gran trepador: baja de los árboles de cabeza.'],
      funFactsEn: ['Its double coat is nearly waterproof, built for Nordic winters.', 'It\'s a great climber — it descends trees head-first.'],
      curiosity: 'En la mitología nórdica, gatos como él tiraban del carro de la diosa Freya.',
      curiosityEn: 'In Norse mythology, cats like it pulled the chariot of the goddess Freya.',
    },
    'himalayan': {
      funFacts: ['Combina el cuerpo del Persa con los puntos de color del Siamés.', 'Tiene ojos azules brillantes y pelaje largo y sedoso.'],
      funFactsEn: ['It blends the Persian\'s body with the Siamese\'s color points.', 'It has bright blue eyes and a long, silky coat.'],
      curiosity: 'Es, técnicamente, el cruce entre Persa y Siamés, criado para unir lo mejor de ambos.',
      curiosityEn: 'It\'s technically a Persian–Siamese cross, bred to combine the best of both.',
    },
  };

  try { if (typeof DOG_BREEDS !== 'undefined' && Array.isArray(DOG_BREEDS)) DOG_BREEDS.forEach(function (b) { if (DOG_TRIVIA[b.id]) Object.assign(b, DOG_TRIVIA[b.id]); }); } catch (e) {}
  try { if (typeof CAT_BREEDS !== 'undefined' && Array.isArray(CAT_BREEDS)) CAT_BREEDS.forEach(function (b) { if (CAT_TRIVIA[b.id]) Object.assign(b, CAT_TRIVIA[b.id]); }); } catch (e) {}
})();
