// breed-data-extra.jsx — Razas adicionales con fotos
// Cargado después de breed-data.jsx; agrega nuevas razas a DOG_BREEDS y DESIGNER_BREEDS

const EXTRA_DOG_BREEDS = [
  // ── PEQUEÑAS ──────────────────────────────────────────
  {
    id:'affenpinscher', name:'Affenpinscher', es:'Affenpinscher', emoji:'🐒',
    photo:'fotos-razas/Affenpinscher.png',
    size:'small', coat:['wiry'], hypo:false, energy:3, grooming:3, shedding:1,
    trainability:3, barking:3, family:3, kids:2, pets:3, apartment:5,
    origin:'Alemania', originEn:'Germany', flag:'🇩🇪',
    weight:'3–6 kg', height:'23–30 cm', lifespan:'12–15 años', akc:true, fci:true,
    temperament:['Entretenido','Valiente','Obstinado','Curioso','Activo'],
    temperamentEn:['Entertaining','Bold','Stubborn','Curious','Active'],
    bestFor:['Apartamentos','Adultos','Personas mayores'],
    bestForEn:['Apartments','Adults','Seniors'],
    desc:'El Affenpinscher, cuyo nombre alemán significa "perro mono", es conocido por su expresión cómica y su gran valentía. Pequeño pero con una personalidad enorme: curioso, entretenido y muy leal a su familia. A pesar de su tamaño, no duda en enfrentarse a perros mucho más grandes.',
    descEn:'The Affenpinscher, whose German name means "monkey dog," is known for its comical expression and great courage. Small but with an enormous personality: curious, entertaining, and very loyal to its family. Despite its size, it won\'t hesitate to confront much larger dogs.',
    care:'Cepillado regular del pelaje áspero. Stripping manual recomendado cada pocos meses. Ejercicio moderado diario.',
    careEn:'Regular brushing of wiry coat. Hand stripping recommended every few months. Moderate daily exercise.',
    health:'Generalmente saludable. Vigilar luxación de rótula, problemas respiratorios leves y problemas dentales.',
    healthEn:'Generally healthy. Watch for patellar luxation, mild breathing issues, and dental problems.',
    mixes:[{name:'Affen Terrier', parents:'Affenpinscher + Toy Fox Terrier', desc:'Pequeño y muy activo. Curioso e inteligente, hereda lo mejor de ambas razas.'}]
  },
  {
    id:'bichon-frise', name:'Bichon Frisé', es:'Bichón Frisé', emoji:'🐩',
    photo:'fotos-razas/Bichon Frise.png',
    size:'small', coat:['curly'], hypo:true, energy:3, grooming:4, shedding:1,
    trainability:4, barking:3, family:5, kids:5, pets:5, apartment:5,
    origin:'Francia / España', originEn:'France / Spain', flag:'🇫🇷',
    weight:'3–5 kg', height:'23–30 cm', lifespan:'12–15 años', akc:true, fci:true,
    temperament:['Juguetón','Gentil','Afectuoso','Alegre','Sociable'],
    temperamentEn:['Playful','Gentle','Affectionate','Cheerful','Sociable'],
    bestFor:['Apartamentos','Familias','Personas con alergias','Niños'],
    bestForEn:['Apartments','Families','Allergy sufferers','Children'],
    desc:'El Bichón Frisé es un pequeño perro de compañía con un pelaje blanco esponjoso y una personalidad irresistiblemente alegre. Hipoalergénico y casi sin derramamiento. Ha sido el favorito de la nobleza europea durante siglos. Sociable con todos — personas, niños y otras mascotas.',
    descEn:'The Bichon Frisé is a small companion dog with a fluffy white coat and an irresistibly cheerful personality. Hypoallergenic and minimal shedding. A favorite of European nobility for centuries. Sociable with everyone — people, children, and other pets.',
    care:'Cepillado diario para evitar enredos. Grooming profesional cada 4–6 semanas. Limpieza regular de manchas oculares.',
    careEn:'Daily brushing to prevent tangles. Professional grooming every 4–6 weeks. Regular cleaning of tear stains.',
    health:'Generalmente saludable. Vigilar alergias cutáneas, manchas lagrimales y luxación de rótula.',
    healthEn:'Generally healthy. Watch for skin allergies, tear staining, and patellar luxation.',
    mixes:[
      {name:'Shichon', parents:'Bichón Frisé + Shih Tzu', desc:'El famoso "Teddy Bear". Gentil, bajo derramamiento, ideal para familias.'},
      {name:'Cavachon', parents:'Bichón Frisé + Cavalier KCS', desc:'Dulce y juguetón. Excelente con niños y adultos mayores.'},
      {name:'Poochon', parents:'Bichón Frisé + Poodle', desc:'Muy popular, hipoalergénico e inteligente. Pelaje rizado adorable.'}
    ]
  },
  {
    id:'havanese', name:'Havanese', es:'Habanero', emoji:'🐶',
    photo:'fotos-razas/Havanese.png',
    size:'small', coat:['long','smooth'], hypo:true, energy:3, grooming:4, shedding:1,
    trainability:4, barking:3, family:5, kids:5, pets:5, apartment:5,
    origin:'Cuba', originEn:'Cuba', flag:'🇨🇺',
    weight:'3–6 kg', height:'23–28 cm', lifespan:'14–16 años', akc:true, fci:true,
    temperament:['Sociable','Juguetón','Afectuoso','Inteligente','Adaptable'],
    temperamentEn:['Sociable','Playful','Affectionate','Intelligent','Adaptable'],
    bestFor:['Apartamentos','Familias','Adultos mayores','Personas con alergias'],
    bestForEn:['Apartments','Families','Seniors','Allergy sufferers'],
    desc:'El Habanero es la raza nacional de Cuba y el único perro originario de la isla. Con su pelaje sedoso y su temperamento alegre, es uno de los perros de compañía más cariñosos del mundo. Hipoalergénico y casi sin derramamiento. Adora a las personas y no le gusta estar solo.',
    descEn:'The Havanese is the national dog of Cuba and the only breed native to the island. With its silky coat and cheerful temperament, it is one of the world\'s most affectionate companion dogs. Hypoallergenic and minimal shedding. Loves people and hates being left alone.',
    care:'Cepillado diario para evitar enredos. Muchos dueños optan por corte corto. Socialización temprana importante.',
    careEn:'Daily brushing to prevent tangles. Many owners prefer a short trim. Early socialization important.',
    health:'Generalmente saludable. Vigilar luxación de rótula, cataratas y displasia de cadera.',
    healthEn:'Generally healthy. Watch for patellar luxation, cataracts, and hip dysplasia.',
    mixes:[
      {name:'Havapoo', parents:'Habanero + Poodle', desc:'Inteligente, sin derramamiento y muy cariñoso. Popular para apartamentos.'},
      {name:'Havamalt', parents:'Habanero + Maltés', desc:'Sedoso y gentil. Casi sin derramamiento, perfecto para alergias leves.'}
    ]
  },
  {
    id:'jack-russell', name:'Jack Russell Terrier', es:'Jack Russell Terrier', emoji:'🐕',
    photo:'fotos-razas/Jack Russell Terrier.png',
    size:'small', coat:['short','wiry'], hypo:false, energy:5, grooming:2, shedding:2,
    trainability:3, barking:4, family:3, kids:3, pets:2, apartment:2,
    origin:'Inglaterra', originEn:'England', flag:'🇬🇧',
    weight:'6–8 kg', height:'25–30 cm', lifespan:'13–16 años', akc:true, fci:true,
    temperament:['Enérgico','Valiente','Inteligente','Curioso','Tenaz'],
    temperamentEn:['Energetic','Bold','Intelligent','Curious','Tenacious'],
    bestFor:['Casas con patio','Personas muy activas','Familias sin mascotas pequeñas'],
    bestForEn:['Houses with yard','Very active people','Families without small pets'],
    desc:'El Jack Russell Terrier fue criado en Inglaterra para cazar zorros. Es uno de los perros más energéticos y tenaces: su espíritu es enorme para su tamaño. Necesita ejercicio intenso y estimulación mental constante. No recomendado para dueños primerizos o apartamentos pequeños.',
    descEn:'The Jack Russell Terrier was bred in England to hunt foxes. It is one of the most energetic and tenacious dogs — its spirit is enormous for its size. Needs intense exercise and constant mental stimulation. Not recommended for first-time owners or small apartments.',
    care:'Ejercicio intenso diario obligatorio. Entrenamiento firme y constante. Excelente en agility.',
    careEn:'Intensive daily exercise essential. Firm, consistent training. Excels at agility.',
    health:'Generalmente saludable y robusto. Vigilar luxación de rótula y problemas oculares hereditarios.',
    healthEn:'Generally healthy and robust. Watch for patellar luxation and hereditary eye problems.',
    mixes:[
      {name:'Jackabee', parents:'Jack Russell + Beagle', desc:'Curioso y enérgico. Combina el olfato del Beagle con la energía del Jack Russell.'},
      {name:'Jack Chi', parents:'Jack Russell + Chihuahua', desc:'Pequeño y audaz. Personalidad explosiva en un cuerpo diminuto.'}
    ]
  },
  {
    id:'pug', name:'Pug', es:'Pug (Carlino)', emoji:'🐶',
    photo:'fotos-razas/Pug.png',
    size:'small', coat:['short'], hypo:false, energy:2, grooming:2, shedding:3,
    trainability:3, barking:2, family:5, kids:5, pets:5, apartment:5,
    origin:'China', originEn:'China', flag:'🇨🇳',
    weight:'6–8 kg', height:'25–30 cm', lifespan:'13–15 años', akc:true, fci:true,
    temperament:['Alegre','Encantador','Travieso','Cariñoso','Tranquilo'],
    temperamentEn:['Joyful','Charming','Mischievous','Affectionate','Calm'],
    bestFor:['Apartamentos','Familias','Adultos mayores','Niños'],
    bestForEn:['Apartments','Families','Seniors','Children'],
    desc:'El Pug, originario de la China imperial, fue criado para ser compañero de la realeza. Con su cara arrugada y sus grandes ojos expresivos, es uno de los perros más adorables y cariñosos del mundo. Tranquilo, alegre y excelente con niños y adultos mayores. Su lema: vivir para amar.',
    descEn:'The Pug, originally from imperial China, was bred to be a companion to royalty. With its wrinkled face and large expressive eyes, it is one of the world\'s most adorable and affectionate dogs. Calm, cheerful, and excellent with children and seniors. Its motto: live to love.',
    care:'Limpiar pliegues faciales a diario. Sensible al calor extremo — nunca ejercitar en días calurosos. Vigilar el peso.',
    careEn:'Clean facial wrinkles daily. Sensitive to extreme heat — never exercise in hot weather. Monitor weight.',
    health:'Braquicéfalo — vigilar problemas respiratorios. Propenso a obesidad, problemas oculares y displasia de cadera.',
    healthEn:'Brachycephalic — monitor breathing. Prone to obesity, eye problems, and hip dysplasia.',
    mixes:[
      {name:'Puggle', parents:'Pug + Beagle', desc:'Sociable y con menos problemas respiratorios que el Pug puro. Muy popular.'},
      {name:'Bugg', parents:'Pug + Boston Terrier', desc:'Adaptable y juguetón. Hereda el humor de ambas razas.'},
      {name:'Frug', parents:'French Bulldog + Pug', desc:'Cara chata y personalidad adorable. Muy cariñoso.'}
    ]
  },
  {
    id:'shiba-inu', name:'Shiba Inu', es:'Shiba Inu', emoji:'🦊',
    photo:'fotos-razas/Shiba Inu.png',
    size:'small', coat:['short','smooth'], hypo:false, energy:3, grooming:2, shedding:4,
    trainability:3, barking:2, family:3, kids:3, pets:2, apartment:3,
    origin:'Japón', originEn:'Japan', flag:'🇯🇵',
    weight:'6–10 kg', height:'33–41 cm', lifespan:'13–16 años', akc:true, fci:true,
    temperament:['Alerta','Activo','Confiado','Tranquilo','Independiente'],
    temperamentEn:['Alert','Active','Confident','Calm','Independent'],
    bestFor:['Personas con experiencia','Adultos','Hogares tranquilos'],
    bestForEn:['Experienced owners','Adults','Calm homes'],
    desc:'El Shiba Inu es la raza más pequeña y más antigua de Japón, con más de 3.000 años de historia. Con su apariencia de zorro y su temperamento independiente, se ha convertido en ícono cultural (famoso por los memes de internet). Limpio, inteligente y leal, pero con una personalidad fuerte que requiere experiencia.',
    descEn:'The Shiba Inu is the smallest and oldest breed in Japan, with over 3,000 years of history. With its fox-like appearance and independent temperament, it has become a cultural icon (famous for internet memes). Clean, intelligent, and loyal, but has a strong personality that requires experience.',
    care:'Cepillado regular — muda estacional intensa. Ejercicio moderado diario. Socialización temprana esencial.',
    careEn:'Regular brushing — intense seasonal shedding. Moderate daily exercise. Early socialization essential.',
    health:'Generalmente saludable. Vigilar displasia de cadera, problemas oculares y alergias.',
    healthEn:'Generally healthy. Watch for hip dysplasia, eye problems, and allergies.',
    mixes:[
      {name:'Shibadoodle', parents:'Shiba Inu + Poodle', desc:'Bajo derramamiento con la personalidad única del Shiba.'},
      {name:'Corgi Inu', parents:'Shiba Inu + Corgi', desc:'Personalidad fuerte con patas cortas. Muy fotogénico.'}
    ]
  },
  {
    id:'toy-poodle', name:'Toy Poodle', es:'Caniche Toy', emoji:'🐩',
    photo:'fotos-razas/Toy Poodle.png',
    size:'small', coat:['curly'], hypo:true, energy:3, grooming:5, shedding:1,
    trainability:5, barking:3, family:5, kids:4, pets:5, apartment:5,
    origin:'Francia / Alemania', originEn:'France / Germany', flag:'🇫🇷',
    weight:'2–4 kg', height:'24–28 cm', lifespan:'14–18 años', akc:true, fci:true,
    temperament:['Inteligente','Activo','Afectuoso','Adaptable','Elegante'],
    temperamentEn:['Intelligent','Active','Affectionate','Adaptable','Elegant'],
    bestFor:['Apartamentos','Personas con alergias','Adultos','Adultos mayores'],
    bestForEn:['Apartments','Allergy sufferers','Adults','Seniors'],
    desc:'El Caniche Toy es la versión más pequeña del Caniche, pero con toda la inteligencia y elegancia de la raza. Hipoalergénico y prácticamente sin derramamiento. Uno de los perros más fáciles de entrenar del mundo. Perfecto para apartamentos y personas con alergias. Tiene una longevidad excepcional para su tamaño.',
    descEn:'The Toy Poodle is the smallest version of the Poodle, but with all the intelligence and elegance of the breed. Hypoallergenic and virtually no shedding. One of the easiest dogs to train in the world. Perfect for apartments and allergy sufferers. Exceptional longevity for its size.',
    care:'Grooming profesional cada 4–6 semanas. Cepillado regular. Estimulación mental diaria importante.',
    careEn:'Professional grooming every 4–6 weeks. Regular brushing. Daily mental stimulation important.',
    health:'Generalmente muy saludable. Vigilar luxación de rótula, epilepsia y enfermedades oculares hereditarias.',
    healthEn:'Generally very healthy. Watch for patellar luxation, epilepsy, and hereditary eye diseases.',
    mixes:[
      {name:'Maltipoo', parents:'Maltés + Caniche Toy', desc:'Adorable e hipoalergénico. Popular para apartamentos.'},
      {name:'Yorkipoo', parents:'Yorkshire Terrier + Caniche Toy', desc:'Enérgico y sin derramamiento. Pequeño y activo.'}
    ]
  },

  // ── MEDIANAS ──────────────────────────────────────────
  {
    id:'australian-shepherd', name:'Australian Shepherd', es:'Pastor Australiano', emoji:'🐕‍🦺',
    photo:'fotos-razas/Australian Shepherd.png',
    size:'medium', coat:['long','smooth'], hypo:false, energy:5, grooming:3, shedding:4,
    trainability:5, barking:3, family:4, kids:4, pets:3, apartment:1,
    origin:'Estados Unidos', originEn:'United States', flag:'🇺🇸',
    weight:'16–32 kg', height:'46–58 cm', lifespan:'13–15 años', akc:true, fci:true,
    temperament:['Inteligente','Activo','Protector','Leal','Trabajador'],
    temperamentEn:['Intelligent','Active','Protective','Loyal','Hard-working'],
    bestFor:['Casas con jardín grande','Familias muy activas','Deporte canino'],
    bestForEn:['Houses with large yard','Very active families','Dog sports'],
    desc:'El Pastor Australiano fue desarrollado en el oeste de EE.UU. como perro de pastoreo, a pesar de su nombre. Excepcionalmente inteligente y atlético, con una necesidad enorme de ejercicio y trabajo mental. Sus ojos de colores (incluyendo heterocromía) y su pelaje moteado son inconfundibles. No apto para vida sedentaria.',
    descEn:'The Australian Shepherd was developed in the western United States as a herding dog, despite its name. Exceptionally intelligent and athletic, with a tremendous need for exercise and mental work. Its multi-colored eyes (including heterochromia) and merle coat are unmistakable. Not suitable for sedentary living.',
    care:'Ejercicio intenso diario (2+ horas). Cepillado frecuente. Entrenamiento y estimulación mental diarios esenciales.',
    careEn:'Intense daily exercise (2+ hours). Frequent brushing. Daily training and mental stimulation essential.',
    health:'Vigilar displasia de cadera, epilepsia, anomalía del ojo del Collie y sensibilidad a medicamentos MDR1.',
    healthEn:'Watch for hip dysplasia, epilepsy, Collie eye anomaly, and MDR1 drug sensitivity.',
    mixes:[
      {name:'Aussiedoodle', parents:'Pastor Australiano + Poodle', desc:'Inteligente, bajo derramamiento y muy activo. Popular en familias deportivas.'},
      {name:'Border Aussie', parents:'Pastor Australiano + Border Collie', desc:'Para personas extremadamente activas. Inteligencia y energía sin límites.'}
    ]
  },
  {
    id:'basset-hound', name:'Basset Hound', es:'Basset Hound', emoji:'🐶',
    photo:'fotos-razas/Basset Hound.png',
    size:'medium', coat:['short'], hypo:false, energy:2, grooming:2, shedding:3,
    trainability:2, barking:4, family:5, kids:5, pets:5, apartment:3,
    origin:'Francia / Bélgica', originEn:'France / Belgium', flag:'🇫🇷',
    weight:'20–27 kg', height:'30–38 cm', lifespan:'10–12 años', akc:true, fci:true,
    temperament:['Tranquilo','Amigable','Tenaz','Gentil','Devoto'],
    temperamentEn:['Calm','Friendly','Tenacious','Gentle','Devoted'],
    bestFor:['Familias','Casas tranquilas','Adultos mayores','Niños'],
    bestForEn:['Families','Calm homes','Seniors','Children'],
    desc:'El Basset Hound, con sus orejas largas características y su expresión melancólica, es un sabueso de rastreo con una nariz extraordinaria — la segunda más potente del mundo canino. Tranquilo y dócil en casa, pero tenaz en la pista de un olor. Excelente con niños y muy cariñoso.',
    descEn:'The Basset Hound, with its characteristic long ears and melancholy expression, is a tracking hound with an extraordinary nose — the second most powerful in the canine world. Calm and docile at home, but tenacious on a scent trail. Excellent with children and very affectionate.',
    care:'Limpiar orejas semanalmente para evitar infecciones. Vigilar el peso. Paseos moderados diarios suficientes.',
    careEn:'Clean ears weekly to prevent infections. Monitor weight. Moderate daily walks sufficient.',
    health:'Propenso a problemas de oídos, displasia de cadera, obesidad y problemas de piel en pliegues.',
    healthEn:'Prone to ear problems, hip dysplasia, obesity, and skin fold problems.',
    mixes:[
      {name:'Bagel', parents:'Basset Hound + Beagle', desc:'Curioso y sociable. Combina el olfato del Basset con la energía del Beagle.'},
      {name:'Bassador', parents:'Basset Hound + Labrador', desc:'Amigable y tranquilo. Más activo que el Basset puro.'}
    ]
  },
  {
    id:'bull-terrier', name:'Bull Terrier', es:'Bull Terrier', emoji:'🐶',
    photo:'fotos-razas/Bull Terrier.png',
    size:'medium', coat:['short'], hypo:false, energy:3, grooming:1, shedding:2,
    trainability:3, barking:2, family:4, kids:4, pets:2, apartment:3,
    origin:'Inglaterra', originEn:'England', flag:'🇬🇧',
    weight:'22–38 kg', height:'45–55 cm', lifespan:'11–14 años', akc:true, fci:true,
    temperament:['Juguetón','Encantador','Travieso','Leal','Persistente'],
    temperamentEn:['Playful','Charming','Mischievous','Loyal','Persistent'],
    bestFor:['Personas con experiencia','Familias activas','Casas sin mascotas pequeñas'],
    bestForEn:['Experienced owners','Active families','Homes without small pets'],
    desc:'El Bull Terrier es inconfundible con su cabeza ovalada característica y sus pequeños ojos triangulares. Originalmente criado en Inglaterra, hoy es conocido por su naturaleza juguetona y cariñosa. Es leal, travieso y muy entretenido. Necesita un dueño con experiencia que pueda manejar su tenacidad.',
    descEn:'The Bull Terrier is unmistakable with its characteristic egg-shaped head and small triangular eyes. Originally bred in England, today it is known for its playful and affectionate nature. Loyal, mischievous, and very entertaining. Needs an experienced owner who can handle its tenacity.',
    care:'Mínimo mantenimiento. Ejercicio moderado diario. Socialización temprana muy importante.',
    careEn:'Minimal maintenance. Moderate daily exercise. Early socialization very important.',
    health:'Vigilar sordera (especialmente en blancos), enfermedad renal hereditaria y problemas cardíacos.',
    healthEn:'Watch for deafness (especially in whites), hereditary kidney disease, and heart problems.',
    mixes:[{name:'Bull-Pei', parents:'Bull Terrier + Shar Pei', desc:'Leal y tranquilo. Apariencia única con los pliegues del Shar Pei.'}]
  },
  {
    id:'chow-chow', name:'Chow Chow', es:'Chow Chow', emoji:'🦁',
    photo:'fotos-razas/Chow Chow.png',
    size:'medium', coat:['long','smooth'], hypo:false, energy:2, grooming:4, shedding:4,
    trainability:2, barking:2, family:3, kids:2, pets:2, apartment:3,
    origin:'China', originEn:'China', flag:'🇨🇳',
    weight:'20–32 kg', height:'46–56 cm', lifespan:'8–12 años', akc:true, fci:true,
    temperament:['Independiente','Leal','Tranquilo','Reservado','Digno'],
    temperamentEn:['Independent','Loyal','Calm','Reserved','Dignified'],
    bestFor:['Personas con experiencia','Adultos sin niños pequeños','Hogares tranquilos'],
    bestForEn:['Experienced owners','Adults without small children','Calm homes'],
    desc:'El Chow Chow, con su lengua azul-negra única y su melena de león, es una de las razas más antiguas del mundo. Originario de China, fue perro de caza, pastoreo y guardia durante milenios. Es profundamente leal a su familia pero muy reservado con extraños. En temperamento, se parece más a un gato que a un perro.',
    descEn:'The Chow Chow, with its unique blue-black tongue and lion-like mane, is one of the world\'s oldest breeds. Originally from China, it was a hunting, herding, and guard dog for millennia. Deeply loyal to its family but very reserved with strangers. In temperament, it is more cat-like than dog-like.',
    care:'Cepillado frecuente (2–3 veces/semana). Muda estacional intensa. Socialización temprana crítica.',
    careEn:'Frequent brushing (2–3 times/week). Intense seasonal shedding. Early socialization critical.',
    health:'Propenso a displasia de cadera, problemas oculares y tiroideos. Sensible al calor.',
    healthEn:'Prone to hip dysplasia, eye and thyroid problems. Heat sensitive.',
    mixes:[
      {name:'Chow Shepherd', parents:'Chow Chow + Pastor Alemán', desc:'Leal y protector. Hereda la dignidad del Chow con la inteligencia del Pastor.'},
      {name:'Chow Lab', parents:'Chow Chow + Labrador', desc:'Más sociable que el Chow puro. Temperamento equilibrado.'}
    ]
  },
  {
    id:'pembroke-corgi', name:'Pembroke Welsh Corgi', es:'Corgi Galés de Pembroke', emoji:'🐕',
    photo:'fotos-razas/Pembroke Welsh Corgi.png',
    size:'small', coat:['short','smooth'], hypo:false, energy:4, grooming:3, shedding:4,
    trainability:4, barking:3, family:5, kids:4, pets:4, apartment:3,
    origin:'Gales, Reino Unido', originEn:'Wales, United Kingdom', flag:'🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    weight:'10–14 kg', height:'25–30 cm', lifespan:'12–15 años', akc:true, fci:true,
    temperament:['Alegre','Inteligente','Activo','Afectuoso','Alerta'],
    temperamentEn:['Cheerful','Intelligent','Active','Affectionate','Alert'],
    bestFor:['Familias activas','Casas con patio','Personas activas'],
    bestForEn:['Active families','Houses with yard','Active people'],
    desc:'El Corgi Galés de Pembroke, raza favorita de la Reina Isabel II de Inglaterra, es un perro de pastoreo compacto y atlético. A pesar de sus patas cortas, es sorprendentemente ágil y activo. Alegre, inteligente y muy leal, con una personalidad encantadora y expresión de zorrito inconfundible.',
    descEn:'The Pembroke Welsh Corgi, Queen Elizabeth II\'s favorite breed, is a compact and athletic herding dog. Despite its short legs, it is surprisingly agile and active. Cheerful, intelligent, and very loyal, with a charming personality and unmistakable fox-like expression.',
    care:'Cepillado frecuente — muda intensa dos veces al año. Ejercicio diario moderado-alto. Vigilar el peso.',
    careEn:'Frequent brushing — heavy shedding twice a year. Moderate-high daily exercise. Monitor weight.',
    health:'Propenso a displasia de cadera, degeneración ocular progresiva y problemas de columna.',
    healthEn:'Prone to hip dysplasia, progressive ocular degeneration, and spinal problems.',
    mixes:[
      {name:'Corgipoo', parents:'Corgi + Poodle', desc:'Bajo derramamiento con la personalidad encantadora del Corgi.'},
      {name:'Corman Shepherd', parents:'Corgi + Pastor Alemán', desc:'Inteligente y leal. Patas cortas con carácter de pastor.'}
    ]
  },

  // ── GRANDES ──────────────────────────────────────────
  {
    id:'afghan-hound', name:'Afghan Hound', es:'Galgo Afgano', emoji:'🐕',
    photo:'fotos-razas/Afghan Hound.png',
    size:'large', coat:['long'], hypo:true, energy:4, grooming:5, shedding:1,
    trainability:2, barking:2, family:3, kids:3, pets:2, apartment:2,
    origin:'Afganistán', originEn:'Afghanistan', flag:'🇦🇫',
    weight:'23–27 kg', height:'61–74 cm', lifespan:'12–14 años', akc:true, fci:true,
    temperament:['Independiente','Digno','Sensible','Cariñoso','Altivo'],
    temperamentEn:['Independent','Dignified','Sensitive','Affectionate','Aloof'],
    bestFor:['Personas con experiencia','Adultos','Deportistas de campo','Exposiciones'],
    bestForEn:['Experienced owners','Adults','Field sportspeople','Dog shows'],
    desc:'El Galgo Afgano es una de las razas más antiguas del mundo, originaria de las montañas de Afganistán. Con su pelaje largo y sedoso y su silueta esbelta, es considerado el perro más elegante del mundo. Increíblemente rápido — puede alcanzar 65 km/h. Hipoalergénico pero requiere mantenimiento intenso y dueños pacientes.',
    descEn:'The Afghan Hound is one of the world\'s oldest breeds, originating in the mountains of Afghanistan. With its long, silky coat and slender silhouette, it is considered the world\'s most elegant dog. Incredibly fast — can reach 65 km/h. Hypoallergenic but requires intensive maintenance and patient owners.',
    care:'Cepillado diario largo e intenso. Baños frecuentes. Ejercicio en áreas cercadas — velocidad extrema.',
    careEn:'Long, intensive daily brushing. Frequent baths. Exercise in fenced areas — extreme speed.',
    health:'Generalmente saludable. Vigilar displasia de cadera, problemas oculares y sensibilidad a la anestesia.',
    healthEn:'Generally healthy. Watch for hip dysplasia, eye problems, and anesthesia sensitivity.',
    mixes:[{name:'Afghan Retriever', parents:'Galgo Afgano + Golden Retriever', desc:'Más sociable que el Afgano puro. Pelaje espectacular y temperamento gentil.'}]
  },
  {
    id:'airedale-terrier', name:'Airedale Terrier', es:'Airedale Terrier', emoji:'🐕',
    photo:'fotos-razas/Airedale Terrier.png',
    size:'large', coat:['wiry'], hypo:false, energy:4, grooming:3, shedding:2,
    trainability:4, barking:3, family:4, kids:4, pets:2, apartment:2,
    origin:'Inglaterra', originEn:'England', flag:'🇬🇧',
    weight:'18–29 kg', height:'56–61 cm', lifespan:'11–14 años', akc:true, fci:true,
    temperament:['Valiente','Amistoso','Inteligente','Confiado','Leal'],
    temperamentEn:['Bold','Friendly','Intelligent','Confident','Loyal'],
    bestFor:['Familias activas','Casas con patio','Personas activas con experiencia'],
    bestForEn:['Active families','Houses with yard','Active experienced owners'],
    desc:'El Airedale Terrier, el "Rey de los Terriers", es el más grande de todos los terriers. Criado en el Valle de Aire en Yorkshire, fue utilizado como perro de caza, policía y mensajero en la Primera Guerra Mundial. Inteligente, valiente y leal, con un sentido del humor peculiar y gran versatilidad en deportes caninos.',
    descEn:'The Airedale Terrier, the "King of Terriers," is the largest of all terriers. Bred in the Aire Valley in Yorkshire, it was used as a hunting dog, police dog, and WWI messenger. Intelligent, brave, and loyal, with a peculiar sense of humor and great versatility in dog sports.',
    care:'Stripping o recorte cada 8–12 semanas. Ejercicio diario intenso. Entrenamiento firme y consistente.',
    careEn:'Stripping or clipping every 8–12 weeks. Intense daily exercise. Firm, consistent training.',
    health:'Generalmente saludable. Vigilar displasia de cadera, problemas de tiroides y alergias.',
    healthEn:'Generally healthy. Watch for hip dysplasia, thyroid problems, and allergies.',
    mixes:[{name:'Airedoodle', parents:'Airedale + Poodle', desc:'Inteligente y bajo derramamiento. Versátil y activo.'}]
  },
  {
    id:'akita', name:'Akita', es:'Akita', emoji:'🐺',
    photo:'fotos-razas/Akita.png',
    size:'large', coat:['short','smooth'], hypo:false, energy:3, grooming:3, shedding:4,
    trainability:3, barking:2, family:3, kids:3, pets:1, apartment:2,
    origin:'Japón', originEn:'Japan', flag:'🇯🇵',
    weight:'32–59 kg', height:'61–71 cm', lifespan:'10–13 años', akc:true, fci:true,
    temperament:['Leal','Valiente','Digno','Reservado','Protector'],
    temperamentEn:['Loyal','Courageous','Dignified','Reserved','Protective'],
    bestFor:['Personas con experiencia','Hogar sin otras mascotas','Adultos'],
    bestForEn:['Experienced owners','Single-pet households','Adults'],
    desc:'El Akita es el perro nacional de Japón y símbolo de buena salud, felicidad y larga vida. Mundialmente famoso por Hachikō, el Akita que esperó a su dueño fallecido durante 9 años en la estación de Shibuya. Profundamente leal, valiente y digno, pero requiere experiencia y no se lleva bien con otros perros.',
    descEn:'The Akita is Japan\'s national dog and a symbol of good health, happiness, and long life. World-famous for Hachikō, the Akita who waited for his deceased owner for 9 years at Shibuya Station. Deeply loyal, courageous, and dignified, but requires experience and does not get along well with other dogs.',
    care:'Cepillado intenso durante muda (dos veces al año). Ejercicio moderado diario. Entrenamiento temprano y firme.',
    careEn:'Intensive brushing during shedding (twice a year). Moderate daily exercise. Early, firm training.',
    health:'Vigilar displasia de cadera, hipotiroidismo y artritis autoinmune.',
    healthEn:'Watch for hip dysplasia, hypothyroidism, and autoimmune arthritis.',
    mixes:[{name:'Aki-Poo', parents:'Akita + Poodle', desc:'Leal con bajo derramamiento. Más sociable que el Akita puro.'}]
  },
  {
    id:'alaskan-malamute', name:'Alaskan Malamute', es:'Malamute de Alaska', emoji:'🐺',
    photo:'fotos-razas/Alaskan Malamute.png',
    size:'large', coat:['long'], hypo:false, energy:4, grooming:3, shedding:5,
    trainability:3, barking:2, family:4, kids:4, pets:2, apartment:1,
    origin:'Alaska (EE.UU.)', originEn:'Alaska (USA)', flag:'🇺🇸',
    weight:'32–43 kg', height:'58–64 cm', lifespan:'10–14 años', akc:true, fci:true,
    temperament:['Amistoso','Leal','Juguetón','Energético','Independiente'],
    temperamentEn:['Friendly','Loyal','Playful','Energetic','Independent'],
    bestFor:['Personas muy activas','Climas fríos','Casas con espacio'],
    bestForEn:['Very active people','Cold climates','Houses with space'],
    desc:'El Malamute de Alaska es uno de los perros de trineo más antiguos del mundo, criado por el pueblo Mahlemut de Alaska para arrastrar cargas pesadas en condiciones árticas. Más grande y musculoso que el Husky Siberiano, es amistoso y juguetón pero con una fuerza e independencia formidables. Necesita ejercicio intenso y espacio.',
    descEn:'The Alaskan Malamute is one of the world\'s oldest sled dogs, bred by the Mahlemut people of Alaska to haul heavy loads in Arctic conditions. Larger and more muscular than the Siberian Husky, it is friendly and playful but with formidable strength and independence. Needs intense exercise and space.',
    care:'Ejercicio intenso diario. Cepillado intenso durante muda. Nunca dejar sin supervisión en calor extremo.',
    careEn:'Intense daily exercise. Intensive brushing during shedding. Never leave unsupervised in extreme heat.',
    health:'Vigilar displasia de cadera, cataratas hereditarias y polineuropatía.',
    healthEn:'Watch for hip dysplasia, hereditary cataracts, and polyneuropathy.',
    mixes:[
      {name:'Malamoodle', parents:'Malamute + Poodle', desc:'Bajo derramamiento con la majestuosidad del Malamute.'},
      {name:'Alusky', parents:'Malamute + Husky', desc:'Doble nórdico. Muy energético, para personas activas en climas fríos.'}
    ]
  },
  {
    id:'belgian-malinois', name:'Belgian Malinois', es:'Malinois Belga', emoji:'🐕‍🦺',
    photo:'fotos-razas/Belgian Malinois.png',
    size:'large', coat:['short'], hypo:false, energy:5, grooming:2, shedding:4,
    trainability:5, barking:3, family:3, kids:3, pets:2, apartment:1,
    origin:'Bélgica', originEn:'Belgium', flag:'🇧🇪',
    weight:'22–34 kg', height:'56–66 cm', lifespan:'12–14 años', akc:true, fci:true,
    temperament:['Protector','Inteligente','Confiado','Alerta','Trabajador'],
    temperamentEn:['Protective','Intelligent','Confident','Alert','Hard-working'],
    bestFor:['Trabajo policial/militar','Personas muy activas con experiencia','Deporte canino avanzado'],
    bestForEn:['Police/military work','Very experienced active people','Advanced dog sports'],
    desc:'El Malinois Belga es el perro de trabajo por excelencia. Usado por fuerzas militares y policiales de todo el mundo, incluyendo operaciones especiales de EE.UU., es increíblemente inteligente, veloz y versátil. Su intensidad y su impulso de trabajo lo hacen inadecuado para la mayoría de los hogares sin experiencia canina avanzada.',
    descEn:'The Belgian Malinois is the ultimate working dog. Used by military and police forces worldwide, including U.S. special operations, it is incredibly intelligent, fast, and versatile. Its intensity and work drive make it unsuitable for most households without advanced canine experience.',
    care:'Ejercicio extremadamente intenso. Entrenamiento avanzado continuo. No es un perro de compañía casual.',
    careEn:'Extremely intense exercise. Continuous advanced training. Not a casual companion dog.',
    health:'Generalmente muy saludable. Vigilar displasia de cadera, problemas oculares y cataratas.',
    healthEn:'Generally very healthy. Watch for hip dysplasia, eye problems, and cataracts.',
    mixes:[{name:'Mali-Dutchie', parents:'Malinois Belga + Pastor Holandés', desc:'Doble potencia de trabajo. Solo para profesionales caninos.'}]
  },
  {
    id:'bernese-mountain-dog', name:'Bernese Mountain Dog', es:'Boyero de Berna', emoji:'🐕',
    photo:'fotos-razas/Bernese Mountain Dog.png',
    size:'large', coat:['long'], hypo:false, energy:3, grooming:3, shedding:4,
    trainability:4, barking:2, family:5, kids:5, pets:5, apartment:1,
    origin:'Suiza', originEn:'Switzerland', flag:'🇨🇭',
    weight:'32–52 kg', height:'58–70 cm', lifespan:'7–10 años', akc:true, fci:true,
    temperament:['Gentil','Cariñoso','Leal','Tranquilo','Paciente'],
    temperamentEn:['Gentle','Affectionate','Loyal','Calm','Patient'],
    bestFor:['Familias con niños','Casas con patio','Climas templados o fríos'],
    bestForEn:['Families with children','Houses with yard','Temperate or cold climates'],
    desc:'El Boyero de Berna, con su llamativo pelaje tricolor y su carácter de gigante gentil, es uno de los perros de familia más adorados del mundo. Originario de las granjas suizas, trabajaba como perro de tiro y pastoreo. Increíblemente paciente con los niños y cariñoso con toda la familia. Su mayor defecto: una vida demasiado corta.',
    descEn:'The Bernese Mountain Dog, with its striking tricolor coat and gentle giant character, is one of the world\'s most beloved family dogs. Originally from Swiss farms, it worked as a draft and herding dog. Incredibly patient with children and affectionate with the whole family. Its greatest flaw: too short a life.',
    care:'Cepillado 2–3 veces por semana. Muda estacional intensa. Ejercicio moderado — sensible al calor.',
    careEn:'Brush 2–3 times weekly. Intense seasonal shedding. Moderate exercise — sensitive to heat.',
    health:'Propenso a displasia de cadera y codo, histiocitosis maligna y cáncer. Esperanza de vida corta.',
    healthEn:'Prone to hip and elbow dysplasia, malignant histiocytosis, and cancer. Short lifespan.',
    mixes:[
      {name:'Bernedoodle', parents:'Boyero de Berna + Poodle', desc:'Muy popular. Bajo derramamiento con el carácter gentil del Bernese. Vida más larga.'},
      {name:'Golden Berner', parents:'Boyero de Berna + Golden Retriever', desc:'Enorme y cariñoso. Combina lo mejor de dos gigantes gentiles.'}
    ]
  },
  {
    id:'boxer', name:'Boxer', es:'Boxer', emoji:'🐶',
    photo:'fotos-razas/Boxer.png',
    size:'large', coat:['short'], hypo:false, energy:4, grooming:1, shedding:2,
    trainability:4, barking:3, family:5, kids:5, pets:3, apartment:2,
    origin:'Alemania', originEn:'Germany', flag:'🇩🇪',
    weight:'22–32 kg', height:'53–63 cm', lifespan:'10–12 años', akc:true, fci:true,
    temperament:['Alegre','Leal','Juguetón','Valiente','Cariñoso'],
    temperamentEn:['Joyful','Loyal','Playful','Brave','Affectionate'],
    bestFor:['Familias activas con niños','Casas con patio','Personas activas'],
    bestForEn:['Active families with kids','Houses with yard','Active people'],
    desc:'El Boxer es un perro eternamente joven, conocido por su carácter juguetón y su devoción familiar. Desarrollado en Alemania a partir del Bullenbeisser, es musculoso y atlético pero sorprendentemente gentil con los niños. Leal y protector con su familia, desconfiado con extraños. Tiene una de las infancias más largas del reino canino.',
    descEn:'The Boxer is an eternally young dog, known for its playful character and family devotion. Developed in Germany from the Bullenbeisser, it is muscular and athletic but surprisingly gentle with children. Loyal and protective with family, wary of strangers. Has one of the longest puppyhoods in the canine world.',
    care:'Mínimo mantenimiento de pelaje. Ejercicio diario moderado-alto. Muy sensible al calor.',
    careEn:'Minimal coat care. Moderate-high daily exercise. Very heat sensitive.',
    health:'Propenso a cardiomiopatía, displasia de cadera y ciertos tipos de cáncer.',
    healthEn:'Prone to cardiomyopathy, hip dysplasia, and certain cancers.',
    mixes:[
      {name:'Boxador', parents:'Boxer + Labrador', desc:'Amigable y atlético. Combina la energía del Boxer con la sociabilidad del Lab.'},
      {name:'Boxerdoodle', parents:'Boxer + Poodle', desc:'Bajo derramamiento. Inteligente y juguetón.'}
    ]
  },
  {
    id:'dalmatian', name:'Dalmatian', es:'Dálmata', emoji:'🐶',
    photo:'fotos-razas/Dalmatian.png',
    size:'large', coat:['short'], hypo:false, energy:4, grooming:2, shedding:3,
    trainability:4, barking:3, family:4, kids:4, pets:3, apartment:1,
    origin:'Croacia', originEn:'Croatia', flag:'🇭🇷',
    weight:'20–32 kg', height:'56–61 cm', lifespan:'10–13 años', akc:true, fci:true,
    temperament:['Activo','Amigable','Leal','Independiente','Inteligente'],
    temperamentEn:['Active','Friendly','Loyal','Independent','Intelligent'],
    bestFor:['Personas muy activas','Casas con patio','Familias deportistas'],
    bestForEn:['Very active people','Houses with yard','Sporty families'],
    desc:'El Dálmata, con sus inconfundibles manchas negras, es una raza antigua con historia como perro de carruajes, bomberos y circo. Muy activo y atlético, necesita ejercicio intenso diario. Alegre y leal con su familia, puede ser reservado con extraños. Famoso por "101 Dálmatas", lo cual aumentó su popularidad — pero no es para todos.',
    descEn:'The Dalmatian, with its unmistakable black spots, is an ancient breed with a history as a carriage dog, firehouse dog, and circus performer. Very active and athletic, needs intense daily exercise. Cheerful and loyal with family, can be reserved with strangers. Famous from "101 Dalmatians" — but not for everyone.',
    care:'Ejercicio intenso diario obligatorio. Dieta baja en purinas para prevenir cálculos urinarios. Cepillado regular.',
    careEn:'Intensive daily exercise essential. Low-purine diet to prevent urinary stones. Regular brushing.',
    health:'Propenso a sordera (25% nacen sordos), cálculos urinarios de urato y alergias cutáneas.',
    healthEn:'Prone to deafness (25% born deaf), urate urinary stones, and skin allergies.',
    mixes:[
      {name:'Dalmadoodle', parents:'Dálmata + Poodle', desc:'Bajo derramamiento y muy activo. Hereda las manchas características.'},
      {name:'Bodacion', parents:'Dálmata + Border Collie', desc:'Extremadamente activo e inteligente. Para personas muy deportistas.'}
    ]
  },
  {
    id:'doberman-pinscher', name:'Doberman Pinscher', es:'Doberman Pinscher', emoji:'🐕',
    photo:'fotos-razas/Doberman Pinscher.png',
    size:'large', coat:['short'], hypo:false, energy:4, grooming:1, shedding:2,
    trainability:5, barking:2, family:5, kids:4, pets:3, apartment:2,
    origin:'Alemania', originEn:'Germany', flag:'🇩🇪',
    weight:'27–45 kg', height:'61–72 cm', lifespan:'10–13 años', akc:true, fci:true,
    temperament:['Leal','Alerta','Confiado','Enérgico','Obediente'],
    temperamentEn:['Loyal','Alert','Confident','Energetic','Obedient'],
    bestFor:['Personas con experiencia','Familias activas','Protección/guardia'],
    bestForEn:['Experienced owners','Active families','Protection/guard'],
    desc:'El Doberman Pinscher fue creado en Alemania a finales del siglo XIX como perro de protección. Hoy es uno de los perros más fieles, obedientes e inteligentes del mundo. Con socialización y entrenamiento adecuados, es un perro familiar gentil y leal. Su reputación intimidante es en gran parte inmerecida.',
    descEn:'The Doberman Pinscher was created in Germany in the late 19th century as a protection dog. Today it is one of the world\'s most loyal, obedient, and intelligent dogs. With proper socialization and training, it is a gentle and loyal family dog. Its intimidating reputation is largely undeserved.',
    care:'Mínimo mantenimiento de pelaje. Ejercicio intenso diario. Entrenamiento y socialización temprana esenciales.',
    careEn:'Minimal coat care. Intense daily exercise. Early training and socialization essential.',
    health:'Vigilar cardiomiopatía dilatada, enfermedad de Von Willebrand y displasia de cadera.',
    healthEn:'Watch for dilated cardiomyopathy, Von Willebrand disease, and hip dysplasia.',
    mixes:[
      {name:'Doberdoodle', parents:'Doberman + Poodle', desc:'Bajo derramamiento y muy inteligente. Combina lealtad con inteligencia.'},
      {name:'Doberlab', parents:'Doberman + Labrador', desc:'Más sociable que el Doberman puro. Leal y amigable.'}
    ]
  },
  {
    id:'great-dane', name:'Great Dane', es:'Gran Danés', emoji:'🐕',
    photo:'fotos-razas/Great Dane.png',
    size:'large', coat:['short'], hypo:false, energy:3, grooming:1, shedding:3,
    trainability:4, barking:3, family:5, kids:4, pets:4, apartment:2,
    origin:'Alemania', originEn:'Germany', flag:'🇩🇪',
    weight:'45–90 kg', height:'71–86 cm', lifespan:'7–10 años', akc:true, fci:true,
    temperament:['Amistoso','Paciente','Confiable','Gentil','Cariñoso'],
    temperamentEn:['Friendly','Patient','Dependable','Gentle','Affectionate'],
    bestFor:['Casas espaciosas','Familias con niños mayores','Personas activas'],
    bestForEn:['Spacious homes','Families with older kids','Active people'],
    desc:'El Gran Danés, conocido como el "Apolo de los perros", es uno de los perros más grandes del mundo. A pesar de su enorme tamaño, es gentil, afectuoso y sorprendentemente tranquilo en casa. Excelente con niños y muy leal a su familia. Su corta esperanza de vida hace que cada momento juntos sea verdaderamente precioso.',
    descEn:'The Great Dane, known as the "Apollo of dogs," is one of the world\'s largest dogs. Despite its enormous size, it is gentle, affectionate, and surprisingly calm indoors. Excellent with children and very loyal to its family. Its short lifespan makes every moment together truly precious.',
    care:'Mínimo mantenimiento de pelaje. Ejercicio moderado — evitar ejercicio intenso en cachorros. Espacio suficiente.',
    careEn:'Minimal coat care. Moderate exercise — avoid intense exercise in puppies. Sufficient space to move.',
    health:'Propenso a dilatación gástrica (vólvulo), displasia de cadera, cardiomiopatía y osteosarcoma.',
    healthEn:'Prone to gastric dilation (bloat), hip dysplasia, cardiomyopathy, and osteosarcoma.',
    mixes:[
      {name:'Great Danoodle', parents:'Gran Danés + Poodle', desc:'Bajo derramamiento en un paquete gigante. Gentil y adaptable.'},
      {name:'Labradane', parents:'Gran Danés + Labrador', desc:'Amigable y enorme. Hereda lo mejor del Lab en tamaño XXL.'}
    ]
  },
  {
    id:'rottweiler', name:'Rottweiler', es:'Rottweiler', emoji:'🐕',
    photo:'fotos-razas/Rottweiler.png',
    size:'large', coat:['short'], hypo:false, energy:3, grooming:1, shedding:3,
    trainability:5, barking:2, family:4, kids:4, pets:2, apartment:2,
    origin:'Alemania', originEn:'Germany', flag:'🇩🇪',
    weight:'35–60 kg', height:'56–69 cm', lifespan:'8–10 años', akc:true, fci:true,
    temperament:['Seguro','Leal','Obediente','Confiado','Protector'],
    temperamentEn:['Steady','Loyal','Obedient','Confident','Protective'],
    bestFor:['Personas con experiencia','Familias activas','Protección','Casas con patio'],
    bestForEn:['Experienced owners','Active families','Protection','Houses with yard'],
    desc:'El Rottweiler, descendiente de los perros de pastoreo romanos, es uno de los perros de trabajo más versátiles del mundo. Ha servido como perro de policía, búsqueda, guía y terapia. Con socialización y entrenamiento adecuados, es un perro familiar confiable y protector. Su mala fama es producto de la cría irresponsable.',
    descEn:'The Rottweiler, descended from Roman herding dogs, is one of the world\'s most versatile working dogs. It has served as a police dog, search dog, guide dog, and therapy dog. With proper socialization and training, it is a reliable and protective family dog. Its bad reputation is the product of irresponsible breeding.',
    care:'Mínimo mantenimiento. Ejercicio intenso diario. Entrenamiento y socialización temprana obligatorios.',
    careEn:'Minimal maintenance. Intense daily exercise. Early training and socialization mandatory.',
    health:'Vigilar displasia de cadera y codo, cardiomiopatía y osteosarcoma.',
    healthEn:'Watch for hip and elbow dysplasia, cardiomyopathy, and osteosarcoma.',
    mixes:[
      {name:'Rottador', parents:'Rottweiler + Labrador', desc:'Más sociable que el Rottweiler puro. Leal y amigable.'},
      {name:'Rottle', parents:'Rottweiler + Poodle', desc:'Bajo derramamiento con la lealtad del Rottweiler.'}
    ]
  },
  {
    id:'saint-bernard', name:'Saint Bernard', es:'San Bernardo', emoji:'🐕',
    photo:'fotos-razas/Saint Bernard.png',
    size:'large', coat:['long','short'], hypo:false, energy:2, grooming:3, shedding:4,
    trainability:4, barking:2, family:5, kids:5, pets:4, apartment:1,
    origin:'Suiza / Italia', originEn:'Switzerland / Italy', flag:'🇨🇭',
    weight:'54–82 kg', height:'65–90 cm', lifespan:'8–10 años', akc:true, fci:true,
    temperament:['Gentil','Amigable','Paciente','Tranquilo','Servicial'],
    temperamentEn:['Gentle','Friendly','Patient','Calm','Helpful'],
    bestFor:['Familias con niños','Casas espaciosas','Climas fríos'],
    bestForEn:['Families with children','Spacious homes','Cold climates'],
    desc:'El San Bernardo, famoso por sus labores de rescate en los Alpes suizos durante 300 años, es el gentil gigante por excelencia. Con su tamaño imponente y su carácter dulce y paciente, es extraordinario con los niños. El hospicio del Gran San Bernardo lo utilizó para rescatar viajeros perdidos en la nieve durante siglos.',
    descEn:'The Saint Bernard, famous for 300 years of rescue work in the Swiss Alps, is the quintessential gentle giant. With its imposing size and sweet, patient character, it is extraordinary with children. The Great Saint Bernard Hospice used this breed to rescue travelers lost in the snow for centuries.',
    care:'Cepillado 2–3 veces por semana. Muy sensible al calor. Ejercicio moderado. Limpieza frecuente de baba.',
    careEn:'Brush 2–3 times weekly. Very heat sensitive. Moderate exercise. Frequent drool cleaning.',
    health:'Propenso a displasia de cadera y codo, dilatación gástrica (vólvulo) y cardiomiopatía.',
    healthEn:'Prone to hip and elbow dysplasia, gastric dilation (bloat), and cardiomyopathy.',
    mixes:[
      {name:'Saint Berdoodle', parents:'San Bernardo + Poodle', desc:'Bajo derramamiento en un paquete gigante. Muy gentil y cariñoso.'},
      {name:'Saint Labrador', parents:'San Bernardo + Labrador', desc:'Amigable y majestuoso. Grande pero manejable.'}
    ]
  },
  {
    id:'samoyed', name:'Samoyed', es:'Samoyedo', emoji:'🐺',
    photo:'fotos-razas/Samoyed.png',
    size:'large', coat:['long'], hypo:false, energy:4, grooming:4, shedding:5,
    trainability:3, barking:3, family:5, kids:5, pets:4, apartment:2,
    origin:'Siberia (Rusia)', originEn:'Siberia (Russia)', flag:'🇷🇺',
    weight:'16–30 kg', height:'51–60 cm', lifespan:'12–14 años', akc:true, fci:true,
    temperament:['Gentil','Adaptable','Amistoso','Juguetón','Leal'],
    temperamentEn:['Gentle','Adaptable','Friendly','Playful','Loyal'],
    bestFor:['Familias activas','Climas fríos','Casas con patio','Personas activas'],
    bestForEn:['Active families','Cold climates','Houses with yard','Active people'],
    desc:'El Samoyedo, con su pelaje blanco inmaculado y su permanente "sonrisa samoyeda", es uno de los perros más hermosos y gentiles del mundo. Criado por el pueblo Samoyedo de Siberia para pastorear renos y tirar trineos. Extremadamente amistoso con todos y sin instinto agresivo. Su sonrisa es famosa en todo el mundo.',
    descEn:'The Samoyed, with its immaculate white coat and permanent "Samoyed smile," is one of the most beautiful and gentle dogs in the world. Bred by the Samoyed people of Siberia to herd reindeer and pull sleds. Extremely friendly with everyone and has no aggressive instinct. Its smile is world-famous.',
    care:'Cepillado intenso diario durante muda. Baños regulares. Ejercicio moderado-alto diario.',
    careEn:'Intensive daily brushing during shedding. Regular baths. Moderate-high daily exercise.',
    health:'Generalmente saludable. Vigilar displasia de cadera, problemas oculares y síndrome hereditario del Samoyedo.',
    healthEn:'Generally healthy. Watch for hip dysplasia, eye problems, and hereditary Samoyed syndrome.',
    mixes:[
      {name:'Samdoodle', parents:'Samoyedo + Poodle', desc:'Bajo derramamiento con la sonrisa del Samoyedo. Muy sociable.'},
      {name:'Samsky', parents:'Samoyedo + Husky', desc:'Hermosa combinación nórdica. Activo y leal.'}
    ]
  },
  {
    id:'weimaraner', name:'Weimaraner', es:'Weimaraner', emoji:'🐕',
    photo:'fotos-razas/Weimaraner.png',
    size:'large', coat:['short'], hypo:false, energy:5, grooming:1, shedding:2,
    trainability:4, barking:3, family:4, kids:4, pets:2, apartment:1,
    origin:'Alemania', originEn:'Germany', flag:'🇩🇪',
    weight:'23–41 kg', height:'57–70 cm', lifespan:'11–14 años', akc:true, fci:true,
    temperament:['Enérgico','Alerta','Leal','Amistoso','Obstinado'],
    temperamentEn:['Energetic','Alert','Loyal','Friendly','Stubborn'],
    bestFor:['Personas muy activas','Casas con patio grande','Deportistas/cazadores'],
    bestForEn:['Very active people','Houses with large yard','Sportspeople/hunters'],
    desc:'El Weimaraner, conocido como el "Fantasma Plateado" por su distintivo pelaje gris plateado, fue criado en Alemania como perro de caza de alto rendimiento. Increíblemente atlético y necesita ejercicio intenso diario. Muy leal a su familia — tanto que puede desarrollar ansiedad de separación. Requiere un dueño activo y experimentado.',
    descEn:'The Weimaraner, known as the "Silver Ghost" for its distinctive silver-gray coat, was bred in Germany as a high-performance hunting dog. Incredibly athletic and needs intense daily exercise. Very loyal to its family — so much so that it can develop separation anxiety. Requires an active, experienced owner.',
    care:'Ejercicio intenso diario (mínimo 2 horas). Mínimo mantenimiento de pelaje. Entrenamiento firme desde cachorro.',
    careEn:'Intense daily exercise (minimum 2 hours). Minimal coat care. Firm training from puppyhood.',
    health:'Vigilar dilatación gástrica (vólvulo), displasia de cadera y problemas oculares.',
    healthEn:'Watch for gastric dilation (bloat), hip dysplasia, and eye problems.',
    mixes:[
      {name:'Weimardoodle', parents:'Weimaraner + Poodle', desc:'Bajo derramamiento con la energía y elegancia del Weimaraner.'},
      {name:'Labmaraner', parents:'Weimaraner + Labrador', desc:'Amigable y atlético. Más manejable que el Weimaraner puro.'}
    ]
  },
];

const EXTRA_DESIGNER_BREEDS = [
  { id:'yorkipoo', name:'Yorkipoo', parents:'Yorkshire Terrier + Toy Poodle', emoji:'🐩',
    photo:'fotos-razas/Yorkipoo.png',
    size:'small', coat:['curly','wavy'], hypo:true, energy:3,
    desc:'El Yorkipoo combina la valentía y personalidad del Yorkshire Terrier con la inteligencia y bajo derramamiento del Caniche Toy. Pequeño, activo y cariñoso, ideal para apartamentos y personas con alergias leves.',
    descEn:'The Yorkipoo combines the boldness and personality of the Yorkshire Terrier with the intelligence and low shedding of the Toy Poodle. Small, active, and affectionate — ideal for apartments and people with mild allergies.'},
  { id:'chocolate-labradoodle', name:'Chocolate Labradoodle', parents:'Labrador Retriever + Poodle', emoji:'🐩',
    photo:'fotos-razas/Chocolate Labradoodle.png',
    size:'medium-large', coat:['curly','wavy'], hypo:true, energy:4,
    desc:'La variante chocolate del Labradoodle, con su pelaje marrón cálido y rizado, es una de las versiones más buscadas. Hereda la obediencia y sociabilidad del Labrador con el bajo derramamiento del Poodle. Excelente perro de servicio, familia y apoyo emocional.',
    descEn:'The chocolate variant of the Labradoodle, with its warm brown curly coat, is one of the most sought-after versions. Inherits the obedience and sociability of the Labrador with the low shedding of the Poodle. Excellent service dog, family dog, and emotional support animal.'},
];

// Agregar a los arrays globales
DOG_BREEDS.push(...EXTRA_DOG_BREEDS);
DESIGNER_BREEDS.push(...EXTRA_DESIGNER_BREEDS);
