// breed-data.jsx — Comprehensive dog breed directory

const DOG_BREEDS = [
  // ── SMALL ──────────────────────────────────────────────
  {
    id:'french-bulldog', name:'French Bulldog', es:'Bulldog Francés', emoji:'🐶', photo:'fotos-razas/French Bulldog.webp',
    size:'small', coat:['short'], hypo:false, energy:2, grooming:1, shedding:2,
    trainability:3, barking:2, family:5, kids:5, pets:4, apartment:5,
    origin:'Francia / Inglaterra', originEn:'France / England', flag:'🇫🇷',
    weight:'8–13 kg', height:'27–35 cm', lifespan:'10–12 años', akc:true, fci:true,
    temperament:['Adaptable','Juguetón','Leal','Alerta','Cariñoso'],
    temperamentEn:['Adaptable','Playful','Loyal','Alert','Affectionate'],
    bestFor:['Apartamentos','Familias','Adultos mayores','Dueños primerizos'],
    bestForEn:['Apartments','Families','Seniors','First-time owners'],
    desc:'El Bulldog Francés es un compañero encantador con orejas en forma de murciélago. Descendiente de Bulldogs ingleses llevados a Francia en el siglo XIX. Altamente adaptable, puede vivir en apartamento o casa, con niños o adultos mayores. Tiene sentido del humor inigualable y lealtad profunda.',
    descEn:'The French Bulldog is a charming companion with bat-like ears. Descended from English Bulldogs brought to France in the 1800s. Highly adaptable — thrives in apartments or houses, with kids or seniors. Unmistakable sense of humor and deep loyalty.',
    care:'Limpiar pliegues faciales a diario. Mínimo cepillado. Sensible al calor — nunca ejercitar en días calurosos.',
    careEn:'Wipe facial folds daily. Minimal brushing. Heat-sensitive — avoid exercise in hot weather.',
    health:'Braquicéfalo — propenso a problemas respiratorios. Vigilar problemas espinales y alergias.',
    healthEn:'Brachycephalic — prone to breathing issues. Watch for spinal problems and allergies.',
    mixes:[
      {name:'Frenchton', parents:'French Bulldog + Boston Terrier', desc:'Más activo que el Frenchie puro, mejor tolerancia al calor. Temperamento juguetón y cuerpo compacto.'},
      {name:'Frug', parents:'French Bulldog + Pug', desc:'Cara ultrachata y personalidad divertida. Muy cariñoso. Requiere vigilancia respiratoria.'},
      {name:'French Bullhuahua', parents:'French Bulldog + Chihuahua', desc:'Pequeño y alerta. Hereda la valentía del Chihuahua y el humor del Frenchie.'},
    ]
  },
  {
    id:'yorkshire-terrier', name:'Yorkshire Terrier', es:'Yorkshire Terrier', emoji:'🐩', photo:'fotos-razas/Yorkshire Terrier.webp',
    size:'small', coat:['long','smooth'], hypo:true, energy:3, grooming:4, shedding:1,
    trainability:3, barking:4, family:4, kids:3, pets:3, apartment:5,
    origin:'Inglaterra', originEn:'England', flag:'🇬🇧',
    weight:'2–3.2 kg', height:'17–23 cm', lifespan:'13–16 años', akc:true, fci:true,
    temperament:['Valiente','Independiente','Curioso','Cariñoso','Energético'],
    temperamentEn:['Bold','Independent','Curious','Affectionate','Energetic'],
    bestFor:['Apartamentos','Adultos','Personas activas'],
    bestForEn:['Apartments','Adults','Active people'],
    desc:'El Yorkshire Terrier nació en el norte de Inglaterra para cazar ratas en minas y fábricas textiles. Hoy es uno de los perros de compañía más amados del mundo. A pesar de su pequeño tamaño, tiene una personalidad enorme: valiente, curioso e independiente. Su pelaje sedoso requiere cuidado regular pero no suelta mucho pelo.',
    descEn:'The Yorkshire Terrier was bred in northern England to hunt rats in mines and textile mills. Today it\'s one of the world\'s most beloved companions. Despite its small size, it has an enormous personality: brave, curious, and independent. Its silky coat requires regular care but sheds minimally.',
    care:'Cepillado diario para evitar nudos. Visitas al groomer cada 6–8 semanas. Limpieza dental regular.',
    careEn:'Daily brushing to prevent tangles. Groomer visits every 6–8 weeks. Regular dental care.',
    health:'Propenso a problemas dentales, luxación de rótula y colapso traqueal. Alimentación de calidad esencial.',
    healthEn:'Prone to dental issues, patellar luxation, and tracheal collapse. High-quality diet essential.',
    mixes:[
      {name:'Morkie', parents:'Maltese + Yorkshire Terrier', desc:'Pelaje suave y temperamento cariñoso. Muy sociable, ideal para apartamentos y familias sin niños pequeños.'},
      {name:'Chorkie', parents:'Chihuahua + Yorkshire Terrier', desc:'Pequeño, activo y lleno de personalidad. Leal a su dueño principal y desconfiado con extraños.'},
      {name:'Shorkie', parents:'Shih Tzu + Yorkshire Terrier', desc:'Dócil y amigable. Combina la dulzura del Shih Tzu con la energía del Yorkie. Pelaje suave y poco derramante.'},
      {name:'Borkie', parents:'Beagle + Yorkshire Terrier', desc:'Curioso y juguetón. Hereda la nariz del Beagle y la valentía del Yorkie. Ideal para familias activas.'},
    ]
  },
  {
    id:'pomeranian', name:'Pomeranian', es:'Pomerania', emoji:'🦊', photo:'fotos-razas/Pomeranian.webp',
    size:'small', coat:['long'], hypo:false, energy:3, grooming:4, shedding:3,
    trainability:4, barking:4, family:4, kids:3, pets:3, apartment:5,
    origin:'Alemania / Polonia', originEn:'Germany / Poland', flag:'🇩🇪',
    weight:'1.8–3.5 kg', height:'18–22 cm', lifespan:'12–16 años', akc:true, fci:true,
    temperament:['Vivaz','Curioso','Audaz','Amigable','Extrovertido'],
    temperamentEn:['Lively','Curious','Bold','Friendly','Extroverted'],
    bestFor:['Apartamentos','Adultos','Personas mayores'],
    bestForEn:['Apartments','Adults','Seniors'],
    desc:'El Pomerania es un perro pequeño de gran corazón, con su característico pelaje esponjoso y su expresión de zorro. Descendiente de perros de trineo del Ártico, fue reducido de tamaño por la realeza europea, especialmente la Reina Victoria. Vivaz y activo, le encanta aprender trucos y ser el centro de atención.',
    descEn:'The Pomeranian is a small dog with a big heart, with its characteristic fluffy coat and fox-like expression. Descended from Arctic sled dogs, it was miniaturized by European royalty, especially Queen Victoria. Lively and active, it loves learning tricks and being the center of attention.',
    care:'Cepillado 2–3 veces por semana. Baño mensual. Evitar calor excesivo por su doble capa.',
    careEn:'Brush 2–3 times weekly. Monthly bath. Avoid excessive heat due to double coat.',
    health:'Propenso a luxación de rótula, problemas dentales y colapso traqueal.',
    healthEn:'Prone to patellar luxation, dental problems, and tracheal collapse.',
    mixes:[
      {name:'Pomchi', parents:'Pomeranian + Chihuahua', desc:'Pequeño y valiente. Hereda el pelaje del Pomerania y la actitud del Chihuahua. Muy leal a su dueño.'},
      {name:'Pomsky', parents:'Pomeranian + Husky Siberiano', desc:'Adorable combinación con ojos penetrantes del Husky y el tamaño manejable del Pomerania. Alta demanda.'},
      {name:'Pomapoo', parents:'Pomeranian + Poodle', desc:'Inteligente y de bajo derramamiento. Pelaje suave y rizado. Muy sociable y adaptable.'},
    ]
  },
  {
    id:'chihuahua', name:'Chihuahua', es:'Chihuahua', emoji:'🐕', photo:'fotos-razas/Chihuahua.webp',
    size:'small', coat:['short','long'], hypo:false, energy:3, grooming:2, shedding:2,
    trainability:3, barking:4, family:3, kids:2, pets:3, apartment:5,
    origin:'México', originEn:'Mexico', flag:'🇲🇽',
    weight:'1.5–3 kg', height:'15–23 cm', lifespan:'14–17 años', akc:true, fci:true,
    temperament:['Valiente','Leal','Curioso','Alerta','Independiente'],
    temperamentEn:['Bold','Loyal','Curious','Alert','Independent'],
    bestFor:['Apartamentos','Adultos','Una sola persona'],
    bestForEn:['Apartments','Adults','Single owners'],
    desc:'El Chihuahua es la raza más pequeña del mundo y una de las más antiguas de América. Originario de México, lleva el nombre del estado donde fue descubierto. Tiene una personalidad enorme en un cuerpo diminuto. Es increíblemente leal a su dueño principal y puede ser desconfiado con extraños. Ideal para adultos que buscan un compañero constante.',
    descEn:'The Chihuahua is the world\'s smallest breed and one of the oldest in the Americas. Originating in Mexico, named after the state where it was discovered. It has an enormous personality in a tiny body. Incredibly loyal to its main owner and can be wary of strangers. Ideal for adults seeking a constant companion.',
    care:'Poco mantenimiento en pelaje corto. Los de pelo largo requieren cepillado regular. Muy sensible al frío.',
    careEn:'Low maintenance for short coat. Long-coated need regular brushing. Very cold-sensitive.',
    health:'Propenso a problemas dentales, luxación de rótula y fontanela abierta. Huesos frágiles.',
    healthEn:'Prone to dental issues, patellar luxation, and open fontanelle. Fragile bones.',
    mixes:[
      {name:'Chorkie', parents:'Chihuahua + Yorkshire Terrier', desc:'Pequeño y lleno de energía. Personalidad fuerte y gran valentía para su tamaño.'},
      {name:'Chion', parents:'Chihuahua + Papillon', desc:'Elegante y vivaz. Hereda las orejas características del Papillon con el temperamento del Chihuahua.'},
      {name:'Pomchi', parents:'Chihuahua + Pomeranian', desc:'Esponjoso y atrevido. Combina el pelaje del Pomerania con la audacia del Chihuahua.'},
    ]
  },
  {
    id:'maltese', name:'Maltese', es:'Maltés', emoji:'🐩', photo:'fotos-razas/Maltese.webp',
    size:'small', coat:['long','smooth'], hypo:true, energy:2, grooming:4, shedding:1,
    trainability:4, barking:3, family:5, kids:3, pets:4, apartment:5,
    origin:'Malta / Mediterráneo', originEn:'Malta / Mediterranean', flag:'🇲🇹',
    weight:'1.4–3.6 kg', height:'20–25 cm', lifespan:'12–15 años', akc:true, fci:true,
    temperament:['Gentil','Juguetón','Responsivo','Cariñoso','Elegante'],
    temperamentEn:['Gentle','Playful','Responsive','Affectionate','Elegant'],
    bestFor:['Apartamentos','Adultos','Apoyo emocional'],
    bestForEn:['Apartments','Adults','Emotional support'],
    desc:'El Maltés es una de las razas más antiguas del mundo, con más de 2.000 años de historia como perro de compañía de la nobleza mediterránea. Su pelaje blanco como la seda y su carácter gentil lo hacen ideal como perro de apoyo emocional. Es hipoalergénico y suelta muy poco pelo, perfecto para personas con alergias leves.',
    descEn:'The Maltese is one of the world\'s oldest breeds, with over 2,000 years of history as a companion to Mediterranean nobility. Its silky white coat and gentle character make it ideal as an emotional support dog. Hypoallergenic and minimal shedding — perfect for people with mild allergies.',
    care:'Cepillado diario esencial. Muchos dueños optan por corte corto (puppy cut). Limpieza ocular para evitar manchas.',
    careEn:'Daily brushing essential. Many owners opt for a puppy cut. Eye cleaning to prevent tear stains.',
    health:'Relativamente saludable. Vigilar luxación de rótula, problemas dentales y manchas lagrimales.',
    healthEn:'Relatively healthy. Watch for patellar luxation, dental issues, and tear staining.',
    mixes:[
      {name:'Maltipoo', parents:'Maltese + Poodle', desc:'Muy popular. Hipoalergénico, inteligente y adorable. Hereda lo mejor de ambas razas.'},
      {name:'Morkie', parents:'Maltese + Yorkshire Terrier', desc:'Pelaje suave y gran personalidad. Muy adaptable y cariñoso con su familia.'},
      {name:'Malshi', parents:'Maltese + Shih Tzu', desc:'Gentil y sociable. Ideal para apartamentos y familias sin niños muy pequeños.'},
    ]
  },
  {
    id:'shih-tzu', name:'Shih Tzu', es:'Shih Tzu', emoji:'🐶', photo:'fotos-razas/Shih Tzu.webp',
    size:'small', coat:['long'], hypo:false, energy:2, grooming:4, shedding:1,
    trainability:3, barking:2, family:5, kids:4, pets:5, apartment:5,
    origin:'China / Tibet', originEn:'China / Tibet', flag:'🇨🇳',
    weight:'4–7.2 kg', height:'20–28 cm', lifespan:'10–18 años', akc:true, fci:true,
    temperament:['Amigable','Confiado','Vivo','Cariñoso','Independiente'],
    temperamentEn:['Friendly','Confident','Lively','Affectionate','Independent'],
    bestFor:['Apartamentos','Familias','Adultos mayores','Apoyo emocional'],
    bestForEn:['Apartments','Families','Seniors','Emotional support'],
    desc:'El Shih Tzu, cuyo nombre significa "León pequeño" en chino, fue criado durante siglos en los palacios imperiales de China y Tibet. Es uno de los perros de compañía más antiguos y amados del mundo. Dócil, amigable con todos y sorprendentemente robusto para su tamaño. Excelente con niños, adultos mayores y otras mascotas.',
    descEn:'The Shih Tzu, whose name means "little lion" in Chinese, was bred for centuries in the imperial palaces of China and Tibet. One of the world\'s oldest and most beloved companions. Docile, friendly with everyone, and surprisingly sturdy for its size. Excellent with children, seniors, and other pets.',
    care:'Cepillado diario. Corte profesional cada 6–8 semanas. Limpieza regular de ojos y pliegues faciales.',
    careEn:'Daily brushing. Professional grooming every 6–8 weeks. Regular eye and facial fold cleaning.',
    health:'Generalmente saludable. Vigilar problemas oculares, problemas respiratorios leves y luxación de rótula.',
    healthEn:'Generally healthy. Watch for eye problems, mild breathing issues, and patellar luxation.',
    mixes:[
      {name:'Shorkie', parents:'Shih Tzu + Yorkshire Terrier', desc:'Pelaje sedoso y mucha personalidad. Juguetón y leal. Ideal para apartamentos.'},
      {name:'Malshi', parents:'Shih Tzu + Maltese', desc:'Gentil y fácil de manejar. Poco derramante, ideal para personas con alergias leves.'},
      {name:'Shichon', parents:'Shih Tzu + Bichon Frisé', desc:'También llamado "Teddy Bear". Pelo rizado suave, carácter dulce. Muy popular como perro de compañía.'},
    ]
  },
  {
    id:'miniature-schnauzer', name:'Miniature Schnauzer', es:'Schnauzer Miniatura', emoji:'🐕', photo:'fotos-razas/Miniature Schnauzer.webp',
    size:'small', coat:['wiry'], hypo:true, energy:3, grooming:3, shedding:1,
    trainability:5, barking:3, family:5, kids:5, pets:3, apartment:4,
    origin:'Alemania', originEn:'Germany', flag:'🇩🇪',
    weight:'5–9 kg', height:'30–36 cm', lifespan:'12–15 años', akc:true, fci:true,
    temperament:['Amigable','Obediente','Inteligente','Animado','Alerta'],
    temperamentEn:['Friendly','Obedient','Intelligent','Spirited','Alert'],
    bestFor:['Casas con patio','Familias con niños','Personas activas'],
    bestForEn:['Houses with yard','Families with kids','Active people'],
    desc:'El Schnauzer Miniatura es el más popular de los tres tamaños de Schnauzer. Originado en Alemania como perro cazador de ratas, combina inteligencia, robustez y un carácter adorable. Hipoalergénico, suelta muy poco pelo y se lleva muy bien con niños. Es obediente, fácil de entrenar y muy adaptable.',
    descEn:'The Miniature Schnauzer is the most popular of the three Schnauzer sizes. Originating in Germany as a rat-hunting dog, it combines intelligence, robustness, and an adorable character. Hypoallergenic, minimal shedding, and great with children. Obedient, easy to train, and very adaptable.',
    care:'Stripping o recorte cada 5–8 semanas. Cepillado regular. Barba necesita limpieza después de comer.',
    careEn:'Stripping or clipping every 5–8 weeks. Regular brushing. Beard needs cleaning after meals.',
    health:'Generalmente robusto. Vigilar pancreatitis, cálculos renales y problemas oculares.',
    healthEn:'Generally robust. Watch for pancreatitis, kidney stones, and eye problems.',
    mixes:[
      {name:'Schnoodle', parents:'Schnauzer + Poodle', desc:'Inteligente y casi sin derramamiento. Hereda lo mejor de dos razas altamente entrenables.'},
      {name:'Snorkie', parents:'Schnauzer Miniatura + Yorkie', desc:'Pequeño y valiente. Muy enérgico y cariñoso con su familia.'},
    ]
  },
  {
    id:'cavalier-kcs', name:'Cavalier King Charles', es:'Cavalier King Charles', emoji:'🐶', photo:'fotos-razas/Cavalier King Charles Spaniel.webp',
    size:'small', coat:['long','smooth'], hypo:false, energy:2, grooming:3, shedding:2,
    trainability:4, barking:2, family:5, kids:5, pets:5, apartment:5,
    origin:'Inglaterra', originEn:'England', flag:'🇬🇧',
    weight:'5.9–8.2 kg', height:'30–33 cm', lifespan:'9–14 años', akc:true, fci:true,
    temperament:['Gentil','Afectuoso','Sociable','Dócil','Adaptable'],
    temperamentEn:['Gentle','Affectionate','Sociable','Graceful','Adaptable'],
    bestFor:['Apartamentos','Apoyo emocional','Adultos mayores','Familias tranquilas'],
    bestForEn:['Apartments','Emotional support','Seniors','Calm families'],
    desc:'El Cavalier King Charles Spaniel es considerado el perro de compañía por excelencia. Criado para ser el perro de falda de la realeza inglesa, tiene un temperamento excepcionalmente gentil y cariñoso. Se adapta a cualquier hogar, ama a niños y adultos por igual, y tiene un instinto natural para brindar apoyo emocional.',
    descEn:'The Cavalier King Charles Spaniel is considered the quintessential companion dog. Bred to be the lap dog of English royalty, it has an exceptionally gentle and affectionate temperament. Adapts to any home, loves children and adults alike, and has a natural instinct for providing emotional support.',
    care:'Cepillado 3–4 veces por semana. Revisar orejas regularmente. Evitar calor excesivo.',
    careEn:'Brush 3–4 times weekly. Regular ear checks. Avoid excessive heat.',
    health:'Propenso a enfermedades cardíacas (MVD) y siringomielia. Comprar solo de criadores que realizan pruebas cardíacas.',
    healthEn:'Prone to heart disease (MVD) and syringomyelia. Only buy from breeders who do cardiac testing.',
    mixes:[
      {name:'Cavapoo', parents:'Cavalier KCS + Poodle', desc:'Muy popular. Bajo derramamiento, inteligente y con el temperamento gentil del Cavalier. Ideal para apoyo emocional.'},
      {name:'Cavachon', parents:'Cavalier KCS + Bichon Frisé', desc:'Dulce y juguetón. Pelaje suave y poco derramante. Excelente con niños.'},
    ]
  },
  {
    id:'dachshund', name:'Dachshund', es:'Dachshund (Teckel)', emoji:'🌭', photo:'fotos-razas/Dachshund.webp',
    size:'small', coat:['short','long','wiry'], hypo:false, energy:3, grooming:2, shedding:2,
    trainability:3, barking:3, family:4, kids:3, pets:3, apartment:4,
    origin:'Alemania', originEn:'Germany', flag:'🇩🇪',
    weight:'3.6–14.5 kg', height:'13–23 cm', lifespan:'12–16 años', akc:true, fci:true,
    temperament:['Curioso','Amigable','Atrevido','Obstinado','Cariñoso'],
    temperamentEn:['Curious','Friendly','Bold','Stubborn','Affectionate'],
    bestFor:['Apartamentos','Adultos','Familias sin niños muy pequeños'],
    bestForEn:['Apartments','Adults','Families without toddlers'],
    desc:'El Dachshund, también conocido como Teckel o "salchicha", fue criado en Alemania para cazar tejones en sus madrigueras. Su cuerpo largo y patas cortas son perfectos para meterse en túneles. Tiene una personalidad enorme, curiosa y a veces obstinada. Viene en dos tamaños (estándar y miniatura) y tres tipos de pelaje.',
    descEn:'The Dachshund, also known as "wiener dog," was bred in Germany to hunt badgers in their burrows. Its long body and short legs are perfect for entering tunnels. It has an enormous, curious, and sometimes stubborn personality. Comes in two sizes (standard and miniature) and three coat types.',
    care:'Vigilar el peso — la obesidad daña su columna. Evitar saltos altos. Cepillado según el tipo de pelaje.',
    careEn:'Monitor weight — obesity damages the spine. Avoid high jumps. Grooming depends on coat type.',
    health:'Propenso a DDIV (enfermedad del disco intervertebral). Clave mantener peso saludable.',
    healthEn:'Prone to IVDD (intervertebral disc disease). Maintaining healthy weight is key.',
    mixes:[
      {name:'Dorkie', parents:'Dachshund + Yorkshire Terrier', desc:'Pequeño y audaz. Hereda la curiosidad del Dachshund con la energía del Yorkie.'},
      {name:'Doxle', parents:'Dachshund + Beagle', desc:'Curioso y sociable. Excelente olfato heredado del Beagle con el temperamento del Dachshund.'},
    ]
  },
  {
    id:'boston-terrier', name:'Boston Terrier', es:'Boston Terrier', emoji:'🐶', photo:'fotos-razas/Boston Terrier.webp',
    size:'small', coat:['short'], hypo:false, energy:3, grooming:1, shedding:2,
    trainability:4, barking:2, family:5, kids:5, pets:4, apartment:5,
    origin:'Estados Unidos', originEn:'United States', flag:'🇺🇸',
    weight:'4.5–11 kg', height:'38–43 cm', lifespan:'11–13 años', akc:true, fci:true,
    temperament:['Amigable','Brillante','Divertido','Adaptable','Cariñoso'],
    temperamentEn:['Friendly','Bright','Amusing','Adaptable','Affectionate'],
    bestFor:['Apartamentos','Familias','Primeros dueños'],
    bestForEn:['Apartments','Families','First-time owners'],
    desc:'El Boston Terrier, conocido como el "Caballero Americano", es una de las pocas razas creadas en Estados Unidos. Con su esmoquin blanco y negro y sus enormes ojos expresivos, es el compañero perfecto para la vida urbana. Amigable, divertido y adaptable, se lleva bien con toda la familia.',
    descEn:'The Boston Terrier, known as the "American Gentleman," is one of the few breeds created in the United States. With its black and white tuxedo and huge expressive eyes, it\'s the perfect companion for city life. Friendly, amusing, and adaptable — gets along great with the whole family.',
    care:'Mínimo mantenimiento de pelaje. Limpiar pliegues faciales. Sensible al calor y al frío extremo.',
    careEn:'Minimal coat care. Clean facial folds. Sensitive to extreme heat and cold.',
    health:'Braquicéfalo — vigilar respiración. Propenso a cataratas y problemas articulares.',
    healthEn:'Brachycephalic — monitor breathing. Prone to cataracts and joint problems.',
    mixes:[
      {name:'Frenchton', parents:'French Bulldog + Boston Terrier', desc:'Lo mejor de dos mundos. Activo y robusto, con temperamento juguetón y amigable.'},
      {name:'Bossi-Poo', parents:'Boston Terrier + Poodle', desc:'Inteligente y bajo mantenimiento. Hereda el humor del Boston con la inteligencia del Poodle.'},
    ]
  },

  // ── MEDIUM ─────────────────────────────────────────────
  {
    id:'beagle', name:'Beagle', es:'Beagle', emoji:'🐕', photo:'fotos-razas/Beagle.webp',
    size:'medium', coat:['short'], hypo:false, energy:4, grooming:2, shedding:3,
    trainability:3, barking:4, family:5, kids:5, pets:4, apartment:3,
    origin:'Inglaterra', originEn:'England', flag:'🇬🇧',
    weight:'9–11 kg', height:'33–41 cm', lifespan:'10–15 años', akc:true, fci:true,
    temperament:['Amigable','Curioso','Determinado','Juguetón','Leal'],
    temperamentEn:['Friendly','Curious','Determined','Playful','Loyal'],
    bestFor:['Casas con patio','Familias con niños','Personas activas'],
    bestForEn:['Houses with yard','Families with kids','Active people'],
    desc:'El Beagle es uno de los perros de caza más populares y amados como mascota familiar. Con su nariz extraordinaria y su carácter sociable, es un compañero incansable para niños. Necesita ejercicio regular y estimulación mental. Tiende a seguir olores, por lo que un jardín cercado es ideal.',
    descEn:'The Beagle is one of the most popular hunting dogs and beloved as a family pet. With its extraordinary nose and sociable character, it\'s a tireless companion for children. Needs regular exercise and mental stimulation. Tends to follow scents, so a fenced yard is ideal.',
    care:'Ejercicio diario obligatorio. Revisar orejas regularmente para evitar infecciones. Vigilar el peso.',
    careEn:'Daily exercise essential. Check ears regularly to prevent infections. Monitor weight.',
    health:'Generalmente saludable. Vigilar epilepsia, problemas de tiroides y obesidad.',
    healthEn:'Generally healthy. Watch for epilepsy, thyroid issues, and obesity.',
    mixes:[
      {name:'Puggle', parents:'Beagle + Pug', desc:'Sociable y divertido. Menos propenso a problemas respiratorios que el Pug puro.'},
      {name:'Borkie', parents:'Beagle + Yorkshire Terrier', desc:'Curioso y energético. Hereda la nariz del Beagle con la personalidad del Yorkie.'},
      {name:'Beabull', parents:'Beagle + Bulldog', desc:'Gentil y resistente. Combina la curiosidad del Beagle con la calma del Bulldog.'},
    ]
  },
  {
    id:'cocker-spaniel', name:'Cocker Spaniel', es:'Cocker Spaniel', emoji:'🐶', photo:'fotos-razas/Cocker Spaniel.webp',
    size:'medium', coat:['long','smooth'], hypo:false, energy:3, grooming:4, shedding:3,
    trainability:4, barking:3, family:5, kids:5, pets:4, apartment:3,
    origin:'España / Inglaterra', originEn:'Spain / England', flag:'🇬🇧',
    weight:'9–14.5 kg', height:'36–43 cm', lifespan:'10–14 años', akc:true, fci:true,
    temperament:['Gentil','Cariñoso','Activo','Juguetón','Feliz'],
    temperamentEn:['Gentle','Affectionate','Active','Playful','Merry'],
    bestFor:['Familias con niños','Casas con patio','Personas activas'],
    bestForEn:['Families with kids','Houses with yard','Active people'],
    desc:'El Cocker Spaniel americano es conocido por sus hermosas orejas caídas y su expresión dulce. Excelente perro de familia, gentil con niños y muy afectuoso. Fue durante muchos años la raza más popular en Estados Unidos. Necesita ejercicio regular y cuidado frecuente de su pelaje largo y sedoso.',
    descEn:'The American Cocker Spaniel is known for its beautiful droopy ears and sweet expression. Excellent family dog, gentle with children and very affectionate. Was for many years the most popular breed in the United States. Needs regular exercise and frequent grooming of its long, silky coat.',
    care:'Cepillado diario. Visita al groomer cada 6–8 semanas. Limpieza regular de oídos para prevenir infecciones.',
    careEn:'Daily brushing. Groomer every 6–8 weeks. Regular ear cleaning to prevent infections.',
    health:'Propenso a problemas oculares (cataratas), infecciones de oído y problemas de cadera.',
    healthEn:'Prone to eye problems (cataracts), ear infections, and hip problems.',
    mixes:[
      {name:'Cockapoo', parents:'Cocker Spaniel + Poodle', desc:'Una de las primeras razas de diseño. Muy popular, bajo derramamiento, inteligente y cariñoso.'},
      {name:'Spangold', parents:'Cocker Spaniel + Golden Retriever', desc:'Afectuoso y activo. Hereda la lealtad del Golden con la elegancia del Cocker.'},
    ]
  },
  {
    id:'border-collie', name:'Border Collie', es:'Border Collie', emoji:'🐕', photo:'fotos-razas/Border Collie.webp',
    size:'medium', coat:['long','smooth'], hypo:false, energy:5, grooming:3, shedding:3,
    trainability:5, barking:3, family:4, kids:4, pets:3, apartment:1,
    origin:'Reino Unido', originEn:'United Kingdom', flag:'🇬🇧',
    weight:'12–20 kg', height:'46–56 cm', lifespan:'12–15 años', akc:true, fci:true,
    temperament:['Energético','Inteligente','Alerta','Receptivo','Trabajador'],
    temperamentEn:['Energetic','Intelligent','Alert','Responsive','Hard-working'],
    bestFor:['Casas con jardín grande','Familias muy activas','Personas con tiempo para entrenar'],
    bestForEn:['Houses with large yard','Very active families','People with time to train'],
    desc:'El Border Collie está considerado la raza más inteligente del mundo. Criado para arrear ovejas en la frontera entre Escocia e Inglaterra, necesita cantidades enormes de ejercicio y estimulación mental. No apto para apartamentos ni para personas con estilo de vida sedentario. Con el entrenamiento correcto, es extraordinario.',
    descEn:'The Border Collie is considered the world\'s most intelligent breed. Bred to herd sheep on the Scottish-English border, it needs enormous amounts of exercise and mental stimulation. Not suitable for apartments or sedentary lifestyles. With proper training, it is extraordinary.',
    care:'Ejercicio intenso diario (mínimo 2 horas). Entrenamiento y estimulación mental esenciales. Cepillado frecuente.',
    careEn:'Intensive daily exercise (minimum 2 hours). Training and mental stimulation essential. Frequent brushing.',
    health:'Generalmente saludable. Vigilar epilepsia, displasia de cadera y anomalía del ojo del Collie.',
    healthEn:'Generally healthy. Watch for epilepsy, hip dysplasia, and Collie eye anomaly.',
    mixes:[
      {name:'Bordoodle', parents:'Border Collie + Poodle', desc:'Altamente inteligente y bajo derramamiento. Para personas muy activas que buscan entrenar extensamente.'},
      {name:'Borador', parents:'Border Collie + Labrador', desc:'Amigable y energético. Más manejable que el Border puro pero igualmente inteligente.'},
    ]
  },
  {
    id:'english-bulldog', name:'English Bulldog', es:'Bulldog Inglés', emoji:'🐶', photo:'fotos-razas/English Bulldog.webp',
    size:'medium', coat:['short'], hypo:false, energy:2, grooming:2, shedding:3,
    trainability:3, barking:2, family:5, kids:5, pets:4, apartment:4,
    origin:'Inglaterra', originEn:'England', flag:'🇬🇧',
    weight:'18–25 kg', height:'31–40 cm', lifespan:'8–10 años', akc:true, fci:true,
    temperament:['Amigable','Valeroso','Calmado','Leal','Gentil'],
    temperamentEn:['Friendly','Courageous','Calm','Loyal','Gentle'],
    bestFor:['Apartamentos','Familias','Adultos mayores'],
    bestForEn:['Apartments','Families','Seniors'],
    desc:'El Bulldog Inglés es un ícono de la resistencia y la nobleza. A pesar de su apariencia intimidante, es uno de los perros más gentiles y afectuosos que existen. Ama a los niños, es tranquilo en interiores y requiere poco ejercicio. Su esperanza de vida más corta hace importante elegir criadores responsables.',
    descEn:'The English Bulldog is an icon of resilience and nobility. Despite its intimidating appearance, it is one of the gentlest and most affectionate dogs. Loves children, is calm indoors, and requires little exercise. Its shorter lifespan makes choosing responsible breeders especially important.',
    care:'Limpiar pliegues diariamente. Mínimo ejercicio pero paseos cortos regulares. Muy sensible al calor.',
    careEn:'Clean folds daily. Minimal exercise but regular short walks. Very heat sensitive.',
    health:'Propenso a problemas respiratorios, displasia de cadera y codera, problemas de piel.',
    healthEn:'Prone to breathing problems, hip and elbow dysplasia, skin problems.',
    mixes:[
      {name:'Bullador', parents:'Bulldog Inglés + Labrador', desc:'Más activo y saludable que el Bulldog puro. Temperamento gentil con más energía.'},
      {name:'Beabull', parents:'Bulldog Inglés + Beagle', desc:'Curioso y sociable. Combina la curiosidad del Beagle con la calma del Bulldog.'},
    ]
  },

  // ── LARGE ──────────────────────────────────────────────
  {
    id:'golden-retriever', name:'Golden Retriever', es:'Golden Retriever', emoji:'🦮', photo:'fotos-razas/Golden Retriever.webp',
    size:'large', coat:['long'], hypo:false, energy:4, grooming:3, shedding:4,
    trainability:5, barking:2, family:5, kids:5, pets:5, apartment:2,
    origin:'Escocia', originEn:'Scotland', flag:'🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    weight:'25–34 kg', height:'51–61 cm', lifespan:'10–12 años', akc:true, fci:true,
    temperament:['Confiable','Amistoso','Inteligente','Cariñoso','Paciente'],
    temperamentEn:['Reliable','Friendly','Intelligent','Affectionate','Patient'],
    bestFor:['Familias con niños','Apoyo emocional','Personas activas','Casas con patio'],
    bestForEn:['Families with kids','Emotional support','Active people','Houses with yard'],
    desc:'El Golden Retriever es uno de los perros más amados del mundo por su temperamento excepcional. Criado originalmente en Escocia como perro de caza, hoy brilla como perro de terapia, asistencia y compañía familiar. Es infinitamente paciente con los niños, fácil de entrenar y siempre alegre. Su sonrisa es inconfundible.',
    descEn:'The Golden Retriever is one of the world\'s most beloved dogs for its exceptional temperament. Originally bred in Scotland as a hunting dog, today it excels as a therapy, assistance, and family companion dog. Infinitely patient with children, easy to train, and always joyful. Its smile is unmistakable.',
    care:'Cepillado 2–3 veces por semana. Ejercicio diario moderado-alto. Vigilar peso y alimentación.',
    careEn:'Brush 2–3 times weekly. Moderate-high daily exercise. Monitor weight and diet.',
    health:'Propenso a displasia de cadera, cataratas y cáncer. Comprar de criadores con pruebas genéticas.',
    healthEn:'Prone to hip dysplasia, cataracts, and cancer. Buy from breeders with genetic testing.',
    mixes:[
      {name:'Goldendoodle', parents:'Golden Retriever + Poodle', desc:'Extremadamente popular. Bajo derramamiento, muy inteligente y con el carácter gentil del Golden.'},
      {name:'Goldador', parents:'Golden Retriever + Labrador', desc:'El perro de compañía definitivo. Combina lo mejor de dos razas excepcionales.'},
      {name:'Golden Husky (Goberian)', parents:'Golden Retriever + Husky', desc:'Impresionante combinación de apariencia. Activo y leal, necesita mucho ejercicio.'},
    ]
  },
  {
    id:'labrador-retriever', name:'Labrador Retriever', es:'Labrador Retriever', emoji:'🦮', photo:'fotos-razas/Labrador Retriever.webp',
    size:'large', coat:['short'], hypo:false, energy:4, grooming:2, shedding:4,
    trainability:5, barking:2, family:5, kids:5, pets:5, apartment:2,
    origin:'Canadá / Inglaterra', originEn:'Canada / England', flag:'🇨🇦',
    weight:'25–36 kg', height:'54–62 cm', lifespan:'10–12 años', akc:true, fci:true,
    temperament:['Amistoso','Activo','Amable','Confiable','Adaptable'],
    temperamentEn:['Friendly','Active','Kind','Trustworthy','Adaptable'],
    bestFor:['Familias con niños','Guía/asistencia','Personas muy activas','Casas con patio'],
    bestForEn:['Families with kids','Guide/assistance','Very active people','Houses with yard'],
    desc:'El Labrador Retriever ha sido la raza más popular de Estados Unidos durante más de 30 años consecutivos. Es el perro de servicio por excelencia: guía para ciegos, asistencia, detección de drogas y terapia. Su carácter amable, activo y siempre dispuesto a complacer lo hace el compañero familiar ideal.',
    descEn:'The Labrador Retriever has been the most popular breed in the United States for over 30 consecutive years. It is the ultimate service dog: guide for the blind, assistance, drug detection, and therapy. Its kind, active, and always eager-to-please character makes it the ideal family companion.',
    care:'Ejercicio intenso diario. Cepillado frecuente en época de muda. Muy propenso a comer en exceso.',
    careEn:'Intense daily exercise. Frequent brushing during shedding season. Very prone to overeating.',
    health:'Vigilar displasia de cadera y codo, obesidad y problemas oculares hereditarios.',
    healthEn:'Watch for hip and elbow dysplasia, obesity, and hereditary eye problems.',
    mixes:[
      {name:'Labradoodle', parents:'Labrador + Poodle', desc:'Popular perro de servicio y familia. Bajo derramamiento, inteligente y de excelente temperamento.'},
      {name:'Huskador', parents:'Labrador + Husky Siberiano', desc:'Enérgico y leal. Necesita ejercicio intenso. Hermosa combinación de ambas razas.'},
      {name:'Bullador', parents:'Labrador + Bulldog', desc:'Más tranquilo que el Lab puro. Temperamento equilibrado, ideal para familias.'},
    ]
  },
  {
    id:'german-shepherd', name:'German Shepherd', es:'Pastor Alemán', emoji:'🐕‍🦺', photo:'fotos-razas/German Shepherd.webp',
    size:'large', coat:['long','smooth'], hypo:false, energy:4, grooming:3, shedding:5,
    trainability:5, barking:3, family:5, kids:5, pets:3, apartment:2,
    origin:'Alemania', originEn:'Germany', flag:'🇩🇪',
    weight:'22–40 kg', height:'55–65 cm', lifespan:'9–13 años', akc:true, fci:true,
    temperament:['Confiado','Valiente','Inteligente','Leal','Obediente'],
    temperamentEn:['Confident','Courageous','Intelligent','Loyal','Obedient'],
    bestFor:['Familias activas','Personas con experiencia','Casas con patio','Seguridad'],
    bestForEn:['Active families','Experienced owners','Houses with yard','Security'],
    desc:'El Pastor Alemán es una de las razas más versátiles e inteligentes del mundo. Usado en policía, ejército, búsqueda y rescate, y como perro de servicio. Es extremadamente leal a su familia y excelente guardián. Necesita socialización temprana y un dueño con experiencia que establezca liderazgo claro.',
    descEn:'The German Shepherd is one of the world\'s most versatile and intelligent breeds. Used in police, military, search and rescue, and as a service dog. Extremely loyal to its family and an excellent guardian. Needs early socialization and an experienced owner who establishes clear leadership.',
    care:'Ejercicio intenso diario. Cepillado frecuente — muda abundante dos veces al año. Entrenamiento temprano crucial.',
    careEn:'Intense daily exercise. Frequent brushing — heavy shedding twice a year. Early training crucial.',
    health:'Propenso a displasia de cadera y codo. Buscar líneas de criadores con certificaciones de salud.',
    healthEn:'Prone to hip and elbow dysplasia. Seek breeders with health certifications.',
    mixes:[
      {name:'Sheprador', parents:'German Shepherd + Labrador', desc:'Leal y amigable. Combina la inteligencia del Pastor con la sociabilidad del Labrador.'},
      {name:'Gerberian Shepsky', parents:'German Shepherd + Husky', desc:'Impresionante y enérgico. Para personas muy activas con experiencia canina.'},
    ]
  },
  {
    id:'siberian-husky', name:'Siberian Husky', es:'Husky Siberiano', emoji:'🐺', photo:'fotos-razas/Siberian Husky.webp',
    size:'large', coat:['long'], hypo:false, energy:5, grooming:3, shedding:5,
    trainability:3, barking:2, family:4, kids:4, pets:3, apartment:1,
    origin:'Siberia (Rusia)', originEn:'Siberia (Russia)', flag:'🇷🇺',
    weight:'16–27 kg', height:'51–60 cm', lifespan:'12–14 años', akc:true, fci:true,
    temperament:['Extrovertido','Energético','Independiente','Amistoso','Leal'],
    temperamentEn:['Outgoing','Energetic','Independent','Friendly','Loyal'],
    bestFor:['Personas muy activas','Climas fríos','Casas con jardín grande'],
    bestForEn:['Very active people','Cold climates','Houses with large yard'],
    desc:'El Husky Siberiano fue criado por el pueblo Chukchi de Siberia para tirar trineos durante siglos. Sus ojos azules o multicolores y su denso pelaje son icónicos. Es un perro de manada que necesita compañía constante y ejercicio intenso. Muy independiente — requiere dueños con experiencia y mucho tiempo.',
    descEn:'The Siberian Husky was bred by the Chukchi people of Siberia to pull sleds for centuries. Its blue or multicolored eyes and dense coat are iconic. It is a pack dog that needs constant companionship and intense exercise. Very independent — requires experienced owners with lots of time.',
    care:'Ejercicio intenso diario (mínimo 2 horas). Cepillado intenso en épocas de muda. Nunca dejar suelto sin cercado.',
    careEn:'Intense daily exercise (minimum 2 hours). Heavy brushing during shedding seasons. Never leave unleashed without fencing.',
    health:'Generalmente saludable. Vigilar displasia de cadera, cataratas hereditarias y problemas de tiroides.',
    healthEn:'Generally healthy. Watch for hip dysplasia, hereditary cataracts, and thyroid issues.',
    mixes:[
      {name:'Pomsky', parents:'Pomeranian + Husky Siberiano', desc:'Tamaño manejable con la apariencia del Husky. Alta demanda. Requiere ejercicio regular.'},
      {name:'Huskador', parents:'Husky + Labrador', desc:'Más amigable y manejable que el Husky puro. Enérgico y leal.'},
      {name:'Gerberian Shepsky', parents:'Husky + Pastor Alemán', desc:'Inteligente y enérgico. Para personas muy activas con experiencia.'},
    ]
  },
  {
    id:'standard-poodle', name:'Standard Poodle', es:'Caniche Estándar', emoji:'🐩', photo:'fotos-razas/Standard Poodle.webp',
    size:'large', coat:['curly'], hypo:true, energy:4, grooming:5, shedding:1,
    trainability:5, barking:2, family:5, kids:5, pets:5, apartment:3,
    origin:'Francia / Alemania', originEn:'France / Germany', flag:'🇫🇷',
    weight:'20–32 kg', height:'45–70 cm', lifespan:'12–15 años', akc:true, fci:true,
    temperament:['Activo','Instintivo','Adaptable','Inteligente','Elegante'],
    temperamentEn:['Active','Instinctual','Adaptable','Intelligent','Elegant'],
    bestFor:['Personas con alergias','Familias activas','Deporte canino','Apoyo emocional'],
    bestForEn:['People with allergies','Active families','Dog sports','Emotional support'],
    desc:'El Caniche Estándar es el perro más inteligente del mundo según muchos expertos, superado solo por el Border Collie. Hipoalergénico con muy poco derramamiento. Es atlético, elegante y excepcionalmente versátil. El padre de muchas de las razas de diseño más populares (Goldendoodle, Labradoodle, Cavapoo, etc.).',
    descEn:'The Standard Poodle is considered the world\'s most intelligent dog by many experts, only surpassed by the Border Collie. Hypoallergenic with very little shedding. Athletic, elegant, and exceptionally versatile. The parent of many of the most popular designer breeds (Goldendoodle, Labradoodle, Cavapoo, etc.).',
    care:'Grooming profesional cada 6–8 semanas. Cepillado regular para evitar nudos. Ejercicio diario moderado-alto.',
    careEn:'Professional grooming every 6–8 weeks. Regular brushing to prevent matting. Moderate-high daily exercise.',
    health:'Generalmente saludable. Vigilar displasia de cadera, problemas oculares hereditarios y dilatación gástrica.',
    healthEn:'Generally healthy. Watch for hip dysplasia, hereditary eye problems, and gastric dilation.',
    mixes:[
      {name:'Goldendoodle', parents:'Golden Retriever + Standard Poodle', desc:'La mezcla más popular. Bajo derramamiento, inteligente y de carácter excepcional.'},
      {name:'Labradoodle', parents:'Labrador + Standard Poodle', desc:'Origen como perro de servicio hipoalergénico. Inteligente y de excelente temperamento.'},
      {name:'Bernedoodle', parents:'Bernese Mountain Dog + Poodle', desc:'Leal y gentil. Combina el pelaje del Bernese con el bajo derramamiento del Poodle.'},
    ]
  },
];

// ── DESIGNER BREEDS ────────────────────────────────────────
const DESIGNER_BREEDS = [
  { id:'goldendoodle', name:'Goldendoodle', parents:'Golden Retriever + Standard Poodle', emoji:'🐩', photo:'fotos-razas/Goldendoodle.webp',
    size:'medium-large', coat:['curly','wavy'], hypo:true, energy:4,
    desc:'La mezcla de diseño más popular en EE. UU. Hereda la inteligencia y el bajo derramamiento del Poodle con el carácter gentil e incondicional del Golden Retriever. Ideal para familias, personas con alergias y como perro de apoyo emocional. Viene en varios tamaños según el tipo de Poodle.',
    descEn:'The most popular designer mix in the U.S. Inherits the intelligence and low shedding of the Poodle with the gentle, unconditional character of the Golden Retriever. Ideal for families, allergy sufferers, and as an emotional support dog. Available in various sizes depending on the Poodle type.'},
  { id:'labradoodle', name:'Labradoodle', parents:'Labrador Retriever + Poodle', emoji:'🐩', photo:'fotos-razas/Labradoodle.webp',
    size:'medium-large', coat:['curly','wavy'], hypo:true, energy:4,
    desc:'Originalmente creado en Australia como perro guía hipoalergénico. Combina la obediencia y sociabilidad del Labrador con el bajo derramamiento del Poodle. Excelente perro de servicio y compañía familiar.',
    descEn:'Originally created in Australia as a hypoallergenic guide dog. Combines the obedience and sociability of the Labrador with the low shedding of the Poodle. Excellent service dog and family companion.'},
  { id:'cavapoo', name:'Cavapoo', parents:'Cavalier King Charles + Miniature Poodle', emoji:'🐶', photo:'fotos-razas/Cavapoo.webp',
    size:'small', coat:['curly','wavy'], hypo:true, energy:3,
    desc:'Dulce, gentil y de bajo mantenimiento. Hereda el temperamento cariñoso del Cavalier con el bajo derramamiento del Poodle. Ideal para apoyo emocional, adultos mayores y apartamentos.',
    descEn:'Sweet, gentle, and low maintenance. Inherits the affectionate temperament of the Cavalier with the low shedding of the Poodle. Ideal for emotional support, seniors, and apartments.'},
  { id:'maltipoo', name:'Maltipoo', parents:'Maltese + Miniature Poodle', emoji:'🐩', photo:'fotos-razas/Maltipoo.webp',
    size:'small', coat:['curly','wavy'], hypo:true, energy:3,
    desc:'Pequeño, adorable e hipoalergénico. Muy popular para personas con alergias. Cariñoso y sociable, se adapta perfectamente a apartamentos y hogares tranquilos.',
    descEn:'Small, adorable, and hypoallergenic. Very popular for people with allergies. Affectionate and sociable, perfectly adapted to apartments and quiet homes.'},
  { id:'shorkie', name:'Shorkie', parents:'Shih Tzu + Yorkshire Terrier', emoji:'🐶',
    size:'small', coat:['long','silky'], hypo:false, energy:3,
    desc:'Pelaje sedoso y carácter juguetón. Combina la dulzura del Shih Tzu con la energía del Yorkie. Poco derramante, ideal para apartamentos.',
    descEn:'Silky coat and playful character. Combines the sweetness of the Shih Tzu with the energy of the Yorkie. Low shedding, ideal for apartments.'},
  { id:'morkie', name:'Morkie', parents:'Maltese + Yorkshire Terrier', emoji:'🐶',
    size:'small', coat:['long','silky'], hypo:false, energy:3,
    desc:'Pelaje largo y suave, temperamento cariñoso y adaptable. Muy sociable. Ideal para adultos y familias sin niños muy pequeños.',
    descEn:'Long, soft coat, affectionate and adaptable temperament. Very sociable. Ideal for adults and families without very young children.'},
  { id:'pomsky', name:'Pomsky', parents:'Pomeranian + Siberian Husky', emoji:'🐺', photo:'fotos-razas/Pomsky.webp',
    size:'small-medium', coat:['long'], hypo:false, energy:4,
    desc:'Alta demanda por su apariencia de Husky en miniatura. Enérgico, inteligente y de fuerte personalidad. Requiere ejercicio regular y socialización temprana.',
    descEn:'High demand for its miniature Husky appearance. Energetic, intelligent, and strong-willed. Requires regular exercise and early socialization.'},
  { id:'frenchton', name:'Frenchton', parents:'French Bulldog + Boston Terrier', emoji:'🐶',
    size:'small', coat:['short'], hypo:false, energy:3,
    desc:'Más activo y saludable que el French Bulldog puro. Mejor tolerancia al calor. Temperamento juguetón y muy sociable. Excelente para apartamentos y familias.',
    descEn:'More active and healthier than a pure French Bulldog. Better heat tolerance. Playful temperament and very sociable. Excellent for apartments and families.'},
  { id:'schnoodle', name:'Schnoodle', parents:'Schnauzer + Poodle', emoji:'🐩',
    size:'small-medium', coat:['curly','wiry'], hypo:true, energy:3,
    desc:'Inteligente, sin derramamiento y con carácter equilibrado. Hereda la lealtad del Schnauzer y la inteligencia del Poodle. Excelente perro de familia.',
    descEn:'Intelligent, non-shedding, and balanced character. Inherits the loyalty of the Schnauzer and the intelligence of the Poodle. Excellent family dog.'},
  { id:'shichon', name:'Shichon (Teddy Bear)', parents:'Shih Tzu + Bichon Frisé', emoji:'🧸',
    size:'small', coat:['curly','soft'], hypo:true, energy:2,
    desc:'Conocido como "Teddy Bear" por su apariencia adorable. Gentil, sociable y de bajo mantenimiento. Casi sin derramamiento. Ideal para personas mayores y familias tranquilas.',
    descEn:'Known as "Teddy Bear" for its adorable appearance. Gentle, sociable, and low maintenance. Almost no shedding. Ideal for seniors and calm families.'},
];

// ── MESTIZOS / MIXED ───────────────────────────────────────
const MESTIZO_INFO = {
  title: ['Perros Mestizos', 'Mixed Breed Dogs'],
  desc: ['Los perros mestizos son una combinación única de varias razas. Suelen tener excelente salud gracias a la "heterosis" (vigor híbrido), temperamentos equilibrados y personalidades únicas. Cada perro mestizo es irrepetible. La mayoría se encuentran en refugios locales esperando un hogar amoroso.',
         'Mixed breed dogs are a unique combination of several breeds. They often have excellent health thanks to "heterosis" (hybrid vigor), balanced temperaments, and unique personalities. Each mixed breed dog is one of a kind. Most are found in local shelters waiting for a loving home.'],
  link: '/adopciones',
};

const ALL_SIZES = ['small','medium','large'];
const ALL_COATS = ['short','long','curly','smooth','wiry','hairless'];

Object.assign(window, { DOG_BREEDS, DESIGNER_BREEDS, MESTIZO_INFO, ALL_SIZES, ALL_COATS });
