// breed-trivia.js — Datos curiosos, dueños famosos y curiosidades por raza.
// Se fusiona por id en DOG_BREEDS / CAT_BREEDS (cargado después de breed-data / cat-breed-data).
(function () {
  var DOG_TRIVIA = {
    'french-bulldog': {
      funFacts: ['No pueden nadar bien: su cuerpo pesado y cara chata se lo impiden.', 'Casi siempre nacen por cesárea por su cabeza grande.', 'Son una de las razas que más "hablan" con gruñidos y bostezos graciosos.'],
      funFactsEn: ['They can\'t really swim: their heavy body and flat face make it hard.', 'They are almost always born by C-section due to their large heads.', 'One of the most "talkative" breeds, with funny grunts and yawns.'],
      famous: ['Lady Gaga', 'Dwayne "The Rock" Johnson', 'Hugh Jackman', 'Reese Witherspoon'],
      curiosity: 'Fue el perro de moda entre las costureras del Londres victoriano antes de conquistar París, donde recibió su nombre.',
      curiosityEn: 'It was the favorite of Victorian London lacemakers before conquering Paris, where it got its name.',
    },
    'golden-retriever': {
      funFacts: ['Tienen "boca blanda": pueden cargar un huevo sin romperlo.', 'Fueron criados en Escocia para recuperar presas en agua y tierra.', 'Su cola no para de moverse: es de las razas más expresivas.'],
      funFactsEn: ['They have a "soft mouth": they can carry an egg without breaking it.', 'Bred in Scotland to retrieve game on water and land.', 'Their tail never stops wagging — one of the most expressive breeds.'],
      famous: ['Oprah Winfrey', 'Adam Levine', 'Jimmy Fallon'],
      curiosity: 'Son de los mejores perros de terapia y asistencia del mundo gracias a su paciencia infinita.',
      curiosityEn: 'They are among the best therapy and service dogs in the world thanks to their endless patience.',
    },
    'labrador-retriever': {
      funFacts: ['Son la raza #1 más popular de EE. UU. por décadas.', 'Tienen patas semipalmeadas: nadadores natos.', 'Su nariz puede detectar olores que ningún aparato humano detecta.'],
      funFactsEn: ['They\'ve been the #1 most popular breed in the U.S. for decades.', 'They have semi-webbed feet — natural swimmers.', 'Their nose can detect scents no human device can.'],
      famous: ['Príncipe Guillermo y Kate', 'Bill Clinton (su Lab "Buddy")', 'Anne Hathaway'],
      famousEn: ['Prince William & Kate', 'Bill Clinton (his Lab "Buddy")', 'Anne Hathaway'],
      curiosity: 'Vienen en tres colores (negro, chocolate y dorado) y pueden nacer los tres en la misma camada.',
      curiosityEn: 'They come in three colors (black, chocolate, yellow) and all three can appear in one litter.',
    },
    'german-shepherd': {
      funFacts: ['Es el perro policía y militar más usado del mundo.', 'Aprende órdenes nuevas en menos de 5 repeticiones.', 'La estrella de cine Rin Tin Tin era un Pastor Alemán rescatado en la I Guerra Mundial.'],
      funFactsEn: ['It\'s the most widely used police and military dog in the world.', 'Learns new commands in fewer than 5 repetitions.', 'Movie star Rin Tin Tin was a German Shepherd rescued in WWI.'],
      famous: ['Jake Gyllenhaal', 'Claudia Schiffer', 'Rin Tin Tin'],
      curiosity: 'Fue creado por un solo hombre, el capitán Max von Stephanitz, con la idea del "perro de utilidad perfecto".',
      curiosityEn: 'It was created by one man, Captain Max von Stephanitz, with the idea of the "perfect utility dog".',
    },
    'standard-poodle': {
      funFacts: ['Está entre las 2 razas más inteligentes del mundo.', 'El corte "pompón" nació para protegerle las articulaciones al nadar.', 'Casi no suelta pelo: ideal para alérgicos.'],
      funFactsEn: ['Ranked among the 2 smartest breeds in the world.', 'The "pom-pom" cut was created to protect its joints while swimming.', 'Barely sheds — great for allergy sufferers.'],
      famous: ['Rihanna', 'Walt Disney', 'Jackie Kennedy'],
      curiosity: 'Aunque hoy parece elegante, fue criado en Alemania como perro cazador de patos en el agua.',
      curiosityEn: 'Though it looks elegant today, it was bred in Germany as a water duck-hunting dog.',
    },
    'beagle': {
      funFacts: ['Tiene unos 220 millones de receptores de olor (los humanos, 5 millones).', 'Snoopy, el personaje más famoso del cómic, es un Beagle.', 'Su "aullido" especial se llama "baying".'],
      funFactsEn: ['Has around 220 million scent receptors (humans have 5 million).', 'Snoopy, the famous comic character, is a Beagle.', 'Their special howl is called "baying".'],
      famous: ['Snoopy', 'Lyndon B. Johnson', 'Barry Manilow'],
      curiosity: 'Su olfato es tan bueno que trabajan en aeropuertos detectando comida y plantas prohibidas.',
      curiosityEn: 'Their nose is so good they work in airports detecting banned food and plants.',
    },
    'chihuahua': {
      funFacts: ['Es la raza de perro más pequeña del mundo.', 'Nacen con una "mollera" blanda en el cráneo, como los bebés.', 'Viven hasta 16–18 años, de las más longevas.'],
      funFactsEn: ['The smallest dog breed in the world.', 'They\'re born with a soft spot on the skull, like babies.', 'They live 16–18 years, among the longest-lived.'],
      famous: ['Paris Hilton', 'Marilyn Monroe', 'Madonna'],
      curiosity: 'Lleva el nombre del estado mexicano de Chihuahua, donde fue redescubierto en el siglo XIX.',
      curiosityEn: 'Named after the Mexican state of Chihuahua, where it was rediscovered in the 1800s.',
    },
    'pomeranian': {
      funFacts: ['Desciende de grandes perros de trineo, ¡aunque no lo parezca!', 'La reina Victoria los puso de moda al criar ejemplares cada vez más pequeños.', 'Dos Pomerania sobrevivieron al hundimiento del Titanic.'],
      funFactsEn: ['Descends from large sled dogs — hard to believe!', 'Queen Victoria made them popular by breeding ever-smaller ones.', 'Two Pomeranians survived the sinking of the Titanic.'],
      famous: ['Reina Victoria', 'Boo "el perro más lindo del mundo"', 'Nicole Richie'],
      famousEn: ['Queen Victoria', 'Boo "the world\'s cutest dog"', 'Nicole Richie'],
      curiosity: 'Mozart y Miguel Ángel también tuvieron Pomeranias como compañeros.',
      curiosityEn: 'Mozart and Michelangelo also kept Pomeranians as companions.',
    },
    'yorkshire-terrier': {
      funFacts: ['Su pelo tiene textura de cabello humano y casi no suelta.', 'Nació para cazar ratas en fábricas y minas de Inglaterra.', 'Smoky, una Yorkie, fue heroína de guerra en la II Guerra Mundial.'],
      funFactsEn: ['Their coat has a human-hair texture and barely sheds.', 'Bred to hunt rats in England\'s mills and mines.', 'Smoky, a Yorkie, was a WWII war hero.'],
      famous: ['Audrey Hepburn', 'Missy Elliott', 'Whitney Houston'],
      curiosity: 'Pasó de perro obrero de clase trabajadora a símbolo de lujo victoriano en pocas décadas.',
      curiosityEn: 'It went from working-class ratter to Victorian luxury symbol in just a few decades.',
    },
    'dachshund': {
      funFacts: ['"Dachshund" significa "perro tejón": fue criado para cazarlos bajo tierra.', 'Su cuerpo largo le dio el apodo de "perro salchicha".', 'Fue la primera mascota oficial de unos Juegos Olímpicos (Múnich 1972, "Waldi").'],
      funFactsEn: ['"Dachshund" means "badger dog": bred to hunt them underground.', 'Its long body earned it the "sausage dog" nickname.', 'It was the first official Olympic mascot (Munich 1972, "Waldi").'],
      famous: ['Pablo Picasso (su "Lump")', 'Andy Warhol', 'David Hockney'],
      famousEn: ['Pablo Picasso (his "Lump")', 'Andy Warhol', 'David Hockney'],
      curiosity: 'Picasso dibujó a su Dachshund "Lump" en varias de sus obras.',
      curiosityEn: 'Picasso drew his Dachshund "Lump" in several of his works.',
    },
    'siberian-husky': {
      funFacts: ['Pueden correr más de 150 km en un día tirando de un trineo.', 'Sus ojos pueden ser de dos colores distintos (heterocromía).', 'No ladran casi nada, pero "cantan" y aúllan mucho.'],
      funFactsEn: ['They can run over 150 km in a day pulling a sled.', 'Their eyes can be two different colors (heterochromia).', 'They barely bark, but they "sing" and howl a lot.'],
      famous: ['Balto y Togo (héroes de Alaska)', 'Ben Stiller', 'Rita Ora'],
      famousEn: ['Balto and Togo (Alaskan heroes)', 'Ben Stiller', 'Rita Ora'],
      curiosity: 'En 1925, equipos de Huskies llevaron medicina a través de Alaska para frenar una epidemia: hoy se recuerda en la carrera Iditarod.',
      curiosityEn: 'In 1925, Husky teams relayed medicine across Alaska to stop an epidemic — remembered today in the Iditarod race.',
    },
    'cavalier-kcs': {
      funFacts: ['Lleva el nombre del rey Carlos II de Inglaterra, que adoraba la raza.', 'Es de los perros falderos más cariñosos que existen.', 'Adora seguir a su humano de cuarto en cuarto.'],
      funFactsEn: ['Named after King Charles II of England, who adored the breed.', 'One of the most affectionate lap dogs there is.', 'Loves following its human from room to room.'],
      famous: ['Frank Sinatra', 'Ronald Reagan', 'Rey Carlos II'],
      famousEn: ['Frank Sinatra', 'Ronald Reagan', 'King Charles II'],
      curiosity: 'Se decía que estos perros se permitían en cualquier edificio público de Inglaterra, ¡incluido el Parlamento!',
      curiosityEn: 'These dogs were reportedly allowed in any public building in England — even Parliament!',
    },
    'pug': {
      funFacts: ['Su nombre en latín, "multum in parvo", significa "mucho en poco espacio".', 'Un grupo de Pugs se llama "a grumble" (un gruñido).', 'Fueron mascotas de los emperadores chinos durante siglos.'],
      funFactsEn: ['Their motto in Latin, "multum in parvo", means "a lot in a little".', 'A group of Pugs is called "a grumble".', 'They were companions to Chinese emperors for centuries.'],
      famous: ['Reina Victoria', 'Gerard Butler', 'Jessica Alba'],
      famousEn: ['Queen Victoria', 'Gerard Butler', 'Jessica Alba'],
      curiosity: 'Un Pug llamado Pompey salvó la vida del príncipe Guillermo de Orange al alertarlo de un ataque enemigo.',
      curiosityEn: 'A Pug named Pompey saved Prince William of Orange by alerting him to an enemy attack.',
    },
    'shiba-inu': {
      funFacts: ['Es la raza detrás del famoso meme "Doge" y de la cripto Dogecoin.', 'Se limpian solos como los gatos.', 'Hacen el "Shiba scream", un grito agudo cuando se emocionan o enojan.'],
      funFactsEn: ['It\'s the breed behind the famous "Doge" meme and Dogecoin.', 'They groom themselves like cats.', 'They do the "Shiba scream", a high-pitched yell when excited or upset.'],
      famous: ['Kabosu (la cara del meme Doge)', 'Crusoe', 'Bunko'],
      famousEn: ['Kabosu (the face of the Doge meme)', 'Crusoe', 'Bunko'],
      curiosity: 'Es la raza más antigua y popular de Japón; casi se extingue tras la II Guerra Mundial.',
      curiosityEn: 'It\'s Japan\'s oldest and most popular breed; it nearly went extinct after WWII.',
    },
    'rottweiler': {
      funFacts: ['Acompañaban a las legiones romanas arreando ganado por los Alpes.', 'Su nombre viene de Rottweil, una ciudad medieval alemana.', 'Son de los perros más fuertes: protectores y leales con su familia.'],
      funFactsEn: ['They accompanied Roman legions herding cattle across the Alps.', 'Their name comes from Rottweil, a medieval German town.', 'Among the strongest dogs — protective and loyal to family.'],
      famous: ['Will Smith', 'Bruno Mars', 'Leonardo DiCaprio'],
      curiosity: 'Fueron de los primeros perros guía y hoy trabajan en rescate y como perros policía.',
      curiosityEn: 'They were among the first guide dogs and today work in search-and-rescue and police K9 units.',
    },
    'boston-terrier': {
      funFacts: ['Lo apodan "el caballero americano" por su esmoquin blanco y negro.', 'Es una de las pocas razas 100% originarias de EE. UU.', 'Es la mascota oficial del estado de Massachusetts.'],
      funFactsEn: ['Nicknamed "the American Gentleman" for its black-and-white tuxedo.', 'One of the few breeds 100% originated in the U.S.', 'It\'s the official state dog of Massachusetts.'],
      famous: ['Helen Keller (su Boston "Phiz")', 'Rose McGowan', 'Robin Williams'],
      famousEn: ['Helen Keller (her Boston "Phiz")', 'Rose McGowan', 'Robin Williams'],
      curiosity: 'Helen Keller recibió uno de los primeros Akita del mundo, pero su perro del día a día fue un Boston Terrier.',
      curiosityEn: 'Helen Keller received one of the first Akitas in the world, but her everyday dog was a Boston Terrier.',
    },
  };

  var CAT_TRIVIA = {
    'persian': {
      funFacts: ['Es el gato de raza más popular del mundo desde hace más de un siglo.', 'Su cara plana hace que sus ojos lagrimeen: hay que limpiarlos a diario.', 'Prefieren quedarse en el suelo: no son grandes saltadores.'],
      funFactsEn: ['It\'s been the world\'s most popular pedigreed cat for over a century.', 'Its flat face makes the eyes water — needs daily cleaning.', 'They prefer staying on the ground — not big jumpers.'],
      famous: ['Florence Nightingale', 'Marilyn Monroe', 'Raymond Chandler'],
      curiosity: 'Llegó a Europa desde Persia en el siglo XVII y fue favorito de la realeza, incluida la reina Victoria.',
      curiosityEn: 'It reached Europe from Persia in the 1600s and was a royal favorite, including Queen Victoria.',
    },
    'siamese': {
      funFacts: ['Son de los gatos más "habladores": mantienen conversaciones contigo.', 'Sus puntos oscuros aparecen en las zonas más frías del cuerpo.', 'Los gatitos nacen totalmente blancos y el color llega con los días.'],
      funFactsEn: ['Among the most "talkative" cats — they hold conversations with you.', 'Their dark points appear on the coolest parts of the body.', 'Kittens are born all white; color develops over days.'],
      famous: ['Si y Am (La Dama y el Vagabundo)', 'James Dean', 'Syd Barrett'],
      famousEn: ['Si and Am (Lady and the Tramp)', 'James Dean', 'Syd Barrett'],
      curiosity: 'Eran gatos sagrados en los templos de Tailandia (antiguo Siam) y se creía que guardaban las almas de la realeza.',
      curiosityEn: 'They were sacred temple cats in Thailand (old Siam), believed to guard the souls of royalty.',
    },
    'maine-coon': {
      funFacts: ['Es la raza de gato doméstico más grande: ¡hasta 1.2 m de largo!', 'Muchos adoran el agua y saben "hablar" con trinos.', 'Tienen pelo extra entre los dedos, como raquetas para la nieve.'],
      funFactsEn: ['The largest domestic cat breed — up to 1.2 m long!', 'Many love water and "talk" with chirps and trills.', 'They have extra fur between their toes, like snowshoes.'],
      famous: ['Stewie (récord Guinness al más largo)', 'Ricky Gervais'],
      famousEn: ['Stewie (Guinness record for longest)', 'Ricky Gervais'],
      curiosity: 'Es el gato oficial del estado de Maine y hay leyendas (falsas pero divertidas) de que es mitad mapache.',
      curiosityEn: 'It\'s the official state cat of Maine, with fun (false) legends that it\'s part raccoon.',
    },
    'bengal': {
      funFacts: ['Su pelaje brilla como si tuviera purpurina ("glitter").', 'Muchos aman el agua y juegan en la ducha.', 'Descienden del cruce con el gato leopardo asiático.'],
      funFactsEn: ['Their coat shimmers as if dusted with glitter.', 'Many love water and play in the shower.', 'They descend from crosses with the Asian leopard cat.'],
      famous: ['Kristin Stewart', 'Ian Somerhalder'],
      curiosity: 'Parecen pequeños leopardos, pero su carácter es de gato doméstico muy juguetón y atlético.',
      curiosityEn: 'They look like tiny leopards, but their temperament is that of a very playful, athletic house cat.',
    },
    'ragdoll': {
      funFacts: ['Se quedan "flojitos" como un muñeco de trapo cuando los cargas: de ahí su nombre.', 'Suelen recibirte en la puerta como un perro.', 'Sus ojos azules son una de sus marcas registradas.'],
      funFactsEn: ['They go limp like a rag doll when you hold them — hence the name.', 'They often greet you at the door like a dog.', 'Their blue eyes are a trademark.'],
      famous: ['Taylor Swift (fan de gatos)', 'Ed Sheeran'],
      curiosity: 'Fue desarrollado en California en los años 60 buscando un gato dócil, grande y muy apegado a las personas.',
      curiosityEn: 'It was developed in 1960s California, aiming for a docile, large, very people-attached cat.',
    },
    'british-shorthair': {
      funFacts: ['Inspiró al Gato de Cheshire de "Alicia en el País de las Maravillas".', 'Es el gato del famoso anuncio de Whiskas.', 'Su cuerpo redondo y mejillas le dan cara de peluche permanente.'],
      funFactsEn: ['It inspired the Cheshire Cat in "Alice in Wonderland".', 'It\'s the cat from the famous Whiskas ads.', 'Its round body and cheeks give it a permanent plush-toy face.'],
      famous: ['El Gato de Cheshire', 'Gato de Whiskas'],
      famousEn: ['The Cheshire Cat', 'The Whiskas cat'],
      curiosity: 'Es una de las razas de gato más antiguas; llegó a Gran Bretaña con los romanos.',
      curiosityEn: 'One of the oldest cat breeds; it arrived in Britain with the Romans.',
    },
    'sphynx': {
      funFacts: ['No es 100% calvo: tiene una pelusa suave como un durazno.', 'Necesita baños porque su piel acumula grasa.', 'Busca calor constante: adora las cobijas y tu regazo.'],
      funFactsEn: ['It\'s not 100% bald — it has a soft peach-fuzz coat.', 'Needs baths because its skin builds up oils.', 'Constantly seeks warmth — loves blankets and your lap.'],
      famous: ['Mr. Bigglesworth (Austin Powers)', 'Steven Tyler'],
      curiosity: 'La falta de pelo viene de una mutación natural aparecida en Canadá en 1966.',
      curiosityEn: 'Its hairlessness comes from a natural mutation that appeared in Canada in 1966.',
    },
    'scottish-fold': {
      funFacts: ['Sus orejitas dobladas vienen de una mutación natural.', 'Adoptan la "pose de Buda", sentados con la barriga al aire.', 'Nacen con orejas rectas; se doblan a las pocas semanas.'],
      funFactsEn: ['Their folded ears come from a natural mutation.', 'They adopt the "Buddha pose", sitting with their belly up.', 'Born with straight ears that fold after a few weeks.'],
      famous: ['Taylor Swift (Olivia Benson y Meredith Grey)', 'Ed Sheeran'],
      famousEn: ['Taylor Swift (Olivia Benson and Meredith Grey)', 'Ed Sheeran'],
      curiosity: 'Toda la raza desciende de una sola gata llamada Susie, encontrada en una granja escocesa en 1961.',
      curiosityEn: 'The entire breed descends from a single cat named Susie, found on a Scottish farm in 1961.',
    },
  };

  try { if (typeof DOG_BREEDS !== 'undefined' && Array.isArray(DOG_BREEDS)) DOG_BREEDS.forEach(function (b) { if (DOG_TRIVIA[b.id]) Object.assign(b, DOG_TRIVIA[b.id]); }); } catch (e) {}
  try { if (typeof CAT_BREEDS !== 'undefined' && Array.isArray(CAT_BREEDS)) CAT_BREEDS.forEach(function (b) { if (CAT_TRIVIA[b.id]) Object.assign(b, CAT_TRIVIA[b.id]); }); } catch (e) {}
})();
