// cat-breed-data.jsx — Comprehensive cat breed directory

const CAT_BREEDS = [
  {
    id:'persian', name:'Persian', es:'Persa', emoji:'🐱',
    size:'medium', coat:['long'], hypo:false, energy:1, grooming:5, shedding:3,
    trainability:2, vocal:1, family:5, kids:3, pets:4, apartment:5,
    origin:'Irán (Persia)', originEn:'Iran (Persia)', flag:'🇮🇷',
    weight:'3–5 kg', lifespan:'12–17 años', akc:false, fci:false, tica:true, cfa:true,
    temperament:['Tranquilo','Gentil','Cariñoso','Reservado','Elegante'],
    temperamentEn:['Calm','Gentle','Affectionate','Reserved','Elegant'],
    bestFor:['Apartamentos','Adultos tranquilos','Personas mayores'],
    bestForEn:['Apartments','Quiet adults','Seniors'],
    desc:'El Persa es el gato de raza más popular del mundo. Su pelaje largo y exuberante y su cara aplanada son inconfundibles. Criado durante siglos como gato de compañía de la nobleza, tiene un carácter sereno, gentil y muy afectuoso. Prefiere ambientes tranquilos y es ideal para apartamentos.',
    descEn:'The Persian is the world\'s most popular pedigreed cat. Its long, luxurious coat and flat face are unmistakable. Bred for centuries as a noble companion, it has a serene, gentle, and very affectionate character. Prefers quiet environments and is ideal for apartments.',
    care:'Cepillado diario obligatorio para evitar nudos. Limpieza ocular frecuente por la cara plana. Baños ocasionales.',
    careEn:'Daily brushing required to prevent matting. Frequent eye cleaning due to flat face. Occasional baths.',
    health:'Propenso a PKD (enfermedad poliquística renal), problemas respiratorios y problemas dentales por la cara plana.',
    healthEn:'Prone to PKD (polycystic kidney disease), breathing issues, and dental problems due to flat face.',
    mixes:[
      {name:'Himalayan', parents:'Persian + Siamese', desc:'Los colores punto del Siamés con el pelaje largo del Persa. Carácter gentil y tranquilo.'},
      {name:'Exotic Shorthair', parents:'Persian + American Shorthair', desc:'El Persa con pelo corto. Mismo carácter dulce con mucho menos mantenimiento de pelaje.'},
    ]
  },
  {
    id:'siamese', name:'Siamese', es:'Siamés', emoji:'🐈',
    size:'medium', coat:['short'], hypo:false, energy:4, grooming:1, shedding:2,
    trainability:5, vocal:5, family:4, kids:4, pets:3, apartment:4,
    origin:'Tailandia', originEn:'Thailand', flag:'🇹🇭',
    weight:'3–5 kg', lifespan:'12–15 años', akc:false, fci:false, tica:true, cfa:true,
    temperament:['Vocal','Social','Inteligente','Demandante','Leal'],
    temperamentEn:['Vocal','Social','Intelligent','Demanding','Loyal'],
    bestFor:['Personas en casa','Familias activas','Quienes desean interacción constante'],
    bestForEn:['People who are home often','Active families','Those wanting constant interaction'],
    desc:'El Siamés es uno de los gatos más antiguos y reconocibles del mundo. Con sus ojos azules penetrantes y su pelaje punto, es inconfundible. Es extremadamente vocal y comunicativo — literalmente "habla" con su dueño. Muy inteligente, sociable y apegado. No tolera bien la soledad prolongada.',
    descEn:'The Siamese is one of the oldest and most recognizable cats in the world. With its piercing blue eyes and point coloring, it is unmistakable. Extremely vocal and communicative — it literally "talks" with its owner. Very intelligent, sociable, and attached. Does not tolerate prolonged loneliness well.',
    care:'Mínimo cepillado. Necesita mucha interacción y juego. Juguetes interactivos recomendados.',
    careEn:'Minimal grooming. Needs lots of interaction and play. Interactive toys recommended.',
    health:'Generalmente saludable. Vigilar amiloidosis hepática y problemas dentales.',
    healthEn:'Generally healthy. Watch for hepatic amyloidosis and dental problems.',
    mixes:[
      {name:'Himalayan', parents:'Siamese + Persian', desc:'Combinación del pelaje largo del Persa con los colores punto del Siamés. Más tranquilo que el Siamés puro.'},
      {name:'Tonkinese', parents:'Siamese + Burmese', desc:'Más tranquilo que el Siamés pero igualmente sociable. Carácter equilibrado y afectuoso.'},
    ]
  },
  {
    id:'ragdoll', name:'Ragdoll', es:'Ragdoll', emoji:'🐈',
    size:'large', coat:['long'], hypo:false, energy:2, grooming:3, shedding:3,
    trainability:4, vocal:2, family:5, kids:5, pets:5, apartment:5,
    origin:'California, EE. UU.', originEn:'California, USA', flag:'🇺🇸',
    weight:'4–9 kg', lifespan:'12–15 años', akc:false, fci:false, tica:true, cfa:true,
    temperament:['Dócil','Cariñoso','Tranquilo','Gentil','Apacible'],
    temperamentEn:['Docile','Affectionate','Calm','Gentle','Easygoing'],
    bestFor:['Familias con niños','Apartamentos','Apoyo emocional','Primeros dueños'],
    bestForEn:['Families with kids','Apartments','Emotional support','First-time owners'],
    desc:'El Ragdoll recibe su nombre por la tendencia a relajarse completamente cuando se le coge en brazos, como una muñeca de trapo. Es uno de los gatos más dóciles y cariñosos que existen. Se lleva excepcionalmente bien con niños, perros y otras mascotas. Ideal como primer gato o para familias.',
    descEn:'The Ragdoll gets its name from its tendency to go completely limp when picked up, like a rag doll. It is one of the most docile and affectionate cats in existence. Gets along exceptionally well with children, dogs, and other pets. Ideal as a first cat or for families.',
    care:'Cepillado 2–3 veces por semana. Semi-sedentario — no necesita mucho ejercicio pero le gustan los juegos tranquilos.',
    careEn:'Brush 2–3 times weekly. Semi-sedentary — doesn\'t need much exercise but enjoys calm play.',
    health:'Vigilar enfermedad del corazón (cardiomiopatía hipertrófica) y PKD. Elegir criadores con pruebas genéticas.',
    healthEn:'Watch for heart disease (HCM) and PKD. Choose breeders with genetic testing.',
    mixes:[
      {name:'Ragamuffin', parents:'Ragdoll (variación)', desc:'Similar al Ragdoll pero con mayor variedad de colores y pelaje más suave. Igualmente dócil.'},
    ]
  },
  {
    id:'maine-coon', name:'Maine Coon', es:'Maine Coon', emoji:'🦁',
    size:'large', coat:['long'], hypo:false, energy:3, grooming:3, shedding:4,
    trainability:5, vocal:3, family:5, kids:5, pets:5, apartment:3,
    origin:'Maine, EE. UU.', originEn:'Maine, USA', flag:'🇺🇸',
    weight:'4–8 kg', lifespan:'12–15 años', akc:false, fci:false, tica:true, cfa:true,
    temperament:['Amigable','Juguetón','Gentil','Inteligente','Sociable'],
    temperamentEn:['Friendly','Playful','Gentle','Intelligent','Sociable'],
    bestFor:['Familias con niños','Casas con espacio','Personas activas'],
    bestForEn:['Families with kids','Spacious homes','Active people'],
    desc:'El Maine Coon es el gato más grande de las razas domésticas y uno de los más antiguos de Norteamérica. Con su pelaje grueso adaptado al invierno de Maine, sus penachos en las orejas y su cola exuberante, es el "perro del mundo felino" — sociable, juguetón y extremadamente adaptable. Le encanta jugar con agua.',
    descEn:'The Maine Coon is the largest domestic cat breed and one of the oldest in North America. With its thick coat adapted to Maine winters, ear tufts, and bushy tail, it is the "dog of the cat world" — sociable, playful, and extremely adaptable. It loves playing with water.',
    care:'Cepillado 2 veces por semana. Activo — necesita juego y espacio. Árbol rascador grande recomendado.',
    careEn:'Brush twice weekly. Active — needs play and space. Large cat tree recommended.',
    health:'Vigilar cardiomiopatía hipertrófica (HCM), displasia de cadera y espinal muscular atrofia.',
    healthEn:'Watch for hypertrophic cardiomyopathy (HCM), hip dysplasia, and spinal muscular atrophy.',
    mixes:[]
  },
  {
    id:'british-shorthair', name:'British Shorthair', es:'British Shorthair', emoji:'🐱',
    size:'large', coat:['short'], hypo:false, energy:2, grooming:2, shedding:3,
    trainability:3, vocal:2, family:5, kids:4, pets:4, apartment:5,
    origin:'Gran Bretaña', originEn:'Great Britain', flag:'🇬🇧',
    weight:'3.5–7.7 kg', lifespan:'12–20 años', akc:false, fci:false, tica:true, cfa:true,
    temperament:['Calmado','Independiente','Leal','Adaptable','Tranquilo'],
    temperamentEn:['Calm','Independent','Loyal','Adaptable','Easygoing'],
    bestFor:['Apartamentos','Familias con niños','Personas con trabajo demandante'],
    bestForEn:['Apartments','Families with kids','Busy professionals'],
    desc:'El British Shorthair es el gato más popular de Gran Bretaña y uno de los más reconocibles del mundo. Redondo, robusto y con su característico pelaje denso, tiene un carácter equilibrado y calmado. Es leal pero no dependiente — ideal para hogares ocupados. El famoso Cheshire Cat de Alicia en el País de las Maravillas está basado en esta raza.',
    descEn:'The British Shorthair is Britain\'s most popular cat and one of the most recognizable in the world. Round, robust, with its characteristic dense coat, it has a balanced and calm character. Loyal but not clingy — ideal for busy households. The famous Cheshire Cat from Alice in Wonderland is based on this breed.',
    care:'Cepillado semanal. Bajo mantenimiento general. Propenso a la obesidad — controlar alimentación.',
    careEn:'Weekly brushing. Generally low maintenance. Prone to obesity — monitor diet.',
    health:'Vigilar cardiomiopatía hipertrófica (HCM) y enfermedad poliquística renal (PKD).',
    healthEn:'Watch for hypertrophic cardiomyopathy (HCM) and polycystic kidney disease (PKD).',
    mixes:[]
  },
  {
    id:'scottish-fold', name:'Scottish Fold', es:'Scottish Fold', emoji:'🐱',
    size:'medium', coat:['short','long'], hypo:false, energy:2, grooming:2, shedding:2,
    trainability:3, vocal:2, family:5, kids:4, pets:4, apartment:5,
    origin:'Escocia', originEn:'Scotland', flag:'🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    weight:'2.7–6 kg', lifespan:'11–14 años', akc:false, fci:false, tica:true, cfa:true,
    temperament:['Adaptable','Tranquilo','Cariñoso','Juguetón','Amigable'],
    temperamentEn:['Adaptable','Calm','Affectionate','Playful','Friendly'],
    bestFor:['Apartamentos','Familias','Primeros dueños'],
    bestForEn:['Apartments','Families','First-time owners'],
    desc:'El Scottish Fold es famoso por sus orejas dobladas hacia adelante que le dan una apariencia de búho adorable. Esta característica es causada por una mutación genética. Adaptable, cariñoso y tranquilo. Se convirtió en viral por el gato Maru en YouTube y el gato de Taylor Swift.',
    descEn:'The Scottish Fold is famous for its forward-folded ears that give it an adorable owl-like appearance. This characteristic is caused by a genetic mutation. Adaptable, affectionate, and calm. It became viral thanks to the cat Maru on YouTube and Taylor Swift\'s cats.',
    care:'Cepillado regular. Revisar orejas regularmente. Importante controlar artritis — raza propensa a problemas articulares.',
    careEn:'Regular brushing. Check ears regularly. Important to monitor arthritis — breed prone to joint problems.',
    health:'Osteocondrodisplasia — todos los Scottish Fold tienen problemas articulares en cierto grado. Controversial eticamente en algunos países.',
    healthEn:'Osteochondrodysplasia — all Scottish Folds have joint problems to some degree. Ethically controversial in some countries.',
    mixes:[
      {name:'Scottish Straight', parents:'Scottish Fold (orejas rectas)', desc:'Misma genética pero sin la mutación de orejas. Más sano que el Fold. Temperamento idéntico.'},
    ]
  },
  {
    id:'bengal', name:'Bengal', es:'Bengal', emoji:'🐆',
    size:'medium-large', coat:['short'], hypo:false, energy:5, grooming:1, shedding:2,
    trainability:5, vocal:3, family:4, kids:4, pets:3, apartment:2,
    origin:'EE. UU. (híbrido)', originEn:'USA (hybrid)', flag:'🇺🇸',
    weight:'3.6–7 kg', lifespan:'12–16 años', akc:false, fci:false, tica:true, cfa:true,
    temperament:['Activo','Curioso','Atlético','Inteligente','Salvaje-doméstico'],
    temperamentEn:['Active','Curious','Athletic','Intelligent','Wild-domestic'],
    bestFor:['Personas muy activas','Casas con espacio','Amantes de gatos exóticos'],
    bestForEn:['Very active people','Spacious homes','Exotic cat lovers'],
    desc:'El Bengal fue creado cruzando el gato leopardo asiático salvaje con gatos domésticos. El resultado es un gato con aspecto de leopardo en miniatura y el carácter de un doméstico. Extremadamente activo e inteligente. Le encanta el agua, trepar y explorar. Necesita mucho espacio y estimulación.',
    descEn:'The Bengal was created by crossing the Asian leopard cat with domestic cats. The result is a cat with the look of a miniature leopard and the character of a domestic. Extremely active and intelligent. Loves water, climbing, and exploring. Needs lots of space and stimulation.',
    care:'Mínimo cepillado. MUCHO ejercicio y estimulación mental. Correas y arneses recomendados para paseos.',
    careEn:'Minimal grooming. LOTS of exercise and mental stimulation. Leashes and harnesses recommended for walks.',
    health:'Generalmente robusto. Vigilar HCM, PK deficiency y cataratas hereditarias.',
    healthEn:'Generally robust. Watch for HCM, PK deficiency, and hereditary cataracts.',
    mixes:[]
  },
  {
    id:'sphynx', name:'Sphynx', es:'Sphynx (Sin pelo)', emoji:'🐈',
    size:'medium', coat:['hairless'], hypo:true, energy:4, grooming:3, shedding:1,
    trainability:4, vocal:4, family:5, kids:4, pets:5, apartment:5,
    origin:'Toronto, Canadá', originEn:'Toronto, Canada', flag:'🇨🇦',
    weight:'3.5–7 kg', lifespan:'9–15 años', akc:false, fci:false, tica:true, cfa:true,
    temperament:['Extrovertido','Curioso','Afectuoso','Juguetón','Travieso'],
    temperamentEn:['Extroverted','Curious','Affectionate','Playful','Mischievous'],
    bestFor:['Personas con alergias leves','Amantes de gatos únicos','Hogares activos'],
    bestForEn:['People with mild allergies','Unique cat lovers','Active households'],
    desc:'El Sphynx parece no tener pelo pero en realidad tiene una capa de pelusa muy fina al tacto como gamuza. Su piel necesita limpieza semanal en lugar de cepillado. Es uno de los gatos más extrovertidos y cariñosos — busca calor humano constantemente. Ideal para personas con alergias leves (aunque no es completamente hipoalergénico).',
    descEn:'The Sphynx appears hairless but actually has a very fine down coat that feels like suede. Its skin needs weekly cleaning instead of brushing. One of the most extroverted and affectionate cats — constantly seeks human warmth. Ideal for people with mild allergies (though not completely hypoallergenic).',
    care:'Baño semanal obligatorio — acumula grasa en la piel. Limpieza de orejas frecuente. Proteger del frío.',
    careEn:'Weekly bath required — accumulates skin oil. Frequent ear cleaning. Protect from cold.',
    health:'Vigilar cardiomiopatía hipertrófica (HCM) y problemas de piel. Sensible al sol.',
    healthEn:'Watch for HCM and skin problems. Sun-sensitive.',
    mixes:[
      {name:'Bambino', parents:'Sphynx + Munchkin', desc:'Sin pelo y patas cortas. Rarísimo. Carácter afectuoso del Sphynx con el tamaño del Munchkin.'},
    ]
  },
  {
    id:'russian-blue', name:'Russian Blue', es:'Azul Ruso', emoji:'🐈',
    size:'medium', coat:['short'], hypo:true, energy:3, grooming:1, shedding:2,
    trainability:3, vocal:2, family:4, kids:3, pets:3, apartment:5,
    origin:'Rusia', originEn:'Russia', flag:'🇷🇺',
    weight:'3.5–7 kg', lifespan:'15–20 años', akc:false, fci:false, tica:true, cfa:true,
    temperament:['Reservado','Inteligente','Gentil','Leal','Sensible'],
    temperamentEn:['Reserved','Intelligent','Gentle','Loyal','Sensitive'],
    bestFor:['Adultos tranquilos','Apartamentos','Personas con alergias leves'],
    bestForEn:['Quiet adults','Apartments','People with mild allergies'],
    desc:'El Azul Ruso es conocido por su pelaje de color azul-gris plateado y sus ojos verdes brillantes. Tiene fama de producir menos alérgenos que otras razas. Es reservado con extraños pero extremadamente leal con su familia. Inteligente, sensible y de carácter tranquilo. Puede vivir hasta 20 años.',
    descEn:'The Russian Blue is known for its blue-gray silver coat and bright green eyes. It is reputed to produce fewer allergens than other breeds. Reserved with strangers but extremely loyal to its family. Intelligent, sensitive, and calm. Can live up to 20 years.',
    care:'Mínimo cepillado. Evitar cambios bruscos en la rutina — muy sensible al estrés.',
    careEn:'Minimal grooming. Avoid sudden routine changes — very stress-sensitive.',
    health:'Generalmente saludable y longevo. Vigilar obesidad y problemas renales en la vejez.',
    healthEn:'Generally healthy and long-lived. Watch for obesity and kidney problems in old age.',
    mixes:[]
  },
  {
    id:'abyssinian', name:'Abyssinian', es:'Abisinio', emoji:'🐆',
    size:'medium', coat:['short'], hypo:false, energy:5, grooming:1, shedding:2,
    trainability:5, vocal:3, family:4, kids:4, pets:4, apartment:2,
    origin:'Etiopía / Gran Bretaña', originEn:'Ethiopia / Great Britain', flag:'🇪🇹',
    weight:'3–5.5 kg', lifespan:'9–13 años', akc:false, fci:false, tica:true, cfa:true,
    temperament:['Activo','Curioso','Juguetón','Atletico','Independiente'],
    temperamentEn:['Active','Curious','Playful','Athletic','Independent'],
    bestFor:['Personas activas','Casas con espacio','Familias sin bebés'],
    bestForEn:['Active people','Spacious homes','Families without babies'],
    desc:'El Abisinio es uno de los gatos más activos e inteligentes del mundo. Con su pelaje atigrado único (ticking) y su cuerpo esbelto y atlético, es el "atleta" del mundo felino. Curioso, juguetón y en constante movimiento. No es el gato ideal para quien busca una mascota tranquila de regazo.',
    descEn:'The Abyssinian is one of the most active and intelligent cats in the world. With its unique ticked coat and slender, athletic body, it is the "athlete" of the cat world. Curious, playful, and in constant motion. Not the ideal cat for someone looking for a calm lap pet.',
    care:'Mínimo cepillado. Necesita mucho juego, estimulación y espacio para correr. Árbol rascador alto esencial.',
    careEn:'Minimal grooming. Needs lots of play, stimulation, and space to run. Tall cat tree essential.',
    health:'Vigilar amiloidosis renal y PK deficiency. Comprar de criadores con pruebas genéticas.',
    healthEn:'Watch for renal amyloidosis and PK deficiency. Buy from breeders with genetic testing.',
    mixes:[]
  },
  {
    id:'devon-rex', name:'Devon Rex', es:'Devon Rex', emoji:'🐱',
    size:'small-medium', coat:['curly'], hypo:true, energy:4, grooming:2, shedding:1,
    trainability:5, vocal:3, family:5, kids:5, pets:5, apartment:5,
    origin:'Devon, Inglaterra', originEn:'Devon, England', flag:'🇬🇧',
    weight:'2.3–4.5 kg', lifespan:'9–15 años', akc:false, fci:false, tica:true, cfa:true,
    temperament:['Travieso','Activo','Social','Afectuoso','Juguetón'],
    temperamentEn:['Mischievous','Active','Social','Affectionate','Playful'],
    bestFor:['Apartamentos','Familias activas','Personas con alergias leves'],
    bestForEn:['Apartments','Active families','People with mild allergies'],
    desc:'El Devon Rex es conocido como el "Alien" del mundo felino por sus orejas enormes, ojos grandes y cara pequeña. Su pelaje ondulado es el resultado de una mutación genética diferente a la del Cornish Rex. Es uno de los gatos más juguetones, traviesos y afectuosos que existen. Le encanta subirse a los hombros de su dueño.',
    descEn:'The Devon Rex is known as the "Alien" of the cat world for its huge ears, large eyes, and small face. Its wavy coat results from a genetic mutation different from the Cornish Rex. One of the most playful, mischievous, and affectionate cats in existence. Loves climbing onto its owner\'s shoulders.',
    care:'Limpieza suave de pelaje. Limpiar orejas regularmente — las grandes orejas acumulan suciedad. Baños ocasionales.',
    careEn:'Gentle coat cleaning. Clean ears regularly — large ears accumulate dirt. Occasional baths.',
    health:'Vigilar miopatía hereditaria (espasmos musculares), cardiomiopatía y problemas de piel.',
    healthEn:'Watch for hereditary myopathy (muscle spasms), cardiomyopathy, and skin problems.',
    mixes:[]
  },
  {
    id:'norwegian-forest', name:'Norwegian Forest Cat', es:'Gato Bosque de Noruega', emoji:'🦁',
    size:'large', coat:['long'], hypo:false, energy:3, grooming:3, shedding:4,
    trainability:3, vocal:2, family:5, kids:5, pets:5, apartment:2,
    origin:'Noruega', originEn:'Norway', flag:'🇳🇴',
    weight:'3.5–9 kg', lifespan:'14–16 años', akc:false, fci:false, tica:true, cfa:true,
    temperament:['Independiente','Amigable','Activo','Gentil','Adaptable'],
    temperamentEn:['Independent','Friendly','Active','Gentle','Adaptable'],
    bestFor:['Casas con espacio','Familias con niños','Jardines cercados'],
    bestForEn:['Spacious homes','Families with kids','Enclosed gardens'],
    desc:'El Gato del Bosque Noruego es el gato nacional de Noruega y aparece en la mitología vikinga. Su doble capa de pelo fue diseñada para sobrevivir los inviernos escandinavos. Resistente, activo e independiente, pero sorprendentemente cariñoso con su familia. Le encanta trepar y explorar.',
    descEn:'The Norwegian Forest Cat is Norway\'s national cat and appears in Viking mythology. Its double coat was designed to survive Scandinavian winters. Sturdy, active, and independent, but surprisingly affectionate with its family. Loves climbing and exploring.',
    care:'Cepillado 2–3 veces por semana. Muda abundante en primavera. Necesita espacio y actividad.',
    careEn:'Brush 2–3 times weekly. Heavy shedding in spring. Needs space and activity.',
    health:'Vigilar HCM, glucogenosis tipo IV y PKD.',
    healthEn:'Watch for HCM, glycogen storage disease type IV, and PKD.',
    mixes:[]
  },
  {
    id:'himalayan', name:'Himalayan', es:'Himalayo', emoji:'💙',
    photo:'uploads/Page 12.webp',
    size:'medium', coat:['long'], hypo:false, energy:1, grooming:5, shedding:3,
    trainability:2, vocal:2, family:5, kids:3, pets:4, apartment:5,
    origin:'USA / UK', originEn:'USA / UK', flag:'🇺🇸',
    weight:'3–5 kg', lifespan:'9–15 años', akc:false, fci:false, tica:true, cfa:true,
    temperament:['Tranquilo','Gentil','Cariñoso','Dulce','Elegante'],
    temperamentEn:['Calm','Gentle','Affectionate','Sweet','Elegant'],
    bestFor:['Apartamentos','Adultos tranquilos','Personas mayores','Familias con niños tranquilos'],
    bestForEn:['Apartments','Quiet adults','Seniors','Families with calm children'],
    desc:'El Himalayo combina el pelaje largo y lujoso del Persa con los colores punto del Siamés, creando uno de los gatos más bellos del mundo. Es tranquilo, afectuoso y profundamente leal a su familia. Sus ojos azules intensos son característicos de la raza.',
    descEn:'The Himalayan combines the long, luxurious coat of the Persian with the colorpoint pattern of the Siamese, creating one of the most beautiful cats in the world. Calm, affectionate, and deeply loyal to their family, with characteristic deep blue eyes.',
    care:'Cepillado diario obligatorio para evitar nudos en el pelaje largo. Limpieza ocular frecuente. Baños mensuales recomendados.',
    careEn:'Daily brushing required to prevent matting. Frequent eye cleaning. Monthly baths recommended.',
    health:'Propenso a PKD (enfermedad poliquística renal), problemas respiratorios leves por la cara aplanada y problemas dentales.',
    healthEn:'Prone to PKD (polycystic kidney disease), mild breathing issues due to flat face, and dental problems.',
    mixes:[
      {name:'Himmy Mix', parents:'Himalayan + domestic', desc:'Hereda los colores punto y el pelaje semi-largo con carácter generalmente tranquilo.'},
    ]
  },
];

const CAT_MESTIZO_INFO = {
  title: ['Gatos Mestizos', 'Mixed Breed Cats'],
  desc: ['Los gatos domésticos de origen desconocido suelen ser los más saludables y adaptables. Cada uno tiene una personalidad única. La mayoría de los gatos en refugios son mestizos buscando un hogar amoroso.',
         'Domestic cats of unknown origin are often the healthiest and most adaptable. Each one has a unique personality. Most cats in shelters are mixed breeds looking for a loving home.'],
  link: 'Adopciones.html',
};

Object.assign(window, { CAT_BREEDS, CAT_MESTIZO_INFO });
