(function(){
const { useState, useEffect } = React;
const TIMELINE = [
  { year: "2012", city: "Santiago, RD", emoji: "\u{1F436}", title: "El primer cachorro", body: "Todo empez\xF3 con una camada de Golden Retrievers en Santiago. Sin experiencia formal, con mucho amor y m\xE1s preguntas que respuestas. El primer hogar que adopt\xF3 un cachorro nuestro se convirti\xF3 en familia." },
  { year: "2015", city: "Santiago, RD", emoji: "\u{1F3EA}", title: "El primer local", body: "Abrimos el primer espacio f\xEDsico dedicado a crianza y adopci\xF3n responsable. Lo que era informal se convirti\xF3 en un proceso: salud verificada, contratos de adopci\xF3n, seguimiento post-adopci\xF3n." },
  { year: "2018", city: "Villa Olga, Santiago, RD", emoji: "\u{1F4C8}", title: "Local m\xE1s grande", body: "Con la demanda creciendo, expandimos nuestro espacio en Villa Olga, Santiago. M\xE1s razas, m\xE1s familias y un equipo m\xE1s grande con un prop\xF3sito m\xE1s claro: crianza responsable como estilo de vida." },
  { year: "2020", city: "USA", emoji: "\u2708\uFE0F", title: "Nos mudamos a USA", body: "Con la familia creciendo y la visi\xF3n m\xE1s clara, cruzamos a los Estados Unidos. El mercado era m\xE1s exigente, la regulaci\xF3n m\xE1s estricta y la competencia enorme. Pero tambi\xE9n hab\xEDa m\xE1s familias que buscaban exactamente lo que ofrecemos: cachorros criados en familia, no en jaulas." },
  { year: "2022", city: "New York", emoji: "\u{1F5FD}", title: "Abrimos en New York", body: "Nueva ciudad, mismo coraz\xF3n. Abrimos operaciones en New York, llevando nuestra filosof\xEDa de crianza responsable a una de las ciudades m\xE1s exigentes del mundo. Cada cachorro, criado con el mismo amor de siempre." },
  { year: "2025", city: "Florida", emoji: "\u{1F334}", title: "Abrimos en Florida", body: "Lanzamos nuestra operaci\xF3n en Florida con la plataforma digital: BPuppy Social para la comunidad, el blog educativo, la tienda curada y el sistema de citas de grooming online. El sue\xF1o de llevar todo a un solo lugar para las familias que conf\xEDan en nosotros." }
];
const IMPACT_STORIES = [
  { emoji: "\u{1F9E9}", tag: "Autismo", title: "Mateo y su Shih Tzu", body: 'Mateo tiene 7 a\xF1os y TEA nivel 2. Sus padres buscaban una raza calmada y gentil. Trabajamos con su terapeuta para elegir el cachorro correcto. Seis meses despu\xE9s, su madre nos escribi\xF3: "Mateo habla m\xE1s con el perro que con cualquier persona. Es su mejor amigo."', img: "nosotros-impact-0" },
  { emoji: "\u{1F474}", tag: "Adultos mayores", title: "Jeff & Freda - Lilly", body: "Entrevistamos a dos adultos mayores que nos contaron de primera mano lo mucho que su mascota Lilly los ha ayudado durante los momentos m\xE1s dif\xEDciles de su vida. Sus testimonios nos recordaron por qu\xE9 hacemos lo que hacemos \u2014 un compa\xF1ero fiel puede cambiar una vida entera.", img: "nosotros-impact-1", video: "rr2gVZjCFWs" },
  { emoji: "\u{1F3E0}", tag: "Refugio", title: "Visita al Humane Society Kansas", body: "Visitamos el Caring Hands Humane Society de Newton, Kansas y entrevistamos a su directora de marketing. Nos habl\xF3 sobre el incre\xEDble trabajo que realizan, c\xF3mo gestionan el refugio y su misi\xF3n de darle una segunda oportunidad a cada animal.", img: "nosotros-impact-2", video: "J5Q6c3wy0QE" },
  { emoji: "\u{1F393}", tag: "Educaci\xF3n", title: "Taller en Lincoln Marti School", hidden: true, body: "Llevamos un cachorro a una escuela primaria en Hialeah para una charla sobre responsabilidad animal, empat\xEDa y cuidado de mascotas. 120 ni\xF1os, un cachorro, y muchas l\xE1grimas de emoci\xF3n de los maestros.", img: "nosotros-impact-3" }
];
const TEAM = [
  { name: "Angelina", role: "Co-Fundadora & Directora", bio: "El coraz\xF3n detr\xE1s de BPuppy. Desde 2012, Angelina ha guiado a cientos de familias en encontrar el compa\xF1ero perfecto. Su enfoque en crianza responsable y bienestar animal define cada decisi\xF3n que tomamos.", img: "uploads/Angelina.jpg" },
  { name: "Luis", role: "Fundador & CEO", bio: "La visi\xF3n detr\xE1s del negocio. Luis llev\xF3 BPuppy de Santo Domingo a Miami con una misi\xF3n clara: demostrar que criar con amor y con est\xE1ndares es la \xFAnica forma de hacer esto bien. 12+ a\xF1os construyendo familias.", img: "uploads/LUIS.jpeg" }
];
const PRESS = [
  { source: "Univision Miami", year: "2023", headline: '"La criadora que lleg\xF3 de RD y cambi\xF3 c\xF3mo Miami adopta mascotas"' },
  { source: "El Nuevo Herald", year: "2022", headline: '"BPuppy: el modelo de adopci\xF3n responsable que crece en el Sur de Florida"' },
  { source: "Miami Herald", year: "2021", headline: '"Local pet breeder delivers puppies to families during lockdown"' },
  { source: "NBC Miami", year: "2024", headline: '"Pet social network: BPuppy launches community app for South Florida dog owners"' }
];
function Timeline() {
  const [active, setActive] = useState(null);
  return /* @__PURE__ */ React.createElement("div", { style: { position: "relative" } }, /* @__PURE__ */ React.createElement("div", { style: { position: "absolute", left: 20, top: 0, bottom: 0, width: 2, background: "var(--line)" } }), /* @__PURE__ */ React.createElement("div", { style: { display: "flex", flexDirection: "column", gap: 0 } }, TIMELINE.map(
    (ev, i) => /* @__PURE__ */ React.createElement("div", { key: i, onClick: () => setActive(active === i ? null : i), style: { display: "flex", gap: 28, paddingBottom: 32, cursor: "pointer" } }, /* @__PURE__ */ React.createElement("div", { style: { position: "relative", flexShrink: 0, width: 42 } }, /* @__PURE__ */ React.createElement("div", { style: { width: 42, height: 42, borderRadius: "50%", background: active === i ? "var(--orange)" : "var(--paper)", border: `2px solid ${active === i ? "var(--orange)" : "var(--line)"}`, display: "grid", placeItems: "center", fontSize: 18, transition: "all .2s", zIndex: 1, position: "relative" } }, ev.emoji)), /* @__PURE__ */ React.createElement("div", { style: { flex: 1, paddingTop: 8 } }, /* @__PURE__ */ React.createElement("div", { style: { display: "flex", alignItems: "baseline", gap: 10, marginBottom: 4 } }, /* @__PURE__ */ React.createElement("span", { style: { fontFamily: "Bricolage Grotesque,sans-serif", fontSize: 22, fontWeight: 800, color: active === i ? "var(--orange)" : "var(--ink)" } }, ev.year), /* @__PURE__ */ React.createElement("span", { style: { fontSize: 12, color: "var(--ink-soft)", fontWeight: 500 } }, "\u{1F4CD} ", ev.city)), /* @__PURE__ */ React.createElement("h3", { style: { fontSize: 16, fontWeight: 700, color: "var(--ink)", margin: "0 0 6px" } }, ev.title), active === i && /* @__PURE__ */ React.createElement("p", { style: { fontSize: 14, color: "var(--ink-2)", lineHeight: 1.7, margin: 0, animation: "fadeIn .25s ease" } }, ev.body)))
  )));
}
function ImpactStories() {
  function isEducacionVisible() {
    try {
      var d = JSON.parse(localStorage.getItem("bpuppy_publish_v1")) || {};
      return d.sections && d.sections["Nosotros"] && d.sections["Nosotros"]["impacto_educacion"] === true;
    } catch (e) {
      return false;
    }
  }
  const visibleStories = IMPACT_STORIES.filter(function(s) {
    return !s.hidden || isEducacionVisible();
  });
  const [active, setActive] = useState(0);
  const story = visibleStories[Math.min(active, visibleStories.length - 1)];
  return /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("div", { style: { display: "flex", gap: 8, marginBottom: 24, flexWrap: "wrap" } }, visibleStories.map(
    (s, i) => /* @__PURE__ */ React.createElement("button", { key: i, onClick: () => setActive(i), style: { padding: "7px 16px", borderRadius: 999, border: "none", cursor: "pointer", fontFamily: "inherit", fontSize: 12.5, fontWeight: active === i ? 700 : 500, background: active === i ? "var(--orange)" : "var(--bg)", color: active === i ? "#fff" : "var(--ink-2)", transition: "all .15s" } }, s.emoji, " ", s.tag)
  )), /* @__PURE__ */ React.createElement("div", { key: active, style: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 32, alignItems: "center", animation: "fadeIn .3s ease" } }, /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("div", { style: { display: "inline-block", padding: "3px 12px", borderRadius: 999, background: "rgba(245,130,32,0.1)", color: "var(--orange)", fontSize: 11, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 14 } }, story.tag), /* @__PURE__ */ React.createElement("h3", { style: { fontFamily: "Bricolage Grotesque,sans-serif", fontSize: 24, fontWeight: 800, color: "var(--ink)", margin: "0 0 14px", letterSpacing: "-0.02em" } }, story.title), /* @__PURE__ */ React.createElement("p", { style: { fontSize: 15.5, color: "var(--ink-2)", lineHeight: 1.75, margin: 0, fontStyle: "italic", fontFamily: "Instrument Serif,Georgia,serif" } }, '"', story.body, '"')), story.video ? /* @__PURE__ */ React.createElement("div", { style: { borderRadius: 20, overflow: "hidden", aspectRatio: "16/9", position: "relative" } }, /* @__PURE__ */ React.createElement(
    "iframe",
    {
      src: "https://www.youtube.com/embed/" + story.video + "?rel=0&modestbranding=1&cc_load_policy=1&cc_lang_pref=es",
      title: story.title,
      allow: "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture",
      allowFullScreen: true,
      style: { position: "absolute", inset: 0, width: "100%", height: "100%", border: "none", display: "block" }
    }
  )) : /* @__PURE__ */ React.createElement("image-slot", { id: story.img, shape: "rounded", radius: "20", fit: "cover", placeholder: `Foto: ${story.title}`, style: { aspectRatio: "3/4", display: "block", width: "100%", background: "var(--bg)" } })));
}
function NosotrosApp() {
  const [tab, setTab] = useState(() => {
    const p = new URLSearchParams(window.location.search).get("tab");
    return ["historia", "impacto", "equipo", "prensa"].includes(p) ? p : "historia";
  });
  const TABS = [["historia", "\u{1F4D6} Historia"], ["impacto", "\u2764\uFE0F Impacto Social"], ["equipo", "\u{1F465} Equipo"]];
  return /* @__PURE__ */ React.createElement("div", { style: { background: "var(--bg)", minHeight: "100vh" } }, /* @__PURE__ */ React.createElement("div", { style: { background: "linear-gradient(135deg, var(--ink) 0%, #3D2E2A 100%)", paddingTop: 120, paddingBottom: 60 } }, /* @__PURE__ */ React.createElement("div", { className: "container", style: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 48, alignItems: "center" } }, /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("div", { style: { display: "inline-block", padding: "4px 14px", borderRadius: 999, background: "rgba(245,130,32,0.18)", color: "var(--orange)", fontSize: 11, fontWeight: 800, letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: 16 } }, "Nuestra historia"), /* @__PURE__ */ React.createElement("h1", { style: { fontFamily: "Bricolage Grotesque,sans-serif", fontSize: "clamp(32px,4.5vw,52px)", fontWeight: 800, color: "#fff", margin: "0 0 16px", letterSpacing: "-0.03em", lineHeight: 1.05 } }, "De Santiago", /* @__PURE__ */ React.createElement("br", null), "a ", /* @__PURE__ */ React.createElement("em", { style: { fontFamily: "Instrument Serif,Georgia,serif", fontStyle: "italic", fontWeight: 400, color: "var(--orange)" } }, "Estados Unidos")), /* @__PURE__ */ React.createElement("p", { style: { fontSize: 15.5, color: "rgba(255,255,255,0.7)", margin: "0 0 28px", lineHeight: 1.65, maxWidth: 420 } }, "M\xE1s de 12 a\xF1os repartiendo felicidad, construyendo familias y generando impacto en comunidades que necesitaban un compa\xF1ero fiel."), /* @__PURE__ */ React.createElement("div", { style: { display: "flex", gap: 24, flexWrap: "wrap" } }, [["12+", "A\xF1os de experiencia"], ["500+", "Familias"], ["3", "Ciudades"], ["100%", "Con amor"]].map(
    ([n, l]) => /* @__PURE__ */ React.createElement("div", { key: l }, /* @__PURE__ */ React.createElement("div", { style: { fontFamily: "Bricolage Grotesque,sans-serif", fontSize: 28, fontWeight: 800, color: "var(--orange)" } }, n), /* @__PURE__ */ React.createElement("div", { style: { fontSize: 11, color: "rgba(255,255,255,0.5)" } }, l))
  ))), /* @__PURE__ */ React.createElement("div", { style: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 } }, ["Equipo BPuppy", "Nuestro local", "Con las familias", "Primera camada"].map(
    (label, i) => /* @__PURE__ */ React.createElement("image-slot", { key: i, id: `nosotros-hero-${i}`, shape: "rounded", radius: "16", placeholder: label, style: { aspectRatio: "1", display: "block" } })
  )))), /* @__PURE__ */ React.createElement("div", { style: { background: "var(--paper)", borderBottom: "1px solid var(--line)", position: "sticky", top: 64, zIndex: 50 } }, /* @__PURE__ */ React.createElement("div", { className: "container", style: { display: "flex", gap: 0, overflowX: "auto", scrollbarWidth: "none" } }, TABS.map(
    ([id, label]) => /* @__PURE__ */ React.createElement("button", { key: id, onClick: () => setTab(id), style: { padding: "16px 20px", border: "none", borderBottom: `2.5px solid ${tab === id ? "var(--orange)" : "transparent"}`, background: "none", cursor: "pointer", fontFamily: "inherit", fontSize: 13.5, fontWeight: tab === id ? 700 : 500, color: tab === id ? "var(--orange)" : "var(--ink-2)", whiteSpace: "nowrap", transition: "all .15s" } }, label)
  ))), /* @__PURE__ */ React.createElement("div", { className: "container", style: { padding: "60px 0 80px" } }, tab === "historia" && /* @__PURE__ */ React.createElement("div", { style: { display: "grid", gridTemplateColumns: "1fr 1.2fr", gap: 64, alignItems: "start" } }, /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("h2", { style: { fontFamily: "Bricolage Grotesque,sans-serif", fontSize: 28, fontWeight: 800, color: "var(--ink)", margin: "0 0 8px", letterSpacing: "-0.02em" } }, "Nuestra historia"), /* @__PURE__ */ React.createElement("p", { style: { fontSize: 15, color: "var(--ink-2)", lineHeight: 1.7, margin: "0 0 32px" } }, "Haz clic en cada momento para conocer la historia detr\xE1s."), /* @__PURE__ */ React.createElement(Timeline, null)), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("div", { style: { background: "var(--paper)", borderRadius: 24, padding: "28px", boxShadow: "0 4px 32px -8px rgba(45,36,33,0.10)", marginBottom: 24 } }, /* @__PURE__ */ React.createElement("h3", { style: { fontFamily: "Bricolage Grotesque,sans-serif", fontSize: 20, fontWeight: 800, color: "var(--ink)", margin: "0 0 16px" } }, "Nuestra filosof\xEDa"), [
    ["\u{1F43E}", "Crianza en familia", "Ning\xFAn cachorro nuestro vive en jaula. Todos crecen en hogares reales, con familias humanas, hasta su adopci\xF3n."],
    ["\u{1F49A}", "Salud verificada", "Cada cachorro sale con vacunas al d\xEDa, desparasitado, microchipado y con certificado veterinario."],
    ["\u{1F91D}", "Adopci\xF3n responsable", "Hacemos preguntas dif\xEDciles. El match correcto familia-mascota es m\xE1s importante que cerrar una venta."],
    ["\u{1F4DE}", "Acompa\xF1amiento post-adopci\xF3n", "Estamos disponibles despu\xE9s de la adopci\xF3n. Las familias no quedan solas con sus preguntas."]
  ].map(
    ([ic, title, body]) => /* @__PURE__ */ React.createElement("div", { key: title, style: { display: "flex", gap: 14, marginBottom: 20 } }, /* @__PURE__ */ React.createElement("span", { style: { fontSize: 22, flexShrink: 0 } }, ic), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("div", { style: { fontSize: 14, fontWeight: 700, color: "var(--ink)", marginBottom: 3 } }, title), /* @__PURE__ */ React.createElement("div", { style: { fontSize: 13, color: "var(--ink-2)", lineHeight: 1.55 } }, body)))
  )), /* @__PURE__ */ React.createElement("image-slot", { id: "nosotros-filosofia", shape: "rounded", radius: "20", placeholder: "Foto del local o del equipo trabajando", style: { width: "100%", aspectRatio: "16/9", display: "block" } }))), tab === "impacto" && /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("div", { style: { marginBottom: 48 } }, /* @__PURE__ */ React.createElement("h2", { style: { fontFamily: "Bricolage Grotesque,sans-serif", fontSize: 28, fontWeight: 800, color: "var(--ink)", margin: "0 0 8px", letterSpacing: "-0.02em" } }, "Impacto en la comunidad"), /* @__PURE__ */ React.createElement("p", { style: { fontSize: 15, color: "var(--ink-2)", lineHeight: 1.7, maxWidth: 600, margin: 0 } }, 'Cada adopci\xF3n es una historia. Algunas cambian vidas de formas que van m\xE1s all\xE1 de "tener una mascota".')), /* @__PURE__ */ React.createElement(ImpactStories, null), /* @__PURE__ */ React.createElement("div", { style: { marginTop: 56, padding: "32px", borderRadius: 20, background: "var(--paper)", boxShadow: "0 2px 24px -8px rgba(45,36,33,0.10)" } }, /* @__PURE__ */ React.createElement("h3", { style: { fontFamily: "Bricolage Grotesque,sans-serif", fontSize: 20, fontWeight: 800, color: "var(--ink)", margin: "0 0 20px" } }, "Nuestros programas de impacto"), /* @__PURE__ */ React.createElement("div", { style: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(220px,1fr))", gap: 16 } }, [
    ["\u{1F9E9}", "Programa TEA", "Matching especializado y descuentos para familias con ni\xF1os en el espectro autista. "],
    ["\u{1F474}", "Mascotas para mayores", "Descuentos especiales para adultos mayores que adoptan. Incluye gu\xEDa de cuidado simplificada."],
    ["\u{1F3E0}", "Visitas a refugios", "Dos veces al a\xF1o facilitamos adopciones y participamos en labores de rescate en Rep\xFAblica Dominicana."],
    ["\u{1F331}", "Educaci\xF3n canina", "Talleres gratuitos en escuelas primarias sobre responsabilidad y cuidado animal."]
  ].map(
    ([ic, title, body]) => /* @__PURE__ */ React.createElement("div", { key: title, style: { padding: "18px", background: "var(--bg)", borderRadius: 14, border: "1px solid var(--line)" } }, /* @__PURE__ */ React.createElement("span", { style: { fontSize: 28, display: "block", marginBottom: 10 } }, ic), /* @__PURE__ */ React.createElement("div", { style: { fontSize: 14, fontWeight: 700, color: "var(--ink)", marginBottom: 6 } }, title), /* @__PURE__ */ React.createElement("div", { style: { fontSize: 12.5, color: "var(--ink-2)", lineHeight: 1.55 } }, body))
  )))), tab === "equipo" && /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("h2", { style: { fontFamily: "Bricolage Grotesque,sans-serif", fontSize: 28, fontWeight: 800, color: "var(--ink)", margin: "0 0 8px", letterSpacing: "-0.02em" } }, "Nuestro equipo"), /* @__PURE__ */ React.createElement("p", { style: { fontSize: 15, color: "var(--ink-2)", marginBottom: 48 } }, "Las personas detr\xE1s de cada cachorro feliz."), /* @__PURE__ */ React.createElement("div", { style: { display: "grid", gridTemplateColumns: "repeat(2,1fr)", gap: 28, marginBottom: 48, maxWidth: 820 } }, TEAM.map(
    (member, i) => /* @__PURE__ */ React.createElement("div", { key: i, style: { background: "var(--paper)", borderRadius: 24, overflow: "hidden", boxShadow: "0 4px 32px -8px rgba(45,36,33,0.13)", border: "1px solid var(--line)" } }, /* @__PURE__ */ React.createElement("div", { style: { position: "relative", aspectRatio: "3/4", overflow: "hidden", background: "var(--bg-2)" } }, /* @__PURE__ */ React.createElement(
      "img",
      {
        src: member.img,
        alt: member.name,
        style: { width: "100%", height: "100%", objectFit: "cover", objectPosition: "top center", display: "block" }
      }
    ), /* @__PURE__ */ React.createElement("div", { style: { position: "absolute", inset: 0, background: "linear-gradient(to bottom, transparent 55%, rgba(45,36,33,0.72) 100%)", pointerEvents: "none" } }), /* @__PURE__ */ React.createElement("div", { style: { position: "absolute", bottom: 0, left: 0, right: 0, padding: "20px 24px" } }, /* @__PURE__ */ React.createElement("div", { style: { fontSize: 10, fontWeight: 800, color: "var(--orange)", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 4 } }, member.role), /* @__PURE__ */ React.createElement("div", { style: { fontFamily: "Bricolage Grotesque,sans-serif", fontSize: "clamp(24px,3vw,32px)", fontWeight: 800, color: "#fff", letterSpacing: "-0.025em", lineHeight: 1 } }, member.name))), /* @__PURE__ */ React.createElement("div", { style: { padding: "20px 24px 24px" } }, /* @__PURE__ */ React.createElement("p", { style: { fontSize: 14, color: "var(--ink-2)", lineHeight: 1.7, margin: 0 } }, member.bio)))
  )), /* @__PURE__ */ React.createElement("div", { style: { background: "var(--paper)", borderRadius: 20, padding: "32px", border: "1px solid var(--line)" } }, /* @__PURE__ */ React.createElement("h3", { style: { fontFamily: "Bricolage Grotesque,sans-serif", fontSize: 20, fontWeight: 800, color: "var(--ink)", margin: "0 0 12px" } }, "\xBFQuieres unirte al equipo?"), /* @__PURE__ */ React.createElement("p", { style: { fontSize: 14.5, color: "var(--ink-2)", margin: "0 0 18px", lineHeight: 1.65 } }, "Es probable que estemos buscando personas para ser parte del equipo, apasionadas por los animales. Grooming, cuidado de cachorros, adoptions coordinator. Escr\xEDbenos."), /* @__PURE__ */ React.createElement("a", { href: "https://wa.me/18084928294", target: "_blank", rel: "noopener noreferrer", style: { display: "inline-flex", alignItems: "center", gap: 8, padding: "12px 22px", borderRadius: 12, background: "#25D366", color: "#fff", fontFamily: "inherit", fontSize: 14, fontWeight: 700, textDecoration: "none" } }, "\u{1F4AC} Escribir por WhatsApp"))), tab === "prensa" && /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("h2", { style: { fontFamily: "Bricolage Grotesque,sans-serif", fontSize: 28, fontWeight: 800, color: "var(--ink)", margin: "0 0 8px", letterSpacing: "-0.02em" } }, "En los medios"), /* @__PURE__ */ React.createElement("p", { style: { fontSize: 15, color: "var(--ink-2)", marginBottom: 36 } }, "Lo que han dicho de BPuppy."), /* @__PURE__ */ React.createElement("div", { style: { display: "flex", flexDirection: "column", gap: 12, marginBottom: 48 } }, PRESS.map(
    (p, i) => /* @__PURE__ */ React.createElement("div", { key: i, style: { display: "flex", alignItems: "center", gap: 20, padding: "18px 24px", background: "var(--paper)", borderRadius: 14, border: "1px solid var(--line)" } }, /* @__PURE__ */ React.createElement("div", { style: { flexShrink: 0, fontFamily: "Bricolage Grotesque,sans-serif", fontSize: 13, fontWeight: 800, color: "var(--orange)", minWidth: 40 } }, p.year), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("div", { style: { fontSize: 11, fontWeight: 700, color: "var(--ink-soft)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 4 } }, p.source), /* @__PURE__ */ React.createElement("div", { style: { fontSize: 15, fontWeight: 600, color: "var(--ink)", fontStyle: "italic" } }, p.headline)))
  )), /* @__PURE__ */ React.createElement("div", { style: { padding: "28px 32px", background: "var(--paper)", borderRadius: 20, border: "1px solid var(--line)" } }, /* @__PURE__ */ React.createElement("h3", { style: { fontFamily: "Bricolage Grotesque,sans-serif", fontSize: 18, fontWeight: 800, color: "var(--ink)", margin: "0 0 10px" } }, "\xBFEres periodista o creador de contenido?"), /* @__PURE__ */ React.createElement("p", { style: { fontSize: 14, color: "var(--ink-2)", margin: "0 0 16px", lineHeight: 1.6 } }, "Estamos disponibles para entrevistas, colaboraciones y apariciones en medios sobre adopci\xF3n responsable, grooming, bienestar animal y la historia de BPuppy."), /* @__PURE__ */ React.createElement("a", { href: "https://wa.me/18084928294", target: "_blank", rel: "noopener noreferrer", style: { display: "inline-flex", alignItems: "center", gap: 8, padding: "11px 20px", borderRadius: 12, background: "var(--orange)", color: "#fff", fontFamily: "inherit", fontSize: 13.5, fontWeight: 700, textDecoration: "none" } }, "\u{1F4E7} Contacto de prensa")))), /* @__PURE__ */ React.createElement("div", { style: { background: "var(--paper)", borderTop: "1px solid var(--line)", marginTop: 40 } }, /* @__PURE__ */ React.createElement("div", { className: "container", style: { padding: "48px 0 56px" } }, /* @__PURE__ */ React.createElement("div", { className: "eyebrow", style: { marginBottom: 10 } }, "Haines City, FL"), /* @__PURE__ */ React.createElement("h2", { style: { fontFamily: "Bricolage Grotesque,sans-serif", fontSize: 26, fontWeight: 800, color: "var(--ink)", margin: "0 0 6px", letterSpacing: "-0.02em" } }, t(["Donde estamos", "Where we are"])), /* @__PURE__ */ React.createElement("p", { style: { fontSize: 14, color: "var(--ink-2)", margin: "0 0 24px" } }, "5604 Kalogridis Rd, Haines City, FL 33844"), /* @__PURE__ */ React.createElement("div", { style: { borderRadius: 20, overflow: "hidden", border: "1px solid var(--line)" } }, /* @__PURE__ */ React.createElement("iframe", { src: "https://maps.google.com/maps?q=5604+Kalogridis+Rd,+Haines+City,+FL+33844&output=embed", width: "100%", height: "360", style: { border: 0, display: "block" }, allowFullScreen: true, loading: "lazy", referrerPolicy: "no-referrer-when-downgrade", title: "BPuppy ubicacion" })), /* @__PURE__ */ React.createElement("div", { style: { marginTop: 16, display: "flex", gap: 12, flexWrap: "wrap" } }, /* @__PURE__ */ React.createElement("a", { href: "https://maps.google.com/?q=5604+Kalogridis+Rd+Haines+City+FL+33844", target: "_blank", rel: "noreferrer", className: "btn btn-ghost", style: { fontSize: 13 } }, t(["Ver en Google Maps", "View on Google Maps"])), /* @__PURE__ */ React.createElement("a", { href: "https://www.google.com/maps?cid=10300429461328700851", target: "_blank", rel: "noreferrer", className: "btn btn-dark", style: { fontSize: 13 } }, "\u2B50 ", t(["Dejar resena", "Leave a review"]))))), /* @__PURE__ */ React.createElement("style", null, `
        @keyframes fadeIn { from { opacity:0; transform:translateY(8px); } to { opacity:1; transform:none; } }
        @media (max-width: 768px) {
          .nosotros-hero-grid, .nosotros-historia-grid, .nosotros-impact-grid { grid-template-columns: 1fr !important; }
        }
      `));
}
Object.assign(window, { NosotrosApp, Timeline, ImpactStories });

})();
