const AMAZON_TAG = "bpuppy-20";
const amz = (asin) => `https://www.amazon.com/dp/${asin}?tag=${AMAZON_TAG}`;
const SHOP_CATS = [
  { id: "todos", label: "Todo", emoji: "\u{1F6CD}\uFE0F" },
  { id: "perros", label: "Perros", emoji: "\u{1F415}" },
  { id: "gatos", label: "Gatos", emoji: "\u{1F431}" },
  { id: "trending", label: "\u{1F525} Viral", emoji: "" },
  { id: "grooming", label: "Grooming", emoji: "\u2702\uFE0F" },
  { id: "salud", label: "Salud", emoji: "\u{1F48A}" }
];
const BADGES = {
  viral: { label: "\u{1F525} Viral TikTok", bg: "#FF0050", color: "#fff" },
  amazon: { label: "\u2B50 Top Amazon", bg: "#FF9900", color: "#fff" },
  staff: { label: "\u{1F48E} Recomendado", bg: "#7C3AED", color: "#fff" },
  nuevo: { label: "\u2728 Nuevo", bg: "#1EB87A", color: "#fff" },
  sale: { label: "\u{1F3F7}\uFE0F Oferta", bg: "#E85D75", color: "#fff" }
};
const SHOP_PRODUCTS = [
  // ── PERROS ────────────────────────────────────────────────────────────────
  {
    id: 1,
    cat: "perros",
    name: "KONG Classic \u2014 Juguete Rellenable",
    desc: "El juguete m\xE1s recomendado por entrenadores del mundo. Rellena con mantequilla de man\xED congelada y ocupa a tu perro por horas. Esencial para crate training.",
    price: 13.99,
    rating: 4.8,
    reviews: 89420,
    badge: "staff",
    img: null,
    emoji: "\u{1F7E0}",
    link: amz("B0002AR0I8"),
    source: "amazon",
    video: "dQw4w9WgXcQ",
    // placeholder - replace with real video ID
    tags: ["juguetes", "entrenamiento", "cachorro"],
    blogId: 35
  },
  {
    id: 2,
    cat: "perros",
    name: "FURminator deShedding Tool \u2014 Tama\xF1o L",
    desc: "Reduce el pelo suelto hasta un 90%. La herramienta favorita de groomers profesionales para razas de doble capa: Golden, Lab, Husky, German Shepherd.",
    price: 44.99,
    rating: 4.7,
    reviews: 127800,
    badge: "amazon",
    img: null,
    emoji: "\u{1FAAE}",
    link: amz("B002RL8IY4"),
    source: "amazon",
    tags: ["cepillo", "pelaje", "grooming"],
    blogId: 38
  },
  {
    id: 3,
    cat: "perros",
    name: "PetSafe Easy Walk Harness",
    desc: "El arn\xE9s anti-jale m\xE1s recomendado por entrenadores. La argolla frontal redirige al perro hacia ti cuando jala. Sin presi\xF3n en cuello ni tr\xE1quea.",
    price: 29.95,
    rating: 4.5,
    reviews: 54300,
    badge: "staff",
    img: null,
    emoji: "\u{1F9AE}",
    link: amz("B004LXIY6Y"),
    source: "amazon",
    tags: ["arn\xE9s", "paseo", "entrenamiento"],
    blogId: 35
  },
  {
    id: 4,
    cat: "perros",
    name: "Ruffwear Front Range Harness",
    desc: "El arn\xE9s premium para perros activos. Reflectivo, con almohadillas en puntos de presi\xF3n, clip frontal y dorsal. Perfecto para trail, playa y ciudad.",
    price: 54.95,
    rating: 4.8,
    reviews: 31200,
    badge: "staff",
    img: null,
    emoji: "\u{1F3D4}\uFE0F",
    link: amz("B07GZPMQHQ"),
    source: "amazon",
    tags: ["arn\xE9s", "outdoor", "premium"]
  },
  {
    id: 5,
    cat: "perros",
    name: 'Big Barker Cama Ortop\xE9dica 7"',
    desc: "La cama ortop\xE9dica m\xE1s avalada por veterinarios. Espuma de memoria de 7 pulgadas dise\xF1ada espec\xEDficamente para perros. Reduce dolores articulares en un 42%.",
    price: 189.95,
    rating: 4.8,
    reviews: 12400,
    badge: "staff",
    img: null,
    emoji: "\u{1F6CF}\uFE0F",
    link: amz("B00A42V46I"),
    source: "amazon",
    tags: ["cama", "ortop\xE9dico", "articulaciones"]
  },
  {
    id: 6,
    cat: "perros",
    name: "ThunderShirt Chaleco Anti-Ansiedad",
    desc: "Funciona como un abrazo constante. Reduce la ansiedad en tormentas, fuegos artificiales y viajes en el 80% de los perros seg\xFAn estudios cl\xEDnicos.",
    price: 49.95,
    rating: 4.4,
    reviews: 43100,
    badge: "amazon",
    img: null,
    emoji: "\u26C8\uFE0F",
    link: amz("B00458D0EI"),
    source: "amazon",
    video: "DLzxrzFCyOs",
    tags: ["ansiedad", "truenos", "comportamiento"],
    blogId: 14
  },
  {
    id: 7,
    cat: "perros",
    name: "Comedero Slow Feeder Anti-Ansiedad",
    desc: "Laberintos que ralentizan la ingesta hasta 10x. Previene el bloat (torsi\xF3n g\xE1strica) en razas grandes y reduce la ansiedad alimentaria. Apto lavavajillas.",
    price: 15.99,
    rating: 4.6,
    reviews: 38700,
    badge: "viral",
    img: null,
    emoji: "\u{1F37D}\uFE0F",
    link: amz("B074FFPQP7"),
    source: "amazon",
    video: "LXb3EKWsInQ",
    tags: ["comedero", "nutrici\xF3n", "salud"],
    blogId: 21
  },
  {
    id: 8,
    cat: "perros",
    name: "Nature's Miracle Limpiador Enzim\xE1tico",
    desc: "Elimina manchas Y olores de orina, heces y v\xF3mito en alfombras, madera y telas. Los limpiadores normales solo enmascaran el olor que el perro sigue detectando.",
    price: 22.97,
    rating: 4.6,
    reviews: 71500,
    badge: "amazon",
    img: null,
    emoji: "\u{1F9F4}",
    link: amz("B000BKQTJQ"),
    source: "amazon",
    tags: ["limpieza", "accidentes", "entrenamiento"],
    blogId: 22
  },
  {
    id: 9,
    cat: "perros",
    name: "KONG Wobbler Dispensador de Comida",
    desc: "Hace que tu perro trabaje por su comida. Estimulaci\xF3n mental y f\xEDsica mientras come. Reduce ansiedad y aburrimiento en perros que se quedan solos.",
    price: 19.99,
    rating: 4.6,
    reviews: 29800,
    badge: "staff",
    img: null,
    emoji: "\u{1F3AF}",
    link: amz("B000GCHWSK"),
    source: "amazon",
    tags: ["estimulaci\xF3n", "entretenimiento", "alimentaci\xF3n"],
    blogId: 15
  },
  {
    id: 10,
    cat: "perros",
    name: "Kit de Primeros Auxilios para Mascotas",
    desc: "Todo lo que necesitas para emergencias: vendas, antis\xE9ptico, guantes, term\xF3metro, gu\xEDa de emergencias. El kit m\xE1s completo para llevar al parque o viajes.",
    price: 32.99,
    rating: 4.7,
    reviews: 8900,
    badge: "nuevo",
    img: null,
    emoji: "\u{1FA7A}",
    link: amz("B0BLW2KS7M"),
    source: "amazon",
    tags: ["salud", "emergencia", "viaje"],
    blogId: 20
  },
  {
    id: 11,
    cat: "perros",
    name: "Bolsa Entrenamiento + Premios Freeze-Dried",
    desc: "Combo perfecto para entrenamiento: bolsa de cintura con cierre magn\xE9tico y premios de pollo liofilizado. Un ingrediente, sabor intenso, tama\xF1o perfecto para sesiones.",
    price: 27.99,
    rating: 4.8,
    reviews: 15600,
    badge: "staff",
    img: null,
    emoji: "\u{1F3C5}",
    link: amz("B0068VX1JK"),
    source: "amazon",
    tags: ["entrenamiento", "premios", "obediencia"],
    blogId: 22
  },
  {
    id: 12,
    cat: "perros",
    name: "Botella de Agua Port\xE1til para Perros",
    desc: "Dise\xF1o 2-en-1: botella + bebedero. Aprieta para llenar el recipiente integrado, el perro bebe y el agua sobrante regresa a la botella. Perfecta para caminatas.",
    price: 14.99,
    rating: 4.5,
    reviews: 44200,
    badge: "viral",
    img: null,
    emoji: "\u{1F4A7}",
    link: amz("B019RKFIG0"),
    source: "amazon",
    video: "VXblqMPAMKE",
    tags: ["hidrataci\xF3n", "outdoor", "paseo"],
    blogId: 20
  },
  // ── GATOS ─────────────────────────────────────────────────────────────────
  {
    id: 13,
    cat: "gatos",
    name: "ScoopFree Self-Cleaning Litter Box",
    desc: "Arenero autolimpiante con detecci\xF3n de cristales. Rastrillea autom\xE1ticamente 20 min despu\xE9s de cada uso. Elimina el mal olor por semanas. Compatible con app.",
    price: 199.95,
    rating: 4.3,
    reviews: 18700,
    badge: "viral",
    img: null,
    emoji: "\u{1F6BD}",
    link: amz("B07G3H9YLL"),
    source: "amazon",
    video: "DHMuKPMp4Qg",
    tags: ["arenero", "autom\xE1tico", "higiene"],
    blogId: 36
  },
  {
    id: 14,
    cat: "gatos",
    name: "Drinkwell Fuente de Agua para Gatos",
    desc: "El agua en movimiento estimula la hidrataci\xF3n en gatos. Capacidad 60oz, con filtro de carb\xF3n activo. Reduce riesgo de enfermedad renal cr\xF3nica, la principal causa de muerte en gatos mayores.",
    price: 38.95,
    rating: 4.4,
    reviews: 29400,
    badge: "staff",
    img: null,
    emoji: "\u26F2",
    link: amz("B0754X36WJ"),
    source: "amazon",
    tags: ["hidrataci\xF3n", "salud", "ri\xF1ones"],
    blogId: 36
  },
  {
    id: 15,
    cat: "gatos",
    name: '\xC1rbol Rascador Go Pet Club 62"',
    desc: "Torre de 62 pulgadas con m\xFAltiples plataformas, hamaca, t\xFAnel y rascadores de sisal. Para gatos que necesitan escalar, observar y ejercitarse. Carga hasta 25 lbs por plataforma.",
    price: 89.99,
    rating: 4.3,
    reviews: 41200,
    badge: "amazon",
    img: null,
    emoji: "\u{1F333}",
    link: amz("B07C8GWRQB"),
    source: "amazon",
    tags: ["\xE1rbol", "rascador", "ejercicio"],
    blogId: 36
  },
  {
    id: 16,
    cat: "gatos",
    name: "Varita Interactiva Da Bird",
    desc: "La varita interactiva m\xE1s recomendada por veterinarios conductistas. Las plumas simulan el movimiento de un p\xE1jaro real. 10-15 minutos diarios satisfacen el instinto predatorio del gato.",
    price: 12.99,
    rating: 4.7,
    reviews: 18900,
    badge: "staff",
    img: null,
    emoji: "\u{1FAB6}",
    link: amz("B079JRDP9T"),
    source: "amazon",
    video: "Nh_k5XnXGdA",
    tags: ["juguetes", "ejercicio", "comportamiento"],
    blogId: 36
  },
  {
    id: 17,
    cat: "gatos",
    name: "FURminator deShedding para Gatos",
    desc: "Elimina el pelo suelto antes de que llegue a sof\xE1s y alfombras. Reduce las bolas de pelo hasta un 90%. Para pelo largo y corto con cuchillas diferentes.",
    price: 34.99,
    rating: 4.7,
    reviews: 33100,
    badge: "amazon",
    img: null,
    emoji: "\u{1FAAE}",
    link: amz("B0728NNHQB"),
    source: "amazon",
    tags: ["cepillo", "grooming", "bolas de pelo"],
    blogId: 40
  },
  {
    id: 18,
    cat: "gatos",
    name: "Mochila Transportadora Space Capsule",
    desc: "Mochila con burbuja transparente que se hace viral en TikTok constantemente. El gato puede asomarse mientras viaja. Ventilaci\xF3n superior, f\xE1cil de limpiar. La favorita del aeropuerto.",
    price: 49.99,
    rating: 4.5,
    reviews: 22400,
    badge: "viral",
    img: null,
    emoji: "\u{1F680}",
    link: amz("B07XF4RXNT"),
    source: "amazon",
    video: "MCwHHkuWZSk",
    tags: ["transporte", "viaje", "viral"],
    blogId: 20
  },
  {
    id: 19,
    cat: "gatos",
    name: "Feliway Classic Difusor de Feromonas",
    desc: 'Las feromonas sint\xE9ticas de "hogar feliz" reducen marcaje, ara\xF1azos inapropiados y conflictos entre gatos. Recomendado por el 90% de veterinarios conductuales.',
    price: 39.99,
    rating: 4.2,
    reviews: 14800,
    badge: "staff",
    img: null,
    emoji: "\u{1F60C}",
    link: amz("B0011WQXSY"),
    source: "amazon",
    tags: ["comportamiento", "ansiedad", "feromonas"],
    blogId: 36
  },
  {
    id: 20,
    cat: "gatos",
    name: "Kit de Hierba Gatera (Cat Grass)",
    desc: "Trigo, avena y cebada para que tu gato mastique hierba fresca en casa. Ayuda a la digesti\xF3n y a expulsar bolas de pelo. Crece en 7-10 d\xEDas, kit con semillas y tierra.",
    price: 11.99,
    rating: 4.5,
    reviews: 19200,
    badge: "viral",
    img: null,
    emoji: "\u{1F331}",
    link: amz("B07G97MB27"),
    source: "amazon",
    video: "aSknBRmpSbs",
    tags: ["hierba", "digesti\xF3n", "natural"],
    blogId: 36
  },
  // ── TRENDING VIRAL ────────────────────────────────────────────────────────
  {
    id: 21,
    cat: "trending",
    name: "Furbo 360\xB0 Dog Camera con Treat Toss",
    desc: "C\xE1mara 360\xB0 con seguimiento de movimiento, visi\xF3n nocturna, audio bidireccional y lanzador de premios controlado por app. Habla con tu perro mientras est\xE1s en el trabajo.",
    price: 169,
    rating: 4.4,
    reviews: 28700,
    badge: "viral",
    img: null,
    emoji: "\u{1F4F7}",
    link: amz("B01DW6ZWQM"),
    source: "amazon",
    video: "YkgkThdzX-8",
    tags: ["c\xE1mara", "tecnolog\xEDa", "home office"],
    blogId: 17
  },
  {
    id: 22,
    cat: "trending",
    name: "Embark Dog DNA Test \u2014 Salud + Razas",
    desc: "El test de ADN m\xE1s completo del mercado: m\xE1s de 350 razas, 230+ condiciones de salud gen\xE9ticas, parentesco y rastreo de ancestros. Avalado por la Universidad Cornell.",
    price: 159,
    rating: 4.7,
    reviews: 31400,
    badge: "staff",
    img: null,
    emoji: "\u{1F9EC}",
    link: "https://embarkvet.com",
    source: "brand",
    video: "N3T_tWMH5bA",
    tags: ["ADN", "salud", "razas"],
    blogId: null
  },
  {
    id: 23,
    cat: "trending",
    name: "Fi Series 3 GPS Smart Collar",
    desc: "Rastreo GPS en tiempo real, cuenta pasos, monitorea sue\xF1o y actividad. Bater\xEDa de 3 meses. El Apple Watch de los perros. Funciona en USA, Canad\xE1 y Europa.",
    price: 149,
    rating: 4.6,
    reviews: 12300,
    badge: "viral",
    img: null,
    emoji: "\u{1F4CD}",
    link: "https://tryfi.com",
    source: "brand",
    video: "DxnMhFKe5eE",
    tags: ["GPS", "tecnolog\xEDa", "seguridad"],
    blogId: 17
  },
  {
    id: 24,
    cat: "trending",
    name: "Tractive GPS Tracker \u2014 Perros y Gatos",
    desc: "GPS en tiempo real con historial de actividad. Funciona en m\xE1s de 150 pa\xEDses. Sin contrato, plan mensual $7.99. La opci\xF3n m\xE1s econ\xF3mica y confiable del mercado.",
    price: 49.99,
    rating: 4.3,
    reviews: 41600,
    badge: "amazon",
    img: null,
    emoji: "\u{1F6F0}\uFE0F",
    link: amz("B08GFZWBXJ"),
    source: "amazon",
    video: "XlJfr_F5GYE",
    tags: ["GPS", "rastreo", "seguridad"],
    blogId: 17
  },
  {
    id: 25,
    cat: "trending",
    name: "Alfombra de Lamer (Lick Mat) \u2014 Pack 2",
    desc: "Las almohadillas con texturas distribuyen mantequilla de man\xED, yogurt o comida h\xFAmeda en capas finas. Calman la ansiedad, alivian el aburrimiento y pueden usarse en el ba\xF1o.",
    price: 16.99,
    rating: 4.7,
    reviews: 52100,
    badge: "viral",
    img: null,
    emoji: "\u{1F445}",
    link: amz("B09BSMH9M8"),
    source: "amazon",
    video: "lkHkWIVe3dE",
    tags: ["ansiedad", "entretenimiento", "ba\xF1o"],
    blogId: 15
  },
  {
    id: 26,
    cat: "trending",
    name: "Pet Stroller \u2014 3 Ruedas All-Terrain",
    desc: "Para perros que no pueden caminar largas distancias (senior, post-cirug\xEDa, peque\xF1os). Ruedas todo terreno, f\xE1cil plegado, con cubierta de mosquito y lluvia.",
    price: 89.99,
    rating: 4.4,
    reviews: 17300,
    badge: "viral",
    img: null,
    emoji: "\u{1F6FA}",
    link: amz("B00SGRJXV6"),
    source: "amazon",
    video: "eBG7P-K3aXA",
    tags: ["paseo", "senior", "movilidad"],
    blogId: 11
  },
  {
    id: 27,
    cat: "trending",
    name: "Colchoneta Refrescante de Gel",
    desc: "Activa con el peso del perro sin refrigeraci\xF3n. Reduce la temperatura corporal hasta 10\xB0F. Esencial para razas braquic\xE9falas (Bulldog, Pug) en verano y climas calurosos.",
    price: 28.99,
    rating: 4.3,
    reviews: 36800,
    badge: "viral",
    img: null,
    emoji: "\u2744\uFE0F",
    link: amz("B01N0BA1PX"),
    source: "amazon",
    video: "WsxgSpMFLPs",
    tags: ["verano", "calor", "confort"],
    blogId: 2
  },
  {
    id: 28,
    cat: "trending",
    name: "Rampa para Mascotas \u2014 Anti-deslizante",
    desc: 'Para perros que no deben saltar: senior, razas condrodistr\xF3ficas (Dachshund, Basset), post-operados. Extensible 38"-72", carga hasta 120 lbs.',
    price: 49.99,
    rating: 4.5,
    reviews: 11200,
    badge: "staff",
    img: null,
    emoji: "\u{1F6DD}",
    link: amz("B07FQTPJTK"),
    source: "amazon",
    tags: ["movilidad", "senior", "ortop\xE9dico"],
    blogId: 11
  },
  // ── GROOMING ─────────────────────────────────────────────────────────────
  {
    id: 29,
    cat: "grooming",
    name: "Chris Christensen Ice on Ice \u2014 Spray Detangle",
    desc: "El spray deslanador y brillante favorito de groomers de concurso. Facilita el cepillado, previene nudos, da brillo y acondiciona el pelaje sin grasarlo.",
    price: 24.99,
    rating: 4.8,
    reviews: 7400,
    badge: "staff",
    img: null,
    emoji: "\u2728",
    link: amz("B0007QHFKS"),
    source: "amazon",
    tags: ["grooming", "pelaje", "profesional"],
    blogId: 38
  },
  {
    id: 30,
    cat: "grooming",
    name: "Andis AGC2 2-Speed Clipper \u2014 Profesional",
    desc: "La maquinilla de grooming profesional m\xE1s vendida en USA. Motor quieto, 2 velocidades, genera menos calor que la competencia. Compatible con todas las hojas Andis.",
    price: 119.99,
    rating: 4.7,
    reviews: 15800,
    badge: "amazon",
    img: null,
    emoji: "\u26A1",
    link: amz("B001OXHPNU"),
    source: "amazon",
    tags: ["grooming", "maquinilla", "profesional"],
    blogId: 37
  },
  {
    id: 31,
    cat: "grooming",
    name: "Wahl 4-in-1 Pet Grooming Shampoo \u2014 Natural",
    desc: "Shampoo 4-en-1 sin alcohol, parabenos ni colorantes artificiales. pH balanceado para perros. Disponible en lavanda, avena y eucalipto. Concentrado: rinde 32oz de producto.",
    price: 9.99,
    rating: 4.6,
    reviews: 42300,
    badge: "staff",
    img: null,
    emoji: "\u{1F9F4}",
    link: amz("B000OSGQHU"),
    source: "amazon",
    tags: ["shampoo", "grooming", "natural"],
    blogId: 39
  },
  {
    id: 32,
    cat: "grooming",
    name: "Cortau\xF1as Safari Professional + Lima",
    desc: "Cortau\xF1as de acero inoxidable con guarda de seguridad para evitar cortar demasiado. Incluye lima para suavizar el borde. El m\xE1s recomendado en grupos de entrenadores.",
    price: 16.99,
    rating: 4.5,
    reviews: 28100,
    badge: "staff",
    img: null,
    emoji: "\u{1F485}",
    link: amz("B00101F35A"),
    source: "amazon",
    tags: ["u\xF1as", "grooming", "herramientas"],
    blogId: 40
  },
  // ── SALUD ─────────────────────────────────────────────────────────────────
  {
    id: 33,
    cat: "salud",
    name: "Zesty Paws Omega 3 Bites para Perros",
    desc: "Suplemento de omega-3 con aceite de salm\xF3n de Alaska. Mejora pelaje, articulaciones y sistema inmune. Forma de masticable \u2014 los perros los comen como premio.",
    price: 29.99,
    rating: 4.7,
    reviews: 93400,
    badge: "amazon",
    img: null,
    emoji: "\u{1F41F}",
    link: amz("B01MCVSNTE"),
    source: "amazon",
    tags: ["suplementos", "pelaje", "articulaciones"],
    blogId: 21
  },
  {
    id: 34,
    cat: "salud",
    name: "Vetri-Science Glyco-Flex III \u2014 Cadera y Articulaciones",
    desc: "El suplemento articular m\xE1s recomendado por veterinarios para razas grandes. Glucosamina, condroitina y MSM en concentraci\xF3n terap\xE9utica. Para prevenci\xF3n y tratamiento.",
    price: 44.99,
    rating: 4.8,
    reviews: 21700,
    badge: "staff",
    img: null,
    emoji: "\u{1F9B4}",
    link: amz("B002A5CQXM"),
    source: "amazon",
    tags: ["articulaciones", "cadera", "senior"],
    blogId: 1
  },
  {
    id: 35,
    cat: "salud",
    name: "Tropiclean Fresh Breath Gel Dental",
    desc: "Aplicar con el dedo o con cepillo. Elimina placa y sarro sin necesidad de enjuague. El m\xE9todo m\xE1s f\xE1cil de cuidado dental diario para perros que no toleran el cepillado.",
    price: 17.99,
    rating: 4.5,
    reviews: 35600,
    badge: "viral",
    img: null,
    emoji: "\u{1F9B7}",
    link: amz("B0019CW0HO"),
    source: "amazon",
    video: "YnopHCL1Jk8",
    tags: ["dental", "salud", "prevenci\xF3n"],
    blogId: 6
  }
];
Object.assign(window, { SHOP_PRODUCTS, SHOP_CATS, BADGES, AMAZON_TAG });
